package org.opensim.view;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.prefs.Preferences;
import javax.swing.Action;
import javax.swing.JFileChooser;
import javax.swing.JToggleButton;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.opensim.utils.FileUtils;
import org.opensim.utils.TheApp;
import org.opensim.view.pub.ViewDB;
import vtk.vtkFileOutputWindow;
import org.opensim.utils.Prefs;

/**
 * Top component which displays something.
 */
public class ModelWindowVTKTopComponent extends TopComponent
{
    
    private static final long serialVersionUID = 1L;
    private static int ct = 0; //A counter used to provide names for new models
    private String tabDisplayName;
    Preferences prefs;
    /** path to the icon used by the component and its open action */
//    static final String ICON_PATH = "SET/PATH/TO/ICON/HERE";
    public ModelWindowVTKTopComponent() {
        initComponents();
        setTabDisplayName(NbBundle.getMessage(
                        ModelWindowVTKTopComponent.class,
                        "UnsavedModelNameFormat",
                        new Object[] { new Integer(ct++) }
                ));
//        SwingUtilities.invokeLater(new Runnable(){
 //           public void run() {
                 setName(tabDisplayName);
//            }});

        // Set preferred directory for the TopComponent (to be used for all saving, loading, ...
        prefs = Preferences.userNodeForPackage(TheApp.class);
        
        vtkFileOutputWindow fow = new vtkFileOutputWindow();
        fow.SetFileName("vtklog.log");
        if (fow != null)
           fow.SetInstance(fow);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jRefitModelButton = new javax.swing.JButton();
        jModelWindowToolBar = new javax.swing.JToolBar();
        jPlusXViewButton = new javax.swing.JButton();
        jMinusXViewButton = new javax.swing.JButton();
        jPlusYViewButton = new javax.swing.JButton();
        jMinusYViewButton = new javax.swing.JButton();
        jPlusZViewButton = new javax.swing.JButton();
        jMinusZViewButton = new javax.swing.JButton();
        jTakeSnapshotButton = new javax.swing.JButton();
        jStartStopMovieToggleButton = new javax.swing.JToggleButton();
        openSimCanvas1 = new org.opensim.view.OpenSimCanvas();

        org.openide.awt.Mnemonics.setLocalizedText(jRefitModelButton, "Refit");
        jRefitModelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRefitModelButtonActionPerformed(evt);
            }
        });

        setLayout(new java.awt.BorderLayout());

        String defaultBackgroundColor="0.15, 0.15, 0.15";
        defaultBackgroundColor = Preferences.userNodeForPackage(TheApp.class).get("BackgroundColor", defaultBackgroundColor);
        double[] background = Prefs.getInstance().parseColor(defaultBackgroundColor);
        jModelWindowToolBar.setBackground(new java.awt.Color((int) (background[0]*255), (int) (background[1]*255), (int) (background[2]*255)));
        jModelWindowToolBar.setBorder(null);
        jModelWindowToolBar.setOrientation(1);
        jModelWindowToolBar.setAlignmentY(0.5F);
        jModelWindowToolBar.setBorderPainted(false);
        jModelWindowToolBar.setMaximumSize(new java.awt.Dimension(160, 160));
        jModelWindowToolBar.setMinimumSize(new java.awt.Dimension(20, 20));
        jModelWindowToolBar.setPreferredSize(new java.awt.Dimension(20, 20));
        jPlusXViewButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensim/view/plusXView.png")));
        jPlusXViewButton.setToolTipText("+X View");
        jPlusXViewButton.setBorderPainted(false);
        jPlusXViewButton.setContentAreaFilled(false);
        jPlusXViewButton.setFocusPainted(false);
        jPlusXViewButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jPlusXViewButton.setMaximumSize(new java.awt.Dimension(20, 20));
        jPlusXViewButton.setMinimumSize(new java.awt.Dimension(20, 20));
        jPlusXViewButton.setPreferredSize(new java.awt.Dimension(20, 20));
        jPlusXViewButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensim/view/plusXView_selected.png")));
        jPlusXViewButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensim/view/plusXView_rollover.png")));
        jPlusXViewButton.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensim/view/plusXView_rollover_selected.png")));
        jPlusXViewButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensim/view/plusXView_selected.png")));
        jPlusXViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPlusXViewButtonActionPerformed(evt);
            }
        });

        jModelWindowToolBar.add(jPlusXViewButton);

        jMinusXViewButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensim/view/minusXView.png")));
        jMinusXViewButton.setToolTipText("-X View");
        jMinusXViewButton.setBorderPainted(false);
        jMinusXViewButton.setContentAreaFilled(false);
        jMinusXViewButton.setFocusPainted(false);
        jMinusXViewButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jMinusXViewButton.setMaximumSize(new java.awt.Dimension(20, 20));
        jMinusXViewButton.setMinimumSize(new java.awt.Dimension(20, 20));
        jMinusXViewButton.setPreferredSize(new java.awt.Dimension(20, 20));
        jMinusXViewButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensim/view/minusXView_selected.png")));
        jMinusXViewButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensim/view/minusXView_rollover.png")));
        jMinusXViewButton.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensim/view/minusXView_rollover_selected.png")));
        jMinusXViewButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensim/view/minusXView_selected.png")));
        jMinusXViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMinusXViewButtonActionPerformed(evt);
            }
        });

        jModelWindowToolBar.add(jMinusXViewButton);

        jPlusYViewButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensim/view/plusYView.png")));
        jPlusYViewButton.setToolTipText("+Y View");
        jPlusYViewButton.setBorderPainted(false);
        jPlusYViewButton.setContentAreaFilled(false);
        jPlusYViewButton.setFocusPainted(false);
        jPlusYViewButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jPlusYViewButton.setMaximumSize(new java.awt.Dimension(20, 20));
        jPlusYViewButton.setMinimumSize(new java.awt.Dimension(20, 20));
        jPlusYViewButton.setPreferredSize(new java.awt.Dimension(20, 20));
        jPlusYViewButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensim/view/plusYView_selected.png")));
        jPlusYViewButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensim/view/plusYView_rollover.png")));
        jPlusYViewButton.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensim/view/plusYView_rollover_selected.png")));
        jPlusYViewButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensim/view/plusYView_selected.png")));
        jPlusYViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPlusYViewButtonActionPerformed(evt);
            }
        });

        jModelWindowToolBar.add(jPlusYViewButton);

        jMinusYViewButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensim/view/minusYView.png")));
        jMinusYViewButton.setToolTipText("-Y View");
        jMinusYViewButton.setBorderPainted(false);
        jMinusYViewButton.setContentAreaFilled(false);
        jMinusYViewButton.setFocusPainted(false);
        jMinusYViewButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jMinusYViewButton.setMaximumSize(new java.awt.Dimension(20, 20));
        jMinusYViewButton.setMinimumSize(new java.awt.Dimension(20, 20));
        jMinusYViewButton.setPreferredSize(new java.awt.Dimension(20, 20));
        jMinusYViewButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensim/view/minusYView_selected.png")));
        jMinusYViewButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensim/view/minusYView_rollover.png")));
        jMinusYViewButton.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensim/view/minusYView_rollover_selected.png")));
        jMinusYViewButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensim/view/minusYView_selected.png")));
        jMinusYViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMinusYViewButtonActionPerformed(evt);
            }
        });

        jModelWindowToolBar.add(jMinusYViewButton);

        jPlusZViewButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensim/view/plusZView.png")));
        jPlusZViewButton.setToolTipText("+Z View");
        jPlusZViewButton.setBorderPainted(false);
        jPlusZViewButton.setContentAreaFilled(false);
        jPlusZViewButton.setFocusPainted(false);
        jPlusZViewButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jPlusZViewButton.setMaximumSize(new java.awt.Dimension(20, 20));
        jPlusZViewButton.setMinimumSize(new java.awt.Dimension(20, 20));
        jPlusZViewButton.setPreferredSize(new java.awt.Dimension(20, 20));
        jPlusZViewButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensim/view/plusZView_selected.png")));
        jPlusZViewButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensim/view/plusZView_rollover.png")));
        jPlusZViewButton.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensim/view/plusZView_rollover_selected.png")));
        jPlusZViewButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensim/view/plusZView_selected.png")));
        jPlusZViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPlusZViewButtonActionPerformed(evt);
            }
        });

        jModelWindowToolBar.add(jPlusZViewButton);

        jMinusZViewButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensim/view/minusZView.png")));
        jMinusZViewButton.setToolTipText("-Z View");
        jMinusZViewButton.setBorderPainted(false);
        jMinusZViewButton.setContentAreaFilled(false);
        jMinusZViewButton.setFocusPainted(false);
        jMinusZViewButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jMinusZViewButton.setMaximumSize(new java.awt.Dimension(20, 20));
        jMinusZViewButton.setMinimumSize(new java.awt.Dimension(20, 20));
        jMinusZViewButton.setPreferredSize(new java.awt.Dimension(20, 20));
        jMinusZViewButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensim/view/minusZView_selected.png")));
        jMinusZViewButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensim/view/minusZView_rollover.png")));
        jMinusZViewButton.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensim/view/minusZView_rollover_selected.png")));
        jMinusZViewButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensim/view/minusZView_selected.png")));
        jMinusZViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMinusZViewButtonActionPerformed(evt);
            }
        });

        jModelWindowToolBar.add(jMinusZViewButton);

        jTakeSnapshotButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensim/view/stillCamera.png")));
        jTakeSnapshotButton.setToolTipText("Save As Image");
        jTakeSnapshotButton.setBorderPainted(false);
        jTakeSnapshotButton.setContentAreaFilled(false);
        jTakeSnapshotButton.setFocusPainted(false);
        jTakeSnapshotButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jTakeSnapshotButton.setMaximumSize(new java.awt.Dimension(20, 20));
        jTakeSnapshotButton.setMinimumSize(new java.awt.Dimension(20, 20));
        jTakeSnapshotButton.setPreferredSize(new java.awt.Dimension(20, 20));
        jTakeSnapshotButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensim/view/stillCamera_selected.png")));
        jTakeSnapshotButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensim/view/stillCamera_rollover.png")));
        jTakeSnapshotButton.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensim/view/stillCamera_rollover_selected.png")));
        jTakeSnapshotButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensim/view/stillCamera_selected.png")));
        jTakeSnapshotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTakeSnapshotButtonActionPerformed(evt);
            }
        });

        jModelWindowToolBar.add(jTakeSnapshotButton);

        jStartStopMovieToggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensim/view/movieCamera.png")));
        jStartStopMovieToggleButton.setToolTipText("Start/Stop Save As Move");
        jStartStopMovieToggleButton.setBorderPainted(false);
        jStartStopMovieToggleButton.setContentAreaFilled(false);
        jStartStopMovieToggleButton.setFocusPainted(false);
        jStartStopMovieToggleButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jStartStopMovieToggleButton.setMaximumSize(new java.awt.Dimension(20, 20));
        jStartStopMovieToggleButton.setMinimumSize(new java.awt.Dimension(20, 20));
        jStartStopMovieToggleButton.setPreferredSize(new java.awt.Dimension(20, 20));
        jStartStopMovieToggleButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensim/view/movieCamera_selected.png")));
        jStartStopMovieToggleButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensim/view/movieCamera_rollover.png")));
        jStartStopMovieToggleButton.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensim/view/movieCamera_rollover_selected.png")));
        jStartStopMovieToggleButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensim/view/movieCamera_selected.png")));
        jStartStopMovieToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStartStopMovieToggleButtonActionPerformed(evt);
                jToggleButton1ActionPerformed(evt);
            }
        });

        jModelWindowToolBar.add(jStartStopMovieToggleButton);

        add(jModelWindowToolBar, java.awt.BorderLayout.EAST);

        add(openSimCanvas1, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents

    private void jPlusZViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPlusZViewButtonActionPerformed
// TODO add your handling code here:
        openSimCanvas1.applyCameraPlusZ();
    }//GEN-LAST:event_jPlusZViewButtonActionPerformed

    private void jPlusYViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPlusYViewButtonActionPerformed
// TODO add your handling code here:
        openSimCanvas1.applyCameraPlusY();
    }//GEN-LAST:event_jPlusYViewButtonActionPerformed

    private void jPlusXViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPlusXViewButtonActionPerformed
// TODO add your handling code here:
        openSimCanvas1.applyCameraPlusX();
    }//GEN-LAST:event_jPlusXViewButtonActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jStartStopMovieToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStartStopMovieToggleButtonActionPerformed
// TODO add your handling code here:
        javax.swing.JToggleButton btn = (javax.swing.JToggleButton)(evt.getSource());
        if (btn.getModel().isSelected()){
            String fileName = FileUtils.getInstance().browseForFilename(".avi", "Movie file to create", false);
            //System.out.println("Create movie to file"+fileName);
            if (fileName!=null){
                // Append .avi to the end if not done by user
                if (!fileName.endsWith(".avi"))
                    fileName = fileName+".avi";
                getCanvas().createMovie(fileName);
            }
            else
                btn.getModel().setSelected(false);
         }
        else{
            getCanvas().finishMovie();
            //System.out.println("Finish movie");
        }
    }//GEN-LAST:event_jStartStopMovieToggleButtonActionPerformed

    private void jMinusXViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMinusXViewButtonActionPerformed
// TODO add your handling code here:
      openSimCanvas1.applyCameraMinusX();
    }//GEN-LAST:event_jMinusXViewButtonActionPerformed

   private void jMinusZViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMinusZViewButtonActionPerformed
// TODO add your handling code here:
      openSimCanvas1.applyCameraMinusZ();
   }//GEN-LAST:event_jMinusZViewButtonActionPerformed

   private void jMinusYViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMinusYViewButtonActionPerformed
// TODO add your handling code here:
      openSimCanvas1.applyCameraMinusY();
   }//GEN-LAST:event_jMinusYViewButtonActionPerformed

    private void jTakeSnapshotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTakeSnapshotButtonActionPerformed
// TODO add your handling code here:
       String defaultDir="";
       defaultDir = Preferences.userNodeForPackage(TheApp.class).get("WorkDirectory", defaultDir);
        final JFileChooser dlog = new JFileChooser(defaultDir);
        
        if (dlog.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
            String fullPath = dlog.getSelectedFile().getAbsolutePath();
            if (! fullPath.toLowerCase().endsWith(".tiff")){
                fullPath = dlog.getSelectedFile().getAbsolutePath()+".tiff";
            }
            getCanvas().HardCopy(fullPath, 1);
        }
    }//GEN-LAST:event_jTakeSnapshotButtonActionPerformed

    private void jRefitModelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRefitModelButtonActionPerformed
// TODO add your handling code here:
        getCanvas().resetCamera();
        getCanvas().Render();
    }//GEN-LAST:event_jRefitModelButtonActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jMinusXViewButton;
    private javax.swing.JButton jMinusYViewButton;
    private javax.swing.JButton jMinusZViewButton;
    private javax.swing.JToolBar jModelWindowToolBar;
    private javax.swing.JButton jPlusXViewButton;
    private javax.swing.JButton jPlusYViewButton;
    private javax.swing.JButton jPlusZViewButton;
    private javax.swing.JButton jRefitModelButton;
    private javax.swing.JToggleButton jStartStopMovieToggleButton;
    private javax.swing.JButton jTakeSnapshotButton;
    private org.opensim.view.OpenSimCanvas openSimCanvas1;
    // End of variables declaration//GEN-END:variables
    
    public int getPersistenceType() {
        return TopComponent.PERSISTENCE_NEVER;
    }
        
    public String preferredID() {
        return "Model";
    }     
    
    public String getDisplayName()
    {
        return tabDisplayName;
    }
    
    /**
     * Potentially there could be multiple canvases inserted into this top component,
     * Use an accessor method just incase 
     */
    public org.opensim.view.OpenSimCanvas getCanvas() {
        return openSimCanvas1;
    }
    
    public Action[] getActions(){
        ViewReplicateAction act1 = new ViewReplicateAction();   // New...
        ViewEditAction act2 = new ViewEditAction(); //Edit...
                         
        return (new Action[]{act1,act2});
    };

    protected void componentActivated() {
        super.componentActivated();
        ViewDB.getInstance().setCurrentModelWindow(this);
    }

    /**
     * Window closing, remove self from ViewDB
     **/
    protected void componentClosed() {
        super.componentClosed();
        ViewDB.getInstance().removeWindow(this);
    }

    public void setTabDisplayName(String tabDisplayName) {
        this.tabDisplayName = tabDisplayName;
    }

}
