/*
 * ObjectEditorJDialog.java
 *
 * Created on July 17, 2006, 3:47 PM
 */

package org.opensim.view;

import javax.swing.JDialog;
import org.opensim.modeling.OpenSimObject;
import org.opensim.view.editors.ObjectPropertyViewerPanel;

/**
 *
 * @author  Ayman
 */
public class ObjectEditorJDialog extends JDialog {
    OpenSimObject   obj;
    OpenSimCanvas   canvas;
    
    /** Creates new form ObjectEditorJDialog */
    public ObjectEditorJDialog(boolean modal, OpenSimObject objectToEdit, OpenSimCanvas canvas) {
        //Object innerPane, String title, boolean isModal, ActionListener bl
        //super(new ObjectPropertyViewerPanel(objectToEdit, false), "Edit an Object", true, null);
        obj = objectToEdit;
        this.canvas = canvas;
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        VisualEditPanel = new javax.swing.JPanel();
        OpacityLabel = new javax.swing.JLabel();
        ObjectNameLabel = new javax.swing.JLabel();
        ObjectNameText = new javax.swing.JTextField();
        OpacitySlider = new javax.swing.JSlider();
        ColorLabel = new javax.swing.JLabel();
        jChooseColorBtn = new javax.swing.JButton();
        ObjectTypeLabel = new javax.swing.JLabel();
        ObjectTypeText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jPanel1.setLayout(new java.awt.BorderLayout());

        OpacityLabel.setText("Opacity:");

        ObjectNameLabel.setText("Object Name:");

        ObjectNameText.setEditable(false);
        ObjectNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObjectNameTextActionPerformed(evt);
            }
        });

        ColorLabel.setText("Color:");

        jChooseColorBtn.setText("Choose...");
        jChooseColorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChooseColorBtnActionPerformed(evt);
            }
        });

        ObjectTypeLabel.setText("Object Type");

        ObjectTypeText.setEditable(false);
        ObjectTypeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObjectTypeTextActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout VisualEditPanelLayout = new org.jdesktop.layout.GroupLayout(VisualEditPanel);
        VisualEditPanel.setLayout(VisualEditPanelLayout);
        VisualEditPanelLayout.setHorizontalGroup(
            VisualEditPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(VisualEditPanelLayout.createSequentialGroup()
                .add(20, 20, 20)
                .add(VisualEditPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(VisualEditPanelLayout.createSequentialGroup()
                        .add(VisualEditPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(OpacityLabel)
                            .add(ObjectNameLabel)
                            .add(ObjectTypeLabel))
                        .add(54, 54, 54)
                        .add(VisualEditPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(OpacitySlider, 0, 0, Short.MAX_VALUE)
                            .add(ObjectTypeText)
                            .add(ObjectNameText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)))
                    .add(VisualEditPanelLayout.createSequentialGroup()
                        .add(ColorLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jChooseColorBtn)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        VisualEditPanelLayout.setVerticalGroup(
            VisualEditPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(VisualEditPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(VisualEditPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, VisualEditPanelLayout.createSequentialGroup()
                        .add(OpacityLabel)
                        .add(11, 11, 11))
                    .add(VisualEditPanelLayout.createSequentialGroup()
                        .add(VisualEditPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(ObjectNameText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(ObjectNameLabel))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(VisualEditPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(ObjectTypeText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(ObjectTypeLabel))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(OpacitySlider, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(19, 19, 19))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, VisualEditPanelLayout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .add(VisualEditPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(ColorLabel)
                    .add(jChooseColorBtn))
                .addContainerGap())
        );
        jPanel1.add(VisualEditPanel, java.awt.BorderLayout.NORTH);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(269, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ObjectTypeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObjectTypeTextActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_ObjectTypeTextActionPerformed

    private void jChooseColorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChooseColorBtnActionPerformed
// TODO add your handling code here:
        /*JColorChooser objectColorChooser = new JColorChooser();
        Color newColor = objectColorChooser.showDialog(this., "Select new object color", canvas.getBackground());
        if (newColor != null){
            float[] colorComponents = newColor.getRGBComponents(null);
            double[] dColorComponents = new double[]{colorComponents[0], colorComponents[1], colorComponents[2]};
            canvas.setObjectColor(obj, dColorComponents);
            canvas.repaint();
        }*/
    }//GEN-LAST:event_jChooseColorBtnActionPerformed

    private void ObjectNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObjectNameTextActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_ObjectNameTextActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ObjectEditorJDialog(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ColorLabel;
    private javax.swing.JLabel ObjectNameLabel;
    private javax.swing.JTextField ObjectNameText;
    private javax.swing.JLabel ObjectTypeLabel;
    private javax.swing.JTextField ObjectTypeText;
    private javax.swing.JLabel OpacityLabel;
    private javax.swing.JSlider OpacitySlider;
    private javax.swing.JPanel VisualEditPanel;
    private javax.swing.JButton jChooseColorBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
}
