/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class AbstractWrapObject extends OpenSimObject {
  private long swigCPtr;

  public AbstractWrapObject(long cPtr, boolean cMemoryOwn) {
    super(opensimModelJNI.SWIGStorageUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(AbstractWrapObject obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      opensimModelJNI.delete_AbstractWrapObject(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public OpenSimObject copy() {
    long cPtr = opensimModelJNI.AbstractWrapObject_copy__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new OpenSimObject(cPtr, false);
  }

  public void copyData(AbstractWrapObject aWrapObject) {
    opensimModelJNI.AbstractWrapObject_copyData(swigCPtr, this, AbstractWrapObject.getCPtr(aWrapObject), aWrapObject);
  }

  public void scale(SWIGTYPE_p_SimTK__Vec3 aScaleFactors) {
    opensimModelJNI.AbstractWrapObject_scale(swigCPtr, this, SWIGTYPE_p_SimTK__Vec3.getCPtr(aScaleFactors));
  }

  public void setup(AbstractDynamicsEngine aEngine, AbstractBody aBody) {
    opensimModelJNI.AbstractWrapObject_setup(swigCPtr, this, AbstractDynamicsEngine.getCPtr(aEngine), aEngine, AbstractBody.getCPtr(aBody), aBody);
  }

  public AbstractBody getBody() {
    long cPtr = opensimModelJNI.AbstractWrapObject_getBody(swigCPtr, this);
    return (cPtr == 0) ? null : new AbstractBody(cPtr, false);
  }

  public SWIGTYPE_p_double getXYZBodyRotation() {
    long cPtr = opensimModelJNI.AbstractWrapObject_getXYZBodyRotation(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public SWIGTYPE_p_double getTranslation() {
    long cPtr = opensimModelJNI.AbstractWrapObject_getTranslation(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public boolean getActive() {
    return opensimModelJNI.AbstractWrapObject_getActive(swigCPtr, this);
  }

  public boolean getActiveUseDefault() {
    return opensimModelJNI.AbstractWrapObject_getActiveUseDefault(swigCPtr, this);
  }

  public String getQuadrantName() {
    return opensimModelJNI.AbstractWrapObject_getQuadrantName(swigCPtr, this);
  }

  public boolean getQuadrantNameUseDefault() {
    return opensimModelJNI.AbstractWrapObject_getQuadrantNameUseDefault(swigCPtr, this);
  }

  public void setQuadrantName(String aName) {
    opensimModelJNI.AbstractWrapObject_setQuadrantName(swigCPtr, this, aName);
  }

  public String getWrapTypeName() {
    return opensimModelJNI.AbstractWrapObject_getWrapTypeName(swigCPtr, this);
  }

  public String getDimensionsString() {
    return opensimModelJNI.AbstractWrapObject_getDimensionsString(swigCPtr, this);
  }

  public int wrapMuscleSegment(MusclePoint aPoint1, MusclePoint aPoint2, MuscleWrap aMuscleWrap, SWIGTYPE_p_OpenSim__WrapResult aWrapResult) {
    return opensimModelJNI.AbstractWrapObject_wrapMuscleSegment(swigCPtr, this, MusclePoint.getCPtr(aPoint1), aPoint1, MusclePoint.getCPtr(aPoint2), aPoint2, MuscleWrap.getCPtr(aMuscleWrap), aMuscleWrap, SWIGTYPE_p_OpenSim__WrapResult.getCPtr(aWrapResult));
  }

  public int wrapLine(SWIGTYPE_p_SimTK__Vec3 aPoint1, SWIGTYPE_p_SimTK__Vec3 aPoint2, MuscleWrap aMuscleWrap, SWIGTYPE_p_OpenSim__WrapResult aWrapResult, SWIGTYPE_p_bool aFlag) {
    return opensimModelJNI.AbstractWrapObject_wrapLine(swigCPtr, this, SWIGTYPE_p_SimTK__Vec3.getCPtr(aPoint1), SWIGTYPE_p_SimTK__Vec3.getCPtr(aPoint2), MuscleWrap.getCPtr(aMuscleWrap), aMuscleWrap, SWIGTYPE_p_OpenSim__WrapResult.getCPtr(aWrapResult), SWIGTYPE_p_bool.getCPtr(aFlag));
  }

  public VisibleObject getDisplayer() {
    long cPtr = opensimModelJNI.AbstractWrapObject_getDisplayer(swigCPtr, this);
    return (cPtr == 0) ? null : new VisibleObject(cPtr, false);
  }

  public void updateGeometry() {
    opensimModelJNI.AbstractWrapObject_updateGeometry(swigCPtr, this);
  }

  public static boolean isKindOf(String type) {
    return opensimModelJNI.AbstractWrapObject_isKindOf(type);
  }

  public boolean isA(String type) {
    return opensimModelJNI.AbstractWrapObject_isA(swigCPtr, this, type);
  }

  public static AbstractWrapObject safeDownCast(OpenSimObject obj) {
    long cPtr = opensimModelJNI.AbstractWrapObject_safeDownCast(OpenSimObject.getCPtr(obj), obj);
    return (cPtr == 0) ? null : new AbstractWrapObject(cPtr, false);
  }

  public void copy(OpenSimObject aObject) {
    opensimModelJNI.AbstractWrapObject_copy__SWIG_1(swigCPtr, this, OpenSimObject.getCPtr(aObject), aObject);
  }

  public final static class WrapQuadrant {
    public final static WrapQuadrant allQuadrants = new WrapQuadrant("allQuadrants");
    public final static WrapQuadrant negativeX = new WrapQuadrant("negativeX");
    public final static WrapQuadrant positiveX = new WrapQuadrant("positiveX");
    public final static WrapQuadrant negativeY = new WrapQuadrant("negativeY");
    public final static WrapQuadrant positiveY = new WrapQuadrant("positiveY");
    public final static WrapQuadrant negativeZ = new WrapQuadrant("negativeZ");
    public final static WrapQuadrant positiveZ = new WrapQuadrant("positiveZ");

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static WrapQuadrant swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + WrapQuadrant.class + " with value " + swigValue);
    }

    private WrapQuadrant(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private WrapQuadrant(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private WrapQuadrant(String swigName, WrapQuadrant swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static WrapQuadrant[] swigValues = { allQuadrants, negativeX, positiveX, negativeY, positiveY, negativeZ, positiveZ };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

  public final static class WrapAction {
    public final static WrapAction noWrap = new WrapAction("noWrap");
    public final static WrapAction insideRadius = new WrapAction("insideRadius");
    public final static WrapAction wrapped = new WrapAction("wrapped");
    public final static WrapAction mandatoryWrap = new WrapAction("mandatoryWrap");

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static WrapAction swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + WrapAction.class + " with value " + swigValue);
    }

    private WrapAction(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private WrapAction(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private WrapAction(String swigName, WrapAction swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static WrapAction[] swigValues = { noWrap, insideRadius, wrapped, mandatoryWrap };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

}
