/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class AbstractTransformAxis extends OpenSimObject {
  private long swigCPtr;

  public AbstractTransformAxis(long cPtr, boolean cMemoryOwn) {
    super(opensimModelJNI.SWIGStorageUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(AbstractTransformAxis obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      opensimModelJNI.delete_AbstractTransformAxis(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public OpenSimObject copy() {
    long cPtr = opensimModelJNI.AbstractTransformAxis_copy__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new OpenSimObject(cPtr, false);
  }

  public void copyData(AbstractTransformAxis aDof) {
    opensimModelJNI.AbstractTransformAxis_copyData(swigCPtr, this, AbstractTransformAxis.getCPtr(aDof), aDof);
  }

  public void setup(AbstractDynamicsEngine aEngine, AbstractJoint aJoint) {
    opensimModelJNI.AbstractTransformAxis_setup(swigCPtr, this, AbstractDynamicsEngine.getCPtr(aEngine), aEngine, AbstractJoint.getCPtr(aJoint), aJoint);
  }

  public void setCoordinateName(String aName) {
    opensimModelJNI.AbstractTransformAxis_setCoordinateName(swigCPtr, this, aName);
  }

  public String getCoordinateName() {
    return opensimModelJNI.AbstractTransformAxis_getCoordinateName(swigCPtr, this);
  }

  public AbstractTransformAxis.MotionType getMotionType() {
    return AbstractTransformAxis.MotionType.swigToEnum(opensimModelJNI.AbstractTransformAxis_getMotionType(swigCPtr, this));
  }

  public void setAxis(SWIGTYPE_p_SimTK__Vec3 axis) {
    opensimModelJNI.AbstractTransformAxis_setAxis(swigCPtr, this, SWIGTYPE_p_SimTK__Vec3.getCPtr(axis));
  }

  public void getAxis(SWIGTYPE_p_SimTK__Vec3 axis) {
    opensimModelJNI.AbstractTransformAxis_getAxis__SWIG_0(swigCPtr, this, SWIGTYPE_p_SimTK__Vec3.getCPtr(axis));
  }

  public void getAxis(double[] rAxis) {
    opensimModelJNI.AbstractTransformAxis_getAxis__SWIG_1(swigCPtr, this, rAxis);
  }

  public double getValue() {
    return opensimModelJNI.AbstractTransformAxis_getValue(swigCPtr, this);
  }

  public AbstractCoordinate getCoordinate() {
    long cPtr = opensimModelJNI.AbstractTransformAxis_getCoordinate(swigCPtr, this);
    return (cPtr == 0) ? null : new AbstractCoordinate(cPtr, false);
  }

  public Function getFunction() {
    long cPtr = opensimModelJNI.AbstractTransformAxis_getFunction(swigCPtr, this);
    return (cPtr == 0) ? null : new Function(cPtr, false);
  }

  public void setFunction(Function aFunction) {
    opensimModelJNI.AbstractTransformAxis_setFunction(swigCPtr, this, Function.getCPtr(aFunction), aFunction);
  }

  public AbstractJoint getJoint() {
    long cPtr = opensimModelJNI.AbstractTransformAxis_getJoint(swigCPtr, this);
    return (cPtr == 0) ? null : new AbstractJoint(cPtr, false);
  }

  public static boolean isKindOf(String type) {
    return opensimModelJNI.AbstractTransformAxis_isKindOf(type);
  }

  public boolean isA(String type) {
    return opensimModelJNI.AbstractTransformAxis_isA(swigCPtr, this, type);
  }

  public static AbstractTransformAxis safeDownCast(OpenSimObject obj) {
    long cPtr = opensimModelJNI.AbstractTransformAxis_safeDownCast(OpenSimObject.getCPtr(obj), obj);
    return (cPtr == 0) ? null : new AbstractTransformAxis(cPtr, false);
  }

  public void copy(OpenSimObject aObject) {
    opensimModelJNI.AbstractTransformAxis_copy__SWIG_1(swigCPtr, this, OpenSimObject.getCPtr(aObject), aObject);
  }

  public final static class MotionType {
    public final static MotionType Translational = new MotionType("Translational");
    public final static MotionType Rotational = new MotionType("Rotational");

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static MotionType swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + MotionType.class + " with value " + swigValue);
    }

    private MotionType(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private MotionType(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private MotionType(String swigName, MotionType swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static MotionType[] swigValues = { Translational, Rotational };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

}
