/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class AbstractJoint extends OpenSimObject {
  private long swigCPtr;

  public AbstractJoint(long cPtr, boolean cMemoryOwn) {
    super(opensimModelJNI.SWIGStorageUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(AbstractJoint obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      opensimModelJNI.delete_AbstractJoint(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public OpenSimObject copy() {
    long cPtr = opensimModelJNI.AbstractJoint_copy__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new OpenSimObject(cPtr, false);
  }

  public void copyData(AbstractJoint aJoint) {
    opensimModelJNI.AbstractJoint_copyData(swigCPtr, this, AbstractJoint.getCPtr(aJoint), aJoint);
  }

  public AbstractDynamicsEngine getDynamicsEngine() {
    long cPtr = opensimModelJNI.AbstractJoint_getDynamicsEngine(swigCPtr, this);
    return (cPtr == 0) ? null : new AbstractDynamicsEngine(cPtr, false);
  }

  public void setup(AbstractDynamicsEngine aEngine) {
    opensimModelJNI.AbstractJoint_setup(swigCPtr, this, AbstractDynamicsEngine.getCPtr(aEngine), aEngine);
  }

  public void invalidate() {
    opensimModelJNI.AbstractJoint_invalidate(swigCPtr, this);
  }

  public TransformAxisSet getTransformAxisSet() {
    long cPtr = opensimModelJNI.AbstractJoint_getTransformAxisSet(swigCPtr, this);
    return (cPtr == 0) ? null : new TransformAxisSet(cPtr, false);
  }

  public AbstractBody getBody() {
    long cPtr = opensimModelJNI.AbstractJoint_getBody(swigCPtr, this);
    return (cPtr == 0) ? null : new AbstractBody(cPtr, false);
  }

  public AbstractBody getParentBody() {
    long cPtr = opensimModelJNI.AbstractJoint_getParentBody(swigCPtr, this);
    return (cPtr == 0) ? null : new AbstractBody(cPtr, false);
  }

  public void setLocationInParent(SWIGTYPE_p_SimTK__Vec3 aLocation) {
    opensimModelJNI.AbstractJoint_setLocationInParent(swigCPtr, this, SWIGTYPE_p_SimTK__Vec3.getCPtr(aLocation));
  }

  public void getLocationInParent(SWIGTYPE_p_SimTK__Vec3 rLocation) {
    opensimModelJNI.AbstractJoint_getLocationInParent__SWIG_0(swigCPtr, this, SWIGTYPE_p_SimTK__Vec3.getCPtr(rLocation));
  }

  public void getLocationInParent(double[] rLocation) {
    opensimModelJNI.AbstractJoint_getLocationInParent__SWIG_1(swigCPtr, this, rLocation);
  }

  public void setLocationInChild(SWIGTYPE_p_SimTK__Vec3 aLocation) {
    opensimModelJNI.AbstractJoint_setLocationInChild(swigCPtr, this, SWIGTYPE_p_SimTK__Vec3.getCPtr(aLocation));
  }

  public void getLocationInChild(SWIGTYPE_p_SimTK__Vec3 rLocation) {
    opensimModelJNI.AbstractJoint_getLocationInChild__SWIG_0(swigCPtr, this, SWIGTYPE_p_SimTK__Vec3.getCPtr(rLocation));
  }

  public void getLocationInChild(double[] rLocation) {
    opensimModelJNI.AbstractJoint_getLocationInChild__SWIG_1(swigCPtr, this, rLocation);
  }

  public Transform getForwardTransform() {
    return new Transform(opensimModelJNI.AbstractJoint_getForwardTransform(swigCPtr, this), false);
  }

  public Transform getInverseTransform() {
    return new Transform(opensimModelJNI.AbstractJoint_getInverseTransform(swigCPtr, this), false);
  }

  public boolean isCoordinateUsed(AbstractCoordinate aCoordinate) {
    return opensimModelJNI.AbstractJoint_isCoordinateUsed(swigCPtr, this, AbstractCoordinate.getCPtr(aCoordinate), aCoordinate);
  }

  public boolean hasXYZAxes() {
    return opensimModelJNI.AbstractJoint_hasXYZAxes(swigCPtr, this);
  }

  public void scale(ScaleSet aScaleSet) {
    opensimModelJNI.AbstractJoint_scale(swigCPtr, this, ScaleSet.getCPtr(aScaleSet), aScaleSet);
  }

  public void setDynamicsEngine(AbstractDynamicsEngine aEngine) {
    opensimModelJNI.AbstractJoint_setDynamicsEngine(swigCPtr, this, AbstractDynamicsEngine.getCPtr(aEngine), aEngine);
  }

  public static boolean isKindOf(String type) {
    return opensimModelJNI.AbstractJoint_isKindOf(type);
  }

  public boolean isA(String type) {
    return opensimModelJNI.AbstractJoint_isA(swigCPtr, this, type);
  }

  public static AbstractJoint safeDownCast(OpenSimObject obj) {
    long cPtr = opensimModelJNI.AbstractJoint_safeDownCast(OpenSimObject.getCPtr(obj), obj);
    return (cPtr == 0) ? null : new AbstractJoint(cPtr, false);
  }

  public void copy(OpenSimObject aObject) {
    opensimModelJNI.AbstractJoint_copy__SWIG_1(swigCPtr, this, OpenSimObject.getCPtr(aObject), aObject);
  }

}
