/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class AnalyticGeometry extends Geometry {
  private long swigCPtr;

  public AnalyticGeometry(long cPtr, boolean cMemoryOwn) {
    super(opensimModelJNI.SWIGStorageUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(AnalyticGeometry obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      opensimModelJNI.delete_AnalyticGeometry(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public AnalyticGeometry(Geometry.GeometryType aGeometricType) {
    this(opensimModelJNI.new_AnalyticGeometry(aGeometricType.swigValue()), true);
  }

  public void setQuadrants(boolean[] quadrants) {
    opensimModelJNI.AnalyticGeometry_setQuadrants(swigCPtr, quadrants);
  }

  public void getQuadrants(boolean[] quadrants) {
    opensimModelJNI.AnalyticGeometry_getQuadrants(swigCPtr, quadrants);
  }

  public boolean isPiece() {
    return opensimModelJNI.AnalyticGeometry_isPiece(swigCPtr);
  }

  public static AnalyticGeometry dynamic_cast(Geometry geometry) {
    long cPtr = opensimModelJNI.AnalyticGeometry_dynamic_cast(Geometry.getCPtr(geometry));
    return (cPtr == 0) ? null : new AnalyticGeometry(cPtr, false);
  }

}
