/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class ArrayInt {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public ArrayInt(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ArrayInt obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      opensimModelJNI.delete_ArrayInt(swigCPtr);
    }
    swigCPtr = 0;
  }

  public ArrayInt(int aDefaultValue, int aSize, int aCapacity) {
    this(opensimModelJNI.new_ArrayInt__SWIG_0(aDefaultValue, aSize, aCapacity), true);
  }

  public ArrayInt(int aDefaultValue, int aSize) {
    this(opensimModelJNI.new_ArrayInt__SWIG_1(aDefaultValue, aSize), true);
  }

  public ArrayInt(int aDefaultValue) {
    this(opensimModelJNI.new_ArrayInt__SWIG_2(aDefaultValue), true);
  }

  public ArrayInt() {
    this(opensimModelJNI.new_ArrayInt__SWIG_3(), true);
  }

  public ArrayInt(ArrayInt aArray) {
    this(opensimModelJNI.new_ArrayInt__SWIG_4(ArrayInt.getCPtr(aArray)), true);
  }

  public boolean computeNewCapacity(int aMinCapacity, SWIGTYPE_p_int rNewCapacity) {
    return opensimModelJNI.ArrayInt_computeNewCapacity(swigCPtr, aMinCapacity, SWIGTYPE_p_int.getCPtr(rNewCapacity));
  }

  public boolean ensureCapacity(int aCapacity) {
    return opensimModelJNI.ArrayInt_ensureCapacity(swigCPtr, aCapacity);
  }

  public void trim() {
    opensimModelJNI.ArrayInt_trim(swigCPtr);
  }

  public int getCapacity() {
    return opensimModelJNI.ArrayInt_getCapacity(swigCPtr);
  }

  public void setCapacityIncrement(int aIncrement) {
    opensimModelJNI.ArrayInt_setCapacityIncrement(swigCPtr, aIncrement);
  }

  public int getCapacityIncrement() {
    return opensimModelJNI.ArrayInt_getCapacityIncrement(swigCPtr);
  }

  public boolean setSize(int aSize) {
    return opensimModelJNI.ArrayInt_setSize(swigCPtr, aSize);
  }

  public int getSize() {
    return opensimModelJNI.ArrayInt_getSize(swigCPtr);
  }

  public int append(int aValue) {
    return opensimModelJNI.ArrayInt_append__SWIG_0(swigCPtr, aValue);
  }

  public int append(ArrayInt aArray) {
    return opensimModelJNI.ArrayInt_append__SWIG_1(swigCPtr, ArrayInt.getCPtr(aArray));
  }

  public int append(int aSize, SWIGTYPE_p_int aArray) {
    return opensimModelJNI.ArrayInt_append__SWIG_2(swigCPtr, aSize, SWIGTYPE_p_int.getCPtr(aArray));
  }

  public int insert(int aIndex, int aValue) {
    return opensimModelJNI.ArrayInt_insert(swigCPtr, aIndex, aValue);
  }

  public int remove(int aIndex) {
    return opensimModelJNI.ArrayInt_remove(swigCPtr, aIndex);
  }

  public void set(int aIndex, int aValue) {
    opensimModelJNI.ArrayInt_set(swigCPtr, aIndex, aValue);
  }

  public SWIGTYPE_p_int get() {
    long cPtr = opensimModelJNI.ArrayInt_get__SWIG_0(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public SWIGTYPE_p_int get(int aIndex) {
    return new SWIGTYPE_p_int(opensimModelJNI.ArrayInt_get__SWIG_1(swigCPtr, aIndex), false);
  }

  public int getitem(int index) {
    return opensimModelJNI.ArrayInt_getitem(swigCPtr, index);
  }

  public void setitem(int index, int val) {
    opensimModelJNI.ArrayInt_setitem(swigCPtr, index, val);
  }

  public SWIGTYPE_p_int getLast() {
    return new SWIGTYPE_p_int(opensimModelJNI.ArrayInt_getLast(swigCPtr), false);
  }

  public int findIndex(int aValue) {
    return opensimModelJNI.ArrayInt_findIndex(swigCPtr, aValue);
  }

  public int rfindIndex(int aValue) {
    return opensimModelJNI.ArrayInt_rfindIndex(swigCPtr, aValue);
  }

  public int searchBinary(int aValue, boolean aFindFirst, int aLo, int aHi) {
    return opensimModelJNI.ArrayInt_searchBinary__SWIG_0(swigCPtr, aValue, aFindFirst, aLo, aHi);
  }

  public int searchBinary(int aValue, boolean aFindFirst, int aLo) {
    return opensimModelJNI.ArrayInt_searchBinary__SWIG_1(swigCPtr, aValue, aFindFirst, aLo);
  }

  public int searchBinary(int aValue, boolean aFindFirst) {
    return opensimModelJNI.ArrayInt_searchBinary__SWIG_2(swigCPtr, aValue, aFindFirst);
  }

  public int searchBinary(int aValue) {
    return opensimModelJNI.ArrayInt_searchBinary__SWIG_3(swigCPtr, aValue);
  }

}
