/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class ArrayBool {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public ArrayBool(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ArrayBool obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      opensimModelJNI.delete_ArrayBool(swigCPtr);
    }
    swigCPtr = 0;
  }

  public ArrayBool(boolean aDefaultValue, int aSize, int aCapacity) {
    this(opensimModelJNI.new_ArrayBool__SWIG_0(aDefaultValue, aSize, aCapacity), true);
  }

  public ArrayBool(boolean aDefaultValue, int aSize) {
    this(opensimModelJNI.new_ArrayBool__SWIG_1(aDefaultValue, aSize), true);
  }

  public ArrayBool(boolean aDefaultValue) {
    this(opensimModelJNI.new_ArrayBool__SWIG_2(aDefaultValue), true);
  }

  public ArrayBool() {
    this(opensimModelJNI.new_ArrayBool__SWIG_3(), true);
  }

  public ArrayBool(ArrayBool aArray) {
    this(opensimModelJNI.new_ArrayBool__SWIG_4(ArrayBool.getCPtr(aArray)), true);
  }

  public boolean computeNewCapacity(int aMinCapacity, SWIGTYPE_p_int rNewCapacity) {
    return opensimModelJNI.ArrayBool_computeNewCapacity(swigCPtr, aMinCapacity, SWIGTYPE_p_int.getCPtr(rNewCapacity));
  }

  public boolean ensureCapacity(int aCapacity) {
    return opensimModelJNI.ArrayBool_ensureCapacity(swigCPtr, aCapacity);
  }

  public void trim() {
    opensimModelJNI.ArrayBool_trim(swigCPtr);
  }

  public int getCapacity() {
    return opensimModelJNI.ArrayBool_getCapacity(swigCPtr);
  }

  public void setCapacityIncrement(int aIncrement) {
    opensimModelJNI.ArrayBool_setCapacityIncrement(swigCPtr, aIncrement);
  }

  public int getCapacityIncrement() {
    return opensimModelJNI.ArrayBool_getCapacityIncrement(swigCPtr);
  }

  public boolean setSize(int aSize) {
    return opensimModelJNI.ArrayBool_setSize(swigCPtr, aSize);
  }

  public int getSize() {
    return opensimModelJNI.ArrayBool_getSize(swigCPtr);
  }

  public int append(boolean aValue) {
    return opensimModelJNI.ArrayBool_append__SWIG_0(swigCPtr, aValue);
  }

  public int append(ArrayBool aArray) {
    return opensimModelJNI.ArrayBool_append__SWIG_1(swigCPtr, ArrayBool.getCPtr(aArray));
  }

  public int append(int aSize, SWIGTYPE_p_bool aArray) {
    return opensimModelJNI.ArrayBool_append__SWIG_2(swigCPtr, aSize, SWIGTYPE_p_bool.getCPtr(aArray));
  }

  public int insert(int aIndex, boolean aValue) {
    return opensimModelJNI.ArrayBool_insert(swigCPtr, aIndex, aValue);
  }

  public int remove(int aIndex) {
    return opensimModelJNI.ArrayBool_remove(swigCPtr, aIndex);
  }

  public void set(int aIndex, boolean aValue) {
    opensimModelJNI.ArrayBool_set(swigCPtr, aIndex, aValue);
  }

  public SWIGTYPE_p_bool get() {
    long cPtr = opensimModelJNI.ArrayBool_get__SWIG_0(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_bool(cPtr, false);
  }

  public SWIGTYPE_p_bool get(int aIndex) {
    return new SWIGTYPE_p_bool(opensimModelJNI.ArrayBool_get__SWIG_1(swigCPtr, aIndex), false);
  }

  public boolean getitem(int index) {
    return opensimModelJNI.ArrayBool_getitem(swigCPtr, index);
  }

  public void setitem(int index, boolean val) {
    opensimModelJNI.ArrayBool_setitem(swigCPtr, index, val);
  }

  public SWIGTYPE_p_bool getLast() {
    return new SWIGTYPE_p_bool(opensimModelJNI.ArrayBool_getLast(swigCPtr), false);
  }

  public int findIndex(boolean aValue) {
    return opensimModelJNI.ArrayBool_findIndex(swigCPtr, aValue);
  }

  public int searchBinary(boolean aValue, boolean aFindFirst, int aLo, int aHi) {
    return opensimModelJNI.ArrayBool_searchBinary__SWIG_0(swigCPtr, aValue, aFindFirst, aLo, aHi);
  }

  public int searchBinary(boolean aValue, boolean aFindFirst, int aLo) {
    return opensimModelJNI.ArrayBool_searchBinary__SWIG_1(swigCPtr, aValue, aFindFirst, aLo);
  }

  public int searchBinary(boolean aValue, boolean aFindFirst) {
    return opensimModelJNI.ArrayBool_searchBinary__SWIG_2(swigCPtr, aValue, aFindFirst);
  }

  public int searchBinary(boolean aValue) {
    return opensimModelJNI.ArrayBool_searchBinary__SWIG_3(swigCPtr, aValue);
  }

}
