/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class Callback extends OpenSimObject {
  private long swigCPtr;

  public Callback(long cPtr, boolean cMemoryOwn) {
    super(opensimModelJNI.SWIGStorageUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(Callback obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      opensimModelJNI.delete_Callback(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public Callback(Model aModel) {
    this(opensimModelJNI.new_Callback__SWIG_0(Model.getCPtr(aModel), aModel), true);
  }

  public Callback() {
    this(opensimModelJNI.new_Callback__SWIG_1(), true);
  }

  public Callback(Callback aCallback) {
    this(opensimModelJNI.new_Callback__SWIG_2(Callback.getCPtr(aCallback), aCallback), true);
  }

  public Callback(String aFileName, boolean aUpdateFromXMLNode) {
    this(opensimModelJNI.new_Callback__SWIG_3(aFileName, aUpdateFromXMLNode), true);
  }

  public Callback(String aFileName) {
    this(opensimModelJNI.new_Callback__SWIG_4(aFileName), true);
  }

  public OpenSimObject copy() {
    long cPtr = opensimModelJNI.Callback_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new OpenSimObject(cPtr, false);
  }

  public void setModel(Model arg0) {
    opensimModelJNI.Callback_setModel(swigCPtr, this, Model.getCPtr(arg0), arg0);
  }

  public Model getModel() {
    long cPtr = opensimModelJNI.Callback_getModel(swigCPtr, this);
    return (cPtr == 0) ? null : new Model(cPtr, false);
  }

  public void setOn(boolean aTrueFalse) {
    opensimModelJNI.Callback_setOn(swigCPtr, this, aTrueFalse);
  }

  public boolean getOn() {
    return opensimModelJNI.Callback_getOn(swigCPtr, this);
  }

  public void setStartTime(double aStartTime) {
    opensimModelJNI.Callback_setStartTime(swigCPtr, this, aStartTime);
  }

  public double getStartTime() {
    return opensimModelJNI.Callback_getStartTime(swigCPtr, this);
  }

  public void setEndTime(double aEndTime) {
    opensimModelJNI.Callback_setEndTime(swigCPtr, this, aEndTime);
  }

  public double getEndTime() {
    return opensimModelJNI.Callback_getEndTime(swigCPtr, this);
  }

}
