/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class CallbackSet extends SetCallback {
  private long swigCPtr;

  public CallbackSet(long cPtr, boolean cMemoryOwn) {
    super(opensimModelJNI.SWIGStorageUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(CallbackSet obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      opensimModelJNI.delete_CallbackSet(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public CallbackSet(Model aModel) {
    this(opensimModelJNI.new_CallbackSet__SWIG_0(Model.getCPtr(aModel)), true);
  }

  public CallbackSet() {
    this(opensimModelJNI.new_CallbackSet__SWIG_1(), true);
  }

  public Model getModel() {
    long cPtr = opensimModelJNI.CallbackSet_getModel(swigCPtr);
    return (cPtr == 0) ? null : new Model(cPtr, false);
  }

  public void setOn(boolean aTrueFalse) {
    opensimModelJNI.CallbackSet_setOn(swigCPtr, aTrueFalse);
  }

}
