/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class CMCTool extends SimulationTool {
  private long swigCPtr;

  public CMCTool(long cPtr, boolean cMemoryOwn) {
    super(opensimModelJNI.SWIGStorageUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(CMCTool obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      opensimModelJNI.delete_CMCTool(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public CMCTool() {
    this(opensimModelJNI.new_CMCTool__SWIG_0(), true);
  }

  public CMCTool(String aFileName) {
    this(opensimModelJNI.new_CMCTool__SWIG_1(aFileName), true);
  }

  public CMCTool(CMCTool aObject) {
    this(opensimModelJNI.new_CMCTool__SWIG_2(CMCTool.getCPtr(aObject), aObject), true);
  }

  public OpenSimObject copy() {
    long cPtr = opensimModelJNI.CMCTool_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new OpenSimObject(cPtr, false);
  }

  public void run() {
    opensimModelJNI.CMCTool_run(swigCPtr, this);
  }

}
