/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class Force extends ModelComponent {
  private long swigCPtr;

  public Force(long cPtr, boolean cMemoryOwn) {
    super(opensimModelJNI.SWIGStorageUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(Force obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      opensimModelJNI.delete_Force(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public void setup(Model model) {
    opensimModelJNI.Force_setup(swigCPtr, this, Model.getCPtr(model), model);
  }

  public void postInit(Model model) {
    opensimModelJNI.Force_postInit(swigCPtr, this, Model.getCPtr(model), model);
  }

  public int getNumStateVariables() {
    return opensimModelJNI.Force_getNumStateVariables(swigCPtr, this);
  }

  public String getStateVariableName(int index) {
    return opensimModelJNI.Force_getStateVariableName(swigCPtr, this, index);
  }

  public double getStateVariable(SWIGTYPE_p_SimTK__State state, int index) {
    return opensimModelJNI.Force_getStateVariable(swigCPtr, this, SWIGTYPE_p_SimTK__State.getCPtr(state), index);
  }

  public void setStateVariable(SWIGTYPE_p_SimTK__State state, int index, double value) {
    opensimModelJNI.Force_setStateVariable(swigCPtr, this, SWIGTYPE_p_SimTK__State.getCPtr(state), index, value);
  }

  public Force(SWIGTYPE_p_DOMElement aNode) {
    this(opensimModelJNI.new_Force__SWIG_0(SWIGTYPE_p_DOMElement.getCPtr(aNode)), true);
  }

  public Force() {
    this(opensimModelJNI.new_Force__SWIG_1(), true);
  }

  public ArrayStr getRecordLabels() {
    return new ArrayStr(opensimModelJNI.Force_getRecordLabels(swigCPtr, this), true);
  }

  public ArrayDouble getRecordValues(SWIGTYPE_p_SimTK__State state) {
    return new ArrayDouble(opensimModelJNI.Force_getRecordValues(swigCPtr, this, SWIGTYPE_p_SimTK__State.getCPtr(state)), true);
  }

}
