/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class Manager {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public Manager(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Manager obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      opensimModelJNI.delete_Manager(swigCPtr);
    }
    swigCPtr = 0;
  }

  public Manager(SWIGTYPE_p_ModelIntegrand aIntegrand) {
    this(opensimModelJNI.new_Manager__SWIG_0(SWIGTYPE_p_ModelIntegrand.getCPtr(aIntegrand)), true);
  }

  public Manager() {
    this(opensimModelJNI.new_Manager__SWIG_1(), true);
  }

  public void setSessionName(String name) {
    opensimModelJNI.Manager_setSessionName(swigCPtr, this, name);
  }

  public String getSessionName() {
    return opensimModelJNI.Manager_getSessionName(swigCPtr, this);
  }

  public String toString() {
    return opensimModelJNI.Manager_toString(swigCPtr, this);
  }

  public void setIntegrand(SWIGTYPE_p_ModelIntegrand aIntegrand) {
    opensimModelJNI.Manager_setIntegrand(swigCPtr, this, SWIGTYPE_p_ModelIntegrand.getCPtr(aIntegrand));
  }

  public SWIGTYPE_p_ModelIntegrand getIntegrand() {
    long cPtr = opensimModelJNI.Manager_getIntegrand(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_ModelIntegrand(cPtr, false);
  }

  public SWIGTYPE_p_IntegRKF getIntegrator() {
    long cPtr = opensimModelJNI.Manager_getIntegrator(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_IntegRKF(cPtr, false);
  }

  public void setInitialTime(double aTI) {
    opensimModelJNI.Manager_setInitialTime(swigCPtr, this, aTI);
  }

  public double getInitialTime() {
    return opensimModelJNI.Manager_getInitialTime(swigCPtr, this);
  }

  public void setFinalTime(double aTF) {
    opensimModelJNI.Manager_setFinalTime(swigCPtr, this, aTF);
  }

  public double getFinalTime() {
    return opensimModelJNI.Manager_getFinalTime(swigCPtr, this);
  }

  public void setFirstDT(double aDT) {
    opensimModelJNI.Manager_setFirstDT(swigCPtr, this, aDT);
  }

  public double getFirstDT() {
    return opensimModelJNI.Manager_getFirstDT(swigCPtr, this);
  }

  public boolean initializeStates() {
    return opensimModelJNI.Manager_initializeStates__SWIG_0(swigCPtr, this);
  }

  public boolean initializeStates(SWIGTYPE_p_double aY, SWIGTYPE_p_double aYP) {
    return opensimModelJNI.Manager_initializeStates__SWIG_1(swigCPtr, this, SWIGTYPE_p_double.getCPtr(aY), SWIGTYPE_p_double.getCPtr(aYP));
  }

  public boolean initializeStates(SWIGTYPE_p_double aY) {
    return opensimModelJNI.Manager_initializeStates__SWIG_2(swigCPtr, this, SWIGTYPE_p_double.getCPtr(aY));
  }

  public boolean integrate() {
    return opensimModelJNI.Manager_integrate__SWIG_0(swigCPtr, this);
  }

  public boolean integrate(int startIndex) {
    return opensimModelJNI.Manager_integrate__SWIG_1(swigCPtr, this, startIndex);
  }

  public boolean integrate(double startTime) {
    return opensimModelJNI.Manager_integrate__SWIG_2(swigCPtr, this, startTime);
  }

}
