/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class Marker extends VisibleObject {
  private long swigCPtr;

  public Marker(long cPtr, boolean cMemoryOwn) {
    super(opensimModelJNI.SWIGStorageUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(Marker obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      opensimModelJNI.delete_Marker(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public Marker() {
    this(opensimModelJNI.new_Marker__SWIG_0(), true);
  }

  public Marker(Marker aMarker) {
    this(opensimModelJNI.new_Marker__SWIG_1(Marker.getCPtr(aMarker)), true);
  }

  public Marker(SWIGTYPE_p_DOMElement aElement) {
    this(opensimModelJNI.new_Marker__SWIG_2(SWIGTYPE_p_DOMElement.getCPtr(aElement)), true);
  }

  public OpenSimObject copy(SWIGTYPE_p_DOMElement aElement) {
    long cPtr = opensimModelJNI.Marker_copy__SWIG_0(swigCPtr, SWIGTYPE_p_DOMElement.getCPtr(aElement));
    return (cPtr == 0) ? null : new OpenSimObject(cPtr, false);
  }

  public OpenSimObject copy() {
    long cPtr = opensimModelJNI.Marker_copy__SWIG_1(swigCPtr);
    return (cPtr == 0) ? null : new OpenSimObject(cPtr, false);
  }

  public double getWeight() {
    return opensimModelJNI.Marker_getWeight(swigCPtr);
  }

  public void setWeight(double aWeight) {
    opensimModelJNI.Marker_setWeight(swigCPtr, aWeight);
  }

  public String getReferenceSegmentName() {
    return opensimModelJNI.Marker_getReferenceSegmentName(swigCPtr);
  }

  public int getRefSegment() {
    return opensimModelJNI.Marker_getRefSegment(swigCPtr);
  }

  public void setRefSegment(int aBodyIndex) {
    opensimModelJNI.Marker_setRefSegment(swigCPtr, aBodyIndex);
  }

  public void getLocation(ArrayDouble aLocation) {
    opensimModelJNI.Marker_getLocation(swigCPtr, ArrayDouble.getCPtr(aLocation));
  }

  public void setLocation(ArrayDouble aLocation) {
    opensimModelJNI.Marker_setLocation(swigCPtr, ArrayDouble.getCPtr(aLocation));
  }

  public void scaleBy(ArrayDouble aScales) {
    opensimModelJNI.Marker_scaleBy(swigCPtr, ArrayDouble.getCPtr(aScales));
  }

  public void update(OpenSimObject aObject, SWIGTYPE_p_Event aEvent) {
    opensimModelJNI.Marker_update(swigCPtr, OpenSimObject.getCPtr(aObject), SWIGTYPE_p_Event.getCPtr(aEvent));
  }

}
