/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class Material extends OpenSimObject {
  private long swigCPtr;

  public Material(long cPtr, boolean cMemoryOwn) {
    super(opensimModelJNI.SWIGStorageUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(Material obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      opensimModelJNI.delete_Material(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public void set_propTranslucency(SWIGTYPE_p_PropertyDbl value) {
    opensimModelJNI.Material__propTranslucency_set(swigCPtr, SWIGTYPE_p_PropertyDbl.getCPtr(value));
  }

  public SWIGTYPE_p_PropertyDbl get_propTranslucency() {
    return new SWIGTYPE_p_PropertyDbl(opensimModelJNI.Material__propTranslucency_get(swigCPtr), true);
  }

  public void set_propAmbientColor(SWIGTYPE_p_PropertyDblArray value) {
    opensimModelJNI.Material__propAmbientColor_set(swigCPtr, SWIGTYPE_p_PropertyDblArray.getCPtr(value));
  }

  public SWIGTYPE_p_PropertyDblArray get_propAmbientColor() {
    return new SWIGTYPE_p_PropertyDblArray(opensimModelJNI.Material__propAmbientColor_get(swigCPtr), true);
  }

  public void set_propDiffuseColor(SWIGTYPE_p_PropertyDblArray value) {
    opensimModelJNI.Material__propDiffuseColor_set(swigCPtr, SWIGTYPE_p_PropertyDblArray.getCPtr(value));
  }

  public SWIGTYPE_p_PropertyDblArray get_propDiffuseColor() {
    return new SWIGTYPE_p_PropertyDblArray(opensimModelJNI.Material__propDiffuseColor_get(swigCPtr), true);
  }

  public void set_propSpecularColor(SWIGTYPE_p_PropertyDblArray value) {
    opensimModelJNI.Material__propSpecularColor_set(swigCPtr, SWIGTYPE_p_PropertyDblArray.getCPtr(value));
  }

  public SWIGTYPE_p_PropertyDblArray get_propSpecularColor() {
    return new SWIGTYPE_p_PropertyDblArray(opensimModelJNI.Material__propSpecularColor_get(swigCPtr), true);
  }

  public void set_translucency(SWIGTYPE_p_double value) {
    opensimModelJNI.Material__translucency_set(swigCPtr, SWIGTYPE_p_double.getCPtr(value));
  }

  public SWIGTYPE_p_double get_translucency() {
    return new SWIGTYPE_p_double(opensimModelJNI.Material__translucency_get(swigCPtr), false);
  }

  public void set_ambientColor(ArrayDouble value) {
    opensimModelJNI.Material__ambientColor_set(swigCPtr, ArrayDouble.getCPtr(value));
  }

  public ArrayDouble get_ambientColor() {
    return new ArrayDouble(opensimModelJNI.Material__ambientColor_get(swigCPtr), false);
  }

  public void set_diffuseColor(ArrayDouble value) {
    opensimModelJNI.Material__diffuseColor_set(swigCPtr, ArrayDouble.getCPtr(value));
  }

  public ArrayDouble get_diffuseColor() {
    return new ArrayDouble(opensimModelJNI.Material__diffuseColor_get(swigCPtr), false);
  }

  public void set_specularColor(ArrayDouble value) {
    opensimModelJNI.Material__specularColor_set(swigCPtr, ArrayDouble.getCPtr(value));
  }

  public ArrayDouble get_specularColor() {
    return new ArrayDouble(opensimModelJNI.Material__specularColor_get(swigCPtr), false);
  }

  public static void set_defaultMaterial(Material value) {
    opensimModelJNI.Material__defaultMaterial_set(Material.getCPtr(value));
  }

  public static Material get_defaultMaterial() {
    long cPtr = opensimModelJNI.Material__defaultMaterial_get();
    return (cPtr == 0) ? null : new Material(cPtr, false);
  }

  public Material() {
    this(opensimModelJNI.new_Material__SWIG_0(), true);
  }

  public Material(String aFileName) {
    this(opensimModelJNI.new_Material__SWIG_1(aFileName), true);
  }

  public Material(Material aMaterial) {
    this(opensimModelJNI.new_Material__SWIG_2(Material.getCPtr(aMaterial)), true);
  }

  public OpenSimObject copy() {
    long cPtr = opensimModelJNI.Material_copy(swigCPtr);
    return (cPtr == 0) ? null : new OpenSimObject(cPtr, false);
  }

  public void setTranslucency(double aTranslucency) {
    opensimModelJNI.Material_setTranslucency(swigCPtr, aTranslucency);
  }

  public double getTranslucency() {
    return opensimModelJNI.Material_getTranslucency(swigCPtr);
  }

  public void setAmbientColor(double[] aAmbientColor) {
    opensimModelJNI.Material_setAmbientColor(swigCPtr, aAmbientColor);
  }

  public SWIGTYPE_p_double getAmbientColor() {
    long cPtr = opensimModelJNI.Material_getAmbientColor(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public void setDiffuseColor(double[] aDiffuseColor) {
    opensimModelJNI.Material_setDiffuseColor(swigCPtr, aDiffuseColor);
  }

  public SWIGTYPE_p_double getDiffuseColor() {
    long cPtr = opensimModelJNI.Material_getDiffuseColor(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public void setSpecularColor(double[] aSpecularColor) {
    opensimModelJNI.Material_setSpecularColor(swigCPtr, aSpecularColor);
  }

  public SWIGTYPE_p_double getSpecularColor() {
    long cPtr = opensimModelJNI.Material_getSpecularColor(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public static String GetDefaultMaterialName() {
    return opensimModelJNI.Material_GetDefaultMaterialName();
  }

  public static Material GetDefaultMaterial() {
    return new Material(opensimModelJNI.Material_GetDefaultMaterial(), false);
  }

}
