/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class Model extends OpenSimObject {
  private long swigCPtr;

  public Model(long cPtr, boolean cMemoryOwn) {
    super(opensimModelJNI.SWIGStorageUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(Model obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      opensimModelJNI.delete_Model(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public String getModelDescriptionFileName() {
    return opensimModelJNI.Model_getModelDescriptionFileName(swigCPtr);
  }

  public void setModelDescriptionFileName(String aModelDescriptionFileName) {
    opensimModelJNI.Model_setModelDescriptionFileName(swigCPtr, aModelDescriptionFileName);
  }

  public int getNB() {
    return opensimModelJNI.Model_getNB(swigCPtr);
  }

  public int getNJ() {
    return opensimModelJNI.Model_getNJ(swigCPtr);
  }

  public int getNQ() {
    return opensimModelJNI.Model_getNQ(swigCPtr);
  }

  public int getNU() {
    return opensimModelJNI.Model_getNU(swigCPtr);
  }

  public int getNX() {
    return opensimModelJNI.Model_getNX(swigCPtr);
  }

  public int getNA() {
    return opensimModelJNI.Model_getNA(swigCPtr);
  }

  public int getNP() {
    return opensimModelJNI.Model_getNP(swigCPtr);
  }

  public int getNY() {
    return opensimModelJNI.Model_getNY(swigCPtr);
  }

  public int getNYP() {
    return opensimModelJNI.Model_getNYP(swigCPtr);
  }

  public void setName(String aName) {
    opensimModelJNI.Model_setName(swigCPtr, aName);
  }

  public String getBodyName(int aIndex) {
    return opensimModelJNI.Model_getBodyName(swigCPtr, aIndex);
  }

  public String getCoordinateName(int aIndex) {
    return opensimModelJNI.Model_getCoordinateName(swigCPtr, aIndex);
  }

  public String getSpeedName(int aIndex) {
    return opensimModelJNI.Model_getSpeedName(swigCPtr, aIndex);
  }

  public String getActuatorName(int aIndex) {
    return opensimModelJNI.Model_getActuatorName(swigCPtr, aIndex);
  }

  public String getControlName(int aIndex) {
    return opensimModelJNI.Model_getControlName(swigCPtr, aIndex);
  }

  public String getStateName(int aIndex) {
    return opensimModelJNI.Model_getStateName(swigCPtr, aIndex);
  }

  public String getPseudoStateName(int aIndex) {
    return opensimModelJNI.Model_getPseudoStateName(swigCPtr, aIndex);
  }

  public int getBodyIndex(String aName) {
    return opensimModelJNI.Model_getBodyIndex(swigCPtr, aName);
  }

  public int getCoordinateIndex(String aName) {
    return opensimModelJNI.Model_getCoordinateIndex(swigCPtr, aName);
  }

  public int getSpeedIndex(String aName) {
    return opensimModelJNI.Model_getSpeedIndex(swigCPtr, aName);
  }

  public int getActuatorIndex(String aName) {
    return opensimModelJNI.Model_getActuatorIndex(swigCPtr, aName);
  }

  public int getControlIndex(String aName) {
    return opensimModelJNI.Model_getControlIndex(swigCPtr, aName);
  }

  public int getStateIndex(String aName) {
    return opensimModelJNI.Model_getStateIndex(swigCPtr, aName);
  }

  public int getPseudoStateIndex(String aName) {
    return opensimModelJNI.Model_getPseudoStateIndex(swigCPtr, aName);
  }

  public Body getBody(int aIndex) {
    long cPtr = opensimModelJNI.Model_getBody(swigCPtr, aIndex);
    return (cPtr == 0) ? null : new Body(cPtr, false);
  }

  public void constructBodies() {
    opensimModelJNI.Model_constructBodies(swigCPtr);
  }

  public SetBodies getBodySet() {
    long cPtr = opensimModelJNI.Model_getBodySet(swigCPtr);
    return (cPtr == 0) ? null : new SetBodies(cPtr, false);
  }

  public MaterialSet getMaterialSet() {
    long cPtr = opensimModelJNI.Model_getMaterialSet(swigCPtr);
    return (cPtr == 0) ? null : new MaterialSet(cPtr, false);
  }

  public VisibleObject getVisibleObjectByName(String aName) {
    long cPtr = opensimModelJNI.Model_getVisibleObjectByName(swigCPtr, aName);
    return (cPtr == 0) ? null : new VisibleObject(cPtr, false);
  }

  public void set(double aT, double[] aX, double[] aY) {
    opensimModelJNI.Model_set(swigCPtr, aT, aX, aY);
  }

  public void setTime(double aT) {
    opensimModelJNI.Model_setTime(swigCPtr, aT);
  }

  public double getTime() {
    return opensimModelJNI.Model_getTime(swigCPtr);
  }

  public void setTimeNormConstant(double aNormConst) {
    opensimModelJNI.Model_setTimeNormConstant(swigCPtr, aNormConst);
  }

  public double getTimeNormConstant() {
    return opensimModelJNI.Model_getTimeNormConstant(swigCPtr);
  }

  public void setControls(double[] aX) {
    opensimModelJNI.Model_setControls(swigCPtr, aX);
  }

  public void setControl(int aIndex, double aValue) {
    opensimModelJNI.Model_setControl__SWIG_0(swigCPtr, aIndex, aValue);
  }

  public void setControl(String aName, double aValue) {
    opensimModelJNI.Model_setControl__SWIG_1(swigCPtr, aName, aValue);
  }

  public void getControls(double[] rX) {
    opensimModelJNI.Model_getControls(swigCPtr, rX);
  }

  public double getControl(int aIndex) {
    return opensimModelJNI.Model_getControl__SWIG_0(swigCPtr, aIndex);
  }

  public double getControl(String aName) {
    return opensimModelJNI.Model_getControl__SWIG_1(swigCPtr, aName);
  }

  public void setInitialStates(double[] aYI) {
    opensimModelJNI.Model_setInitialStates(swigCPtr, aYI);
  }

  public void getInitialStates(double[] rYI) {
    opensimModelJNI.Model_getInitialStates(swigCPtr, rYI);
  }

  public double getInitialState(int aIndex) {
    return opensimModelJNI.Model_getInitialState__SWIG_0(swigCPtr, aIndex);
  }

  public double getInitialState(String aName) {
    return opensimModelJNI.Model_getInitialState__SWIG_1(swigCPtr, aName);
  }

  public void setStates(double[] aY) {
    opensimModelJNI.Model_setStates(swigCPtr, aY);
  }

  public void getStates(double[] rY) {
    opensimModelJNI.Model_getStates(swigCPtr, rY);
  }

  public double getState(int aIndex) {
    return opensimModelJNI.Model_getState__SWIG_0(swigCPtr, aIndex);
  }

  public double getState(String aName) {
    return opensimModelJNI.Model_getState__SWIG_1(swigCPtr, aName);
  }

  public void setInitialPseudoStates(double[] aYPI) {
    opensimModelJNI.Model_setInitialPseudoStates(swigCPtr, aYPI);
  }

  public void getInitialPseudoStates(double[] rYPI) {
    opensimModelJNI.Model_getInitialPseudoStates(swigCPtr, rYPI);
  }

  public double getInitialPseudoState(int aIndex) {
    return opensimModelJNI.Model_getInitialPseudoState__SWIG_0(swigCPtr, aIndex);
  }

  public double getInitialPseudoState(String aName) {
    return opensimModelJNI.Model_getInitialPseudoState__SWIG_1(swigCPtr, aName);
  }

  public void setPseudoStates(double[] aYP) {
    opensimModelJNI.Model_setPseudoStates(swigCPtr, aYP);
  }

  public void getPseudoStates(double[] rYP) {
    opensimModelJNI.Model_getPseudoStates(swigCPtr, rYP);
  }

  public double getPseudoState(int aIndex) {
    return opensimModelJNI.Model_getPseudoState(swigCPtr, aIndex);
  }

  public void setConfiguration(double[] aY) {
    opensimModelJNI.Model_setConfiguration__SWIG_0(swigCPtr, aY);
  }

  public void setConfiguration(double[] aQ, double[] aU) {
    opensimModelJNI.Model_setConfiguration__SWIG_1(swigCPtr, aQ, aU);
  }

  public void getCoordinates(double[] rQ) {
    opensimModelJNI.Model_getCoordinates(swigCPtr, rQ);
  }

  public double getCoordinate(int aIndex) {
    return opensimModelJNI.Model_getCoordinate__SWIG_0(swigCPtr, aIndex);
  }

  public double getCoordinate(String aName) {
    return opensimModelJNI.Model_getCoordinate__SWIG_1(swigCPtr, aName);
  }

  public void getSpeeds(double[] rU) {
    opensimModelJNI.Model_getSpeeds(swigCPtr, rU);
  }

  public double getSpeed(int aIndex) {
    return opensimModelJNI.Model_getSpeed__SWIG_0(swigCPtr, aIndex);
  }

  public double getSpeed(String aName) {
    return opensimModelJNI.Model_getSpeed__SWIG_1(swigCPtr, aName);
  }

  public void getAccelerations(double[] rDUDT) {
    opensimModelJNI.Model_getAccelerations(swigCPtr, rDUDT);
  }

  public double getAcceleration(int aIndex) {
    return opensimModelJNI.Model_getAcceleration__SWIG_0(swigCPtr, aIndex);
  }

  public double getAcceleration(String aSpeedName) {
    return opensimModelJNI.Model_getAcceleration__SWIG_1(swigCPtr, aSpeedName);
  }

  public void extractConfiguration(double[] aY, double[] rQ, double[] rU) {
    opensimModelJNI.Model_extractConfiguration(swigCPtr, aY, rQ, rU);
  }

  public int assemble(double aTime, SWIGTYPE_p_double rState, SWIGTYPE_p_int aLock, double aTol, int aMaxevals, SWIGTYPE_p_int rFcnt, SWIGTYPE_p_int rErr) {
    return opensimModelJNI.Model_assemble(swigCPtr, aTime, SWIGTYPE_p_double.getCPtr(rState), SWIGTYPE_p_int.getCPtr(aLock), aTol, aMaxevals, SWIGTYPE_p_int.getCPtr(rFcnt), SWIGTYPE_p_int.getCPtr(rErr));
  }

  public boolean scale(ScaleSet aScaleSet) {
    return opensimModelJNI.Model_scale(swigCPtr, ScaleSet.getCPtr(aScaleSet));
  }

  public void getGravity(double[] rGrav) {
    opensimModelJNI.Model_getGravity(swigCPtr, rGrav);
  }

  public void setGravity(double[] aGrav) {
    opensimModelJNI.Model_setGravity(swigCPtr, aGrav);
  }

  public int getGroundID() {
    return opensimModelJNI.Model_getGroundID(swigCPtr);
  }

  public void setBodyToJointBodyLocal(int abody, double[] aBTJ) {
    opensimModelJNI.Model_setBodyToJointBodyLocal(swigCPtr, abody, aBTJ);
  }

  public void getBodyToJointBodyLocal(int aBody, double[] rBTJ) {
    opensimModelJNI.Model_getBodyToJointBodyLocal(swigCPtr, aBody, rBTJ);
  }

  public void setInboardToJointBodyLocal(int aBody, double[] aBTJ) {
    opensimModelJNI.Model_setInboardToJointBodyLocal(swigCPtr, aBody, aBTJ);
  }

  public void getInboardToJointBodyLocal(int aBody, double[] rBTJ) {
    opensimModelJNI.Model_getInboardToJointBodyLocal(swigCPtr, aBody, rBTJ);
  }

  public void setPin(int aBody, int aPinNumber, double[] aPin) {
    opensimModelJNI.Model_setPin(swigCPtr, aBody, aPinNumber, aPin);
  }

  public void getPin(int aBody, int aPinNumber, double[] rPin) {
    opensimModelJNI.Model_getPin(swigCPtr, aBody, aPinNumber, rPin);
  }

  public void getJointInfo(int aJoint, int[] rInfo, int[] rSlider) {
    opensimModelJNI.Model_getJointInfo(swigCPtr, aJoint, rInfo, rSlider);
  }

  public double getMass(int aBody) {
    return opensimModelJNI.Model_getMass(swigCPtr, aBody);
  }

  public int getInertiaBodyLocal(int aBody, SWIGTYPE_p_a_3__double rI) {
    return opensimModelJNI.Model_getInertiaBodyLocal__SWIG_0(swigCPtr, aBody, SWIGTYPE_p_a_3__double.getCPtr(rI));
  }

  public int getInertiaBodyLocal(int aBody, SWIGTYPE_p_double rI) {
    return opensimModelJNI.Model_getInertiaBodyLocal__SWIG_1(swigCPtr, aBody, SWIGTYPE_p_double.getCPtr(rI));
  }

  public void getSystemInertia(SWIGTYPE_p_double rM, double[] rCOM, SWIGTYPE_p_a_3__double rI) {
    opensimModelJNI.Model_getSystemInertia__SWIG_0(swigCPtr, SWIGTYPE_p_double.getCPtr(rM), rCOM, SWIGTYPE_p_a_3__double.getCPtr(rI));
  }

  public void getSystemInertia(SWIGTYPE_p_double rM, SWIGTYPE_p_double rCOM, SWIGTYPE_p_double rI) {
    opensimModelJNI.Model_getSystemInertia__SWIG_1(swigCPtr, SWIGTYPE_p_double.getCPtr(rM), SWIGTYPE_p_double.getCPtr(rCOM), SWIGTYPE_p_double.getCPtr(rI));
  }

  public void getPosition(int aBody, double[] aPoint, double[] rPos) {
    opensimModelJNI.Model_getPosition(swigCPtr, aBody, aPoint, rPos);
  }

  public void getVelocity(int aBody, double[] aPoint, double[] rVel) {
    opensimModelJNI.Model_getVelocity(swigCPtr, aBody, aPoint, rVel);
  }

  public void getAcceleration(int aBody, double[] aPoint, double[] rAcc) {
    opensimModelJNI.Model_getAcceleration__SWIG_2(swigCPtr, aBody, aPoint, rAcc);
  }

  public void getDirectionCosines(int aBody, SWIGTYPE_p_a_3__double rDirCos) {
    opensimModelJNI.Model_getDirectionCosines__SWIG_0(swigCPtr, aBody, SWIGTYPE_p_a_3__double.getCPtr(rDirCos));
  }

  public void getDirectionCosines(int aBody, SWIGTYPE_p_double rDirCos) {
    opensimModelJNI.Model_getDirectionCosines__SWIG_1(swigCPtr, aBody, SWIGTYPE_p_double.getCPtr(rDirCos));
  }

  public void getAngularVelocity(int aBody, double[] rAngVel) {
    opensimModelJNI.Model_getAngularVelocity(swigCPtr, aBody, rAngVel);
  }

  public void getAngularVelocityBodyLocal(int aBody, double[] rAngVel) {
    opensimModelJNI.Model_getAngularVelocityBodyLocal(swigCPtr, aBody, rAngVel);
  }

  public void getAngularAcceleration(int aBody, double[] rAngAcc) {
    opensimModelJNI.Model_getAngularAcceleration(swigCPtr, aBody, rAngAcc);
  }

  public void getAngularAccelerationBodyLocal(int aBody, double[] rAngAcc) {
    opensimModelJNI.Model_getAngularAccelerationBodyLocal(swigCPtr, aBody, rAngAcc);
  }

  public void applyForce(int aBody, double[] aPoint, double[] aForce) {
    opensimModelJNI.Model_applyForce(swigCPtr, aBody, aPoint, aForce);
  }

  public void applyForces(int aN, int[] aBodies, SWIGTYPE_p_a_3__double aPoints, SWIGTYPE_p_a_3__double aForces) {
    opensimModelJNI.Model_applyForces__SWIG_0(swigCPtr, aN, aBodies, SWIGTYPE_p_a_3__double.getCPtr(aPoints), SWIGTYPE_p_a_3__double.getCPtr(aForces));
  }

  public void applyForces(int aN, int[] aBodies, SWIGTYPE_p_double aPoints, SWIGTYPE_p_double aForces) {
    opensimModelJNI.Model_applyForces__SWIG_1(swigCPtr, aN, aBodies, SWIGTYPE_p_double.getCPtr(aPoints), SWIGTYPE_p_double.getCPtr(aForces));
  }

  public void applyForceBodyLocal(int aBody, double[] aPoint, double[] aForce) {
    opensimModelJNI.Model_applyForceBodyLocal(swigCPtr, aBody, aPoint, aForce);
  }

  public void applyForcesBodyLocal(int aN, int[] aBodies, SWIGTYPE_p_a_3__double aPoints, SWIGTYPE_p_a_3__double aForces) {
    opensimModelJNI.Model_applyForcesBodyLocal__SWIG_0(swigCPtr, aN, aBodies, SWIGTYPE_p_a_3__double.getCPtr(aPoints), SWIGTYPE_p_a_3__double.getCPtr(aForces));
  }

  public void applyForcesBodyLocal(int aN, int[] aBodies, SWIGTYPE_p_double aPoints, SWIGTYPE_p_double aForces) {
    opensimModelJNI.Model_applyForcesBodyLocal__SWIG_1(swigCPtr, aN, aBodies, SWIGTYPE_p_double.getCPtr(aPoints), SWIGTYPE_p_double.getCPtr(aForces));
  }

  public void applyTorque(int aBody, double[] aTorque) {
    opensimModelJNI.Model_applyTorque(swigCPtr, aBody, aTorque);
  }

  public void applyTorques(int aN, int[] aBodies, SWIGTYPE_p_a_3__double aTorques) {
    opensimModelJNI.Model_applyTorques__SWIG_0(swigCPtr, aN, aBodies, SWIGTYPE_p_a_3__double.getCPtr(aTorques));
  }

  public void applyTorques(int aN, int[] aBodies, SWIGTYPE_p_double aTorques) {
    opensimModelJNI.Model_applyTorques__SWIG_1(swigCPtr, aN, aBodies, SWIGTYPE_p_double.getCPtr(aTorques));
  }

  public void applyTorqueBodyLocal(int aBody, double[] aTorque) {
    opensimModelJNI.Model_applyTorqueBodyLocal(swigCPtr, aBody, aTorque);
  }

  public void applyTorquesBodyLocal(int aN, int[] aBodies, SWIGTYPE_p_a_3__double aTorques) {
    opensimModelJNI.Model_applyTorquesBodyLocal__SWIG_0(swigCPtr, aN, aBodies, SWIGTYPE_p_a_3__double.getCPtr(aTorques));
  }

  public void applyTorquesBodyLocal(int aN, int[] aBodies, SWIGTYPE_p_double aTorques) {
    opensimModelJNI.Model_applyTorquesBodyLocal__SWIG_1(swigCPtr, aN, aBodies, SWIGTYPE_p_double.getCPtr(aTorques));
  }

  public void applyGeneralizedForce(int aU, double aF) {
    opensimModelJNI.Model_applyGeneralizedForce(swigCPtr, aU, aF);
  }

  public void applyGeneralizedForces(double[] aF) {
    opensimModelJNI.Model_applyGeneralizedForces__SWIG_0(swigCPtr, aF);
  }

  public void applyGeneralizedForces(int aN, int[] aU, double[] aF) {
    opensimModelJNI.Model_applyGeneralizedForces__SWIG_1(swigCPtr, aN, aU, aF);
  }

  public double getNetAppliedGeneralizedForce(int aU) {
    return opensimModelJNI.Model_getNetAppliedGeneralizedForce(swigCPtr, aU);
  }

  public void computeGeneralizedForces(double[] aDUDT, double[] rF) {
    opensimModelJNI.Model_computeGeneralizedForces(swigCPtr, aDUDT, rF);
  }

  public void computeReactions(SWIGTYPE_p_a_3__double rForces, SWIGTYPE_p_a_3__double rTorques) {
    opensimModelJNI.Model_computeReactions(swigCPtr, SWIGTYPE_p_a_3__double.getCPtr(rForces), SWIGTYPE_p_a_3__double.getCPtr(rTorques));
  }

  public void prescribeMotion(int aJoint, int aAxis, int aPrescribed) {
    opensimModelJNI.Model_prescribeMotion(swigCPtr, aJoint, aAxis, aPrescribed);
  }

  public void formMassMatrix(SWIGTYPE_p_double rI) {
    opensimModelJNI.Model_formMassMatrix(swigCPtr, SWIGTYPE_p_double.getCPtr(rI));
  }

  public void formEulerTransform(int aBody, SWIGTYPE_p_double rE) {
    opensimModelJNI.Model_formEulerTransform(swigCPtr, aBody, SWIGTYPE_p_double.getCPtr(rE));
  }

  public void formJacobianTranslation(int aBody, double[] aPoint, SWIGTYPE_p_double rJ, int aRefBody) {
    opensimModelJNI.Model_formJacobianTranslation__SWIG_0(swigCPtr, aBody, aPoint, SWIGTYPE_p_double.getCPtr(rJ), aRefBody);
  }

  public void formJacobianTranslation(int aBody, double[] aPoint, SWIGTYPE_p_double rJ) {
    opensimModelJNI.Model_formJacobianTranslation__SWIG_1(swigCPtr, aBody, aPoint, SWIGTYPE_p_double.getCPtr(rJ));
  }

  public void formJacobianOrientation(int aBody, SWIGTYPE_p_double rJ0, int aRefBody) {
    opensimModelJNI.Model_formJacobianOrientation__SWIG_0(swigCPtr, aBody, SWIGTYPE_p_double.getCPtr(rJ0), aRefBody);
  }

  public void formJacobianOrientation(int aBody, SWIGTYPE_p_double rJ0) {
    opensimModelJNI.Model_formJacobianOrientation__SWIG_1(swigCPtr, aBody, SWIGTYPE_p_double.getCPtr(rJ0));
  }

  public void formJacobianEuler(int aBody, SWIGTYPE_p_double rJE, int aRefBody) {
    opensimModelJNI.Model_formJacobianEuler__SWIG_0(swigCPtr, aBody, SWIGTYPE_p_double.getCPtr(rJE), aRefBody);
  }

  public void formJacobianEuler(int aBody, SWIGTYPE_p_double rJE) {
    opensimModelJNI.Model_formJacobianEuler__SWIG_1(swigCPtr, aBody, SWIGTYPE_p_double.getCPtr(rJE));
  }

  public static int ComputeEffectiveMassMatrix(int aNJX, int aNU, SWIGTYPE_p_double aJ, SWIGTYPE_p_double aIinv, SWIGTYPE_p_double rIeff) {
    return opensimModelJNI.Model_ComputeEffectiveMassMatrix(aNJX, aNU, SWIGTYPE_p_double.getCPtr(aJ), SWIGTYPE_p_double.getCPtr(aIinv), SWIGTYPE_p_double.getCPtr(rIeff));
  }

  public static int ComputeJacobianInverse(int aNJX, int aNU, SWIGTYPE_p_double aJ, SWIGTYPE_p_double aI, SWIGTYPE_p_double rJInv) {
    return opensimModelJNI.Model_ComputeJacobianInverse(aNJX, aNU, SWIGTYPE_p_double.getCPtr(aJ), SWIGTYPE_p_double.getCPtr(aI), SWIGTYPE_p_double.getCPtr(rJInv));
  }

  public int computeAccelerations(SWIGTYPE_p_double dqdt, SWIGTYPE_p_double dudt) {
    return opensimModelJNI.Model_computeAccelerations(swigCPtr, SWIGTYPE_p_double.getCPtr(dqdt), SWIGTYPE_p_double.getCPtr(dudt));
  }

  public void computeAuxiliaryDerivatives(SWIGTYPE_p_double dydt) {
    opensimModelJNI.Model_computeAuxiliaryDerivatives(swigCPtr, SWIGTYPE_p_double.getCPtr(dydt));
  }

  public void promoteControlsToStates(double[] aX, double aDT) {
    opensimModelJNI.Model_promoteControlsToStates(swigCPtr, aX, aDT);
  }

  public int computePerformance(double t, SWIGTYPE_p_double x, SWIGTYPE_p_double y, SWIGTYPE_p_double p, SWIGTYPE_p_void cd) {
    return opensimModelJNI.Model_computePerformance__SWIG_0(swigCPtr, t, SWIGTYPE_p_double.getCPtr(x), SWIGTYPE_p_double.getCPtr(y), SWIGTYPE_p_double.getCPtr(p), SWIGTYPE_p_void.getCPtr(cd));
  }

  public int computePerformance(double t, SWIGTYPE_p_double x, SWIGTYPE_p_double y, SWIGTYPE_p_double p) {
    return opensimModelJNI.Model_computePerformance__SWIG_1(swigCPtr, t, SWIGTYPE_p_double.getCPtr(x), SWIGTYPE_p_double.getCPtr(y), SWIGTYPE_p_double.getCPtr(p));
  }

  public int computeConstraint(double t, SWIGTYPE_p_double x, SWIGTYPE_p_double y, int ic, SWIGTYPE_p_double c, SWIGTYPE_p_void cd) {
    return opensimModelJNI.Model_computeConstraint__SWIG_0(swigCPtr, t, SWIGTYPE_p_double.getCPtr(x), SWIGTYPE_p_double.getCPtr(y), ic, SWIGTYPE_p_double.getCPtr(c), SWIGTYPE_p_void.getCPtr(cd));
  }

  public int computeConstraint(double t, SWIGTYPE_p_double x, SWIGTYPE_p_double y, int ic, SWIGTYPE_p_double c) {
    return opensimModelJNI.Model_computeConstraint__SWIG_1(swigCPtr, t, SWIGTYPE_p_double.getCPtr(x), SWIGTYPE_p_double.getCPtr(y), ic, SWIGTYPE_p_double.getCPtr(c));
  }

  public void transform(int aBody1, double[] aVec1, int aBody2, double[] rVec2) {
    opensimModelJNI.Model_transform(swigCPtr, aBody1, aVec1, aBody2, rVec2);
  }

  public void transformPosition(int aBody, double[] aPos, double[] rPos) {
    opensimModelJNI.Model_transformPosition(swigCPtr, aBody, aPos, rPos);
  }

  public void convertQuaternionsToAngles(SWIGTYPE_p_double aQ, SWIGTYPE_p_double rQAng) {
    opensimModelJNI.Model_convertQuaternionsToAngles__SWIG_0(swigCPtr, SWIGTYPE_p_double.getCPtr(aQ), SWIGTYPE_p_double.getCPtr(rQAng));
  }

  public void convertQuaternionsToAngles(Storage rQStore) {
    opensimModelJNI.Model_convertQuaternionsToAngles__SWIG_1(swigCPtr, Storage.getCPtr(rQStore));
  }

  public void convertAnglesToQuaternions(SWIGTYPE_p_double aQAng, SWIGTYPE_p_double rQ) {
    opensimModelJNI.Model_convertAnglesToQuaternions__SWIG_0(swigCPtr, SWIGTYPE_p_double.getCPtr(aQAng), SWIGTYPE_p_double.getCPtr(rQ));
  }

  public void convertAnglesToQuaternions(Storage rQStore) {
    opensimModelJNI.Model_convertAnglesToQuaternions__SWIG_1(swigCPtr, Storage.getCPtr(rQStore));
  }

  public void convertRadiansToDegrees(SWIGTYPE_p_double aQRad, SWIGTYPE_p_double rQDeg) {
    opensimModelJNI.Model_convertRadiansToDegrees__SWIG_0(swigCPtr, SWIGTYPE_p_double.getCPtr(aQRad), SWIGTYPE_p_double.getCPtr(rQDeg));
  }

  public void convertRadiansToDegrees(Storage rQStore) {
    opensimModelJNI.Model_convertRadiansToDegrees__SWIG_1(swigCPtr, Storage.getCPtr(rQStore));
  }

  public void convertDegreesToRadians(SWIGTYPE_p_double aQDeg, SWIGTYPE_p_double rQRad) {
    opensimModelJNI.Model_convertDegreesToRadians__SWIG_0(swigCPtr, SWIGTYPE_p_double.getCPtr(aQDeg), SWIGTYPE_p_double.getCPtr(rQRad));
  }

  public void convertDegreesToRadians(Storage rQStore) {
    opensimModelJNI.Model_convertDegreesToRadians__SWIG_1(swigCPtr, Storage.getCPtr(rQStore));
  }

  public void convertAnglesToDirectionCosines(double aE1, double aE2, double aE3, SWIGTYPE_p_a_3__double rDirCos) {
    opensimModelJNI.Model_convertAnglesToDirectionCosines__SWIG_0(swigCPtr, aE1, aE2, aE3, SWIGTYPE_p_a_3__double.getCPtr(rDirCos));
  }

  public void convertAnglesToDirectionCosines(double aE1, double aE2, double aE3, SWIGTYPE_p_double rDirCos) {
    opensimModelJNI.Model_convertAnglesToDirectionCosines__SWIG_1(swigCPtr, aE1, aE2, aE3, SWIGTYPE_p_double.getCPtr(rDirCos));
  }

  public void convertDirectionCosinesToAngles(SWIGTYPE_p_a_3__double aDirCos, SWIGTYPE_p_double rE1, SWIGTYPE_p_double rE2, SWIGTYPE_p_double rE3) {
    opensimModelJNI.Model_convertDirectionCosinesToAngles__SWIG_0(swigCPtr, SWIGTYPE_p_a_3__double.getCPtr(aDirCos), SWIGTYPE_p_double.getCPtr(rE1), SWIGTYPE_p_double.getCPtr(rE2), SWIGTYPE_p_double.getCPtr(rE3));
  }

  public void convertDirectionCosinesToAngles(SWIGTYPE_p_double aDirCos, SWIGTYPE_p_double rE1, SWIGTYPE_p_double rE2, SWIGTYPE_p_double rE3) {
    opensimModelJNI.Model_convertDirectionCosinesToAngles__SWIG_1(swigCPtr, SWIGTYPE_p_double.getCPtr(aDirCos), SWIGTYPE_p_double.getCPtr(rE1), SWIGTYPE_p_double.getCPtr(rE2), SWIGTYPE_p_double.getCPtr(rE3));
  }

  public void convertDirectionCosinesToQuaternions(SWIGTYPE_p_a_3__double aDirCos, SWIGTYPE_p_double rQ1, SWIGTYPE_p_double rQ2, SWIGTYPE_p_double rQ3, SWIGTYPE_p_double rQ4) {
    opensimModelJNI.Model_convertDirectionCosinesToQuaternions__SWIG_0(swigCPtr, SWIGTYPE_p_a_3__double.getCPtr(aDirCos), SWIGTYPE_p_double.getCPtr(rQ1), SWIGTYPE_p_double.getCPtr(rQ2), SWIGTYPE_p_double.getCPtr(rQ3), SWIGTYPE_p_double.getCPtr(rQ4));
  }

  public void convertDirectionCosinesToQuaternions(SWIGTYPE_p_double aDirCos, SWIGTYPE_p_double rQ1, SWIGTYPE_p_double rQ2, SWIGTYPE_p_double rQ3, SWIGTYPE_p_double rQ4) {
    opensimModelJNI.Model_convertDirectionCosinesToQuaternions__SWIG_1(swigCPtr, SWIGTYPE_p_double.getCPtr(aDirCos), SWIGTYPE_p_double.getCPtr(rQ1), SWIGTYPE_p_double.getCPtr(rQ2), SWIGTYPE_p_double.getCPtr(rQ3), SWIGTYPE_p_double.getCPtr(rQ4));
  }

  public void convertQuaternionsToDirectionCosines(double aQ1, double aQ2, double aQ3, double aQ4, SWIGTYPE_p_a_3__double rDirCos) {
    opensimModelJNI.Model_convertQuaternionsToDirectionCosines__SWIG_0(swigCPtr, aQ1, aQ2, aQ3, aQ4, SWIGTYPE_p_a_3__double.getCPtr(rDirCos));
  }

  public void convertQuaternionsToDirectionCosines(double aQ1, double aQ2, double aQ3, double aQ4, SWIGTYPE_p_double rDirCos) {
    opensimModelJNI.Model_convertQuaternionsToDirectionCosines__SWIG_1(swigCPtr, aQ1, aQ2, aQ3, aQ4, SWIGTYPE_p_double.getCPtr(rDirCos));
  }

  public void computeActuation() {
    opensimModelJNI.Model_computeActuation(swigCPtr);
  }

  public void applyActuatorForce(int aID) {
    opensimModelJNI.Model_applyActuatorForce(swigCPtr, aID);
  }

  public void applyActuatorForces() {
    opensimModelJNI.Model_applyActuatorForces(swigCPtr);
  }

  public void setActuatorForce(int aID, double aForce) {
    opensimModelJNI.Model_setActuatorForce(swigCPtr, aID, aForce);
  }

  public double getActuatorForce(int aID) {
    return opensimModelJNI.Model_getActuatorForce(swigCPtr, aID);
  }

  public double getActuatorStress(int aID) {
    return opensimModelJNI.Model_getActuatorStress(swigCPtr, aID);
  }

  public double getActuatorSpeed(int aID) {
    return opensimModelJNI.Model_getActuatorSpeed(swigCPtr, aID);
  }

  public double getActuatorPower(int aID) {
    return opensimModelJNI.Model_getActuatorPower(swigCPtr, aID);
  }

  public void computeContact() {
    opensimModelJNI.Model_computeContact(swigCPtr);
  }

  public void applyContactForce(int aID) {
    opensimModelJNI.Model_applyContactForce(swigCPtr, aID);
  }

  public void applyContactForces() {
    opensimModelJNI.Model_applyContactForces(swigCPtr);
  }

  public int getContactBodyA(int aID) {
    return opensimModelJNI.Model_getContactBodyA(swigCPtr, aID);
  }

  public int getContactBodyB(int aID) {
    return opensimModelJNI.Model_getContactBodyB(swigCPtr, aID);
  }

  public void setContactPointA(int aID, double[] aPoint) {
    opensimModelJNI.Model_setContactPointA(swigCPtr, aID, aPoint);
  }

  public void getContactPointA(int aID, double[] rPoint) {
    opensimModelJNI.Model_getContactPointA(swigCPtr, aID, rPoint);
  }

  public void setContactPointB(int aID, double[] aPoint) {
    opensimModelJNI.Model_setContactPointB(swigCPtr, aID, aPoint);
  }

  public void getContactPointB(int aID, double[] rPoint) {
    opensimModelJNI.Model_getContactPointB(swigCPtr, aID, rPoint);
  }

  public void getContactForce(int aID, double[] rF) {
    opensimModelJNI.Model_getContactForce__SWIG_0(swigCPtr, aID, rF);
  }

  public void getContactNormalForce(int aID, double[] rFP, double[] rFV, double[] rF) {
    opensimModelJNI.Model_getContactNormalForce(swigCPtr, aID, rFP, rFV, rF);
  }

  public void getContactTangentForce(int aID, double[] rFP, double[] rFV, double[] rF) {
    opensimModelJNI.Model_getContactTangentForce(swigCPtr, aID, rFP, rFV, rF);
  }

  public void getContactStiffness(int aID, double[] aDX, double[] rDF) {
    opensimModelJNI.Model_getContactStiffness(swigCPtr, aID, aDX, rDF);
  }

  public void getContactViscosity(int aID, double[] aDV, double[] rDF) {
    opensimModelJNI.Model_getContactViscosity(swigCPtr, aID, aDV, rDF);
  }

  public void getContactFrictionCorrection(int aID, double[] aDFFric) {
    opensimModelJNI.Model_getContactFrictionCorrection(swigCPtr, aID, aDFFric);
  }

  public double getContactForce(int aID) {
    return opensimModelJNI.Model_getContactForce__SWIG_1(swigCPtr, aID);
  }

  public double getContactSpeed(int aID) {
    return opensimModelJNI.Model_getContactSpeed(swigCPtr, aID);
  }

  public double getContactPower(int aID) {
    return opensimModelJNI.Model_getContactPower(swigCPtr, aID);
  }

  public AnalysisSet getAnalysisSet() {
    long cPtr = opensimModelJNI.Model_getAnalysisSet(swigCPtr);
    return (cPtr == 0) ? null : new AnalysisSet(cPtr, false);
  }

  public void addAnalysis(Analysis aAnalysis) {
    opensimModelJNI.Model_addAnalysis(swigCPtr, Analysis.getCPtr(aAnalysis));
  }

  public int getNumAnalyses() {
    return opensimModelJNI.Model_getNumAnalyses(swigCPtr);
  }

  public Analysis getAnalysis(int index) {
    return new Analysis(opensimModelJNI.Model_getAnalysis(swigCPtr, index), false);
  }

  public SWIGTYPE_p_OpenSim__IntegCallbackSet getIntegCallbackSet() {
    long cPtr = opensimModelJNI.Model_getIntegCallbackSet(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_OpenSim__IntegCallbackSet(cPtr, false);
  }

  public void addIntegCallback(IntegCallback aCallback) {
    opensimModelJNI.Model_addIntegCallback(swigCPtr, IntegCallback.getCPtr(aCallback));
  }

  public IntegCallback getIntegCallback(int index) {
    return new IntegCallback(opensimModelJNI.Model_getIntegCallback(swigCPtr, index), false);
  }

  public SWIGTYPE_p_OpenSim__DerivCallbackSet getDerivCallbackSet() {
    long cPtr = opensimModelJNI.Model_getDerivCallbackSet(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_OpenSim__DerivCallbackSet(cPtr, false);
  }

  public void addDerivCallback(SWIGTYPE_p_OpenSim__DerivCallback aCallback) {
    opensimModelJNI.Model_addDerivCallback(swigCPtr, SWIGTYPE_p_OpenSim__DerivCallback.getCPtr(aCallback));
  }

  public void setIncludePipelineActuators(boolean include) {
    opensimModelJNI.Model_setIncludePipelineActuators(swigCPtr, include);
  }

  public void computeConstrainedCoordinates(SWIGTYPE_p_double y) {
    opensimModelJNI.Model_computeConstrainedCoordinates(swigCPtr, SWIGTYPE_p_double.getCPtr(y));
  }

  public void formCompleteStorages(Storage aQIn, Storage rQComplete, Storage rUComplete) {
    opensimModelJNI.Model_formCompleteStorages(swigCPtr, Storage.getCPtr(aQIn), Storage.getCPtr(rQComplete), Storage.getCPtr(rUComplete));
  }

  public void printBasicInfo(SWIGTYPE_p_std__ostream aOStream) {
    opensimModelJNI.Model_printBasicInfo(swigCPtr, SWIGTYPE_p_std__ostream.getCPtr(aOStream));
  }

  public void printDetailedInfo(SWIGTYPE_p_std__ostream aOStream) {
    opensimModelJNI.Model_printDetailedInfo(swigCPtr, SWIGTYPE_p_std__ostream.getCPtr(aOStream));
  }

}
