/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class ModelComponent extends OpenSimObject {
  private long swigCPtr;

  public ModelComponent(long cPtr, boolean cMemoryOwn) {
    super(opensimModelJNI.SWIGStorageUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(ModelComponent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      opensimModelJNI.delete_ModelComponent(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public Model getModel() {
    return new Model(opensimModelJNI.ModelComponent_getModel(swigCPtr, this), false);
  }

  public Model updModel() {
    return new Model(opensimModelJNI.ModelComponent_updModel(swigCPtr, this), false);
  }

}
