/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class SetBodies extends OpenSimObject {
  private long swigCPtr;

  public SetBodies(long cPtr, boolean cMemoryOwn) {
    super(opensimModelJNI.SWIGStorageUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(SetBodies obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      opensimModelJNI.delete_SetBodies(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public SetBodies() {
    this(opensimModelJNI.new_SetBodies__SWIG_0(), true);
  }

  public SetBodies(String aFileName) {
    this(opensimModelJNI.new_SetBodies__SWIG_1(aFileName), true);
  }

  public SetBodies(SetBodies aSet) {
    this(opensimModelJNI.new_SetBodies__SWIG_2(SetBodies.getCPtr(aSet), aSet), true);
  }

  public OpenSimObject copy() {
    long cPtr = opensimModelJNI.SetBodies_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new OpenSimObject(cPtr, false);
  }

  public void setMemoryOwner(boolean aTrueFalse) {
    opensimModelJNI.SetBodies_setMemoryOwner(swigCPtr, this, aTrueFalse);
  }

  public boolean getMemoryOwner() {
    return opensimModelJNI.SetBodies_getMemoryOwner(swigCPtr, this);
  }

  public boolean computeNewCapacity(int aMinCapacity, SWIGTYPE_p_int rNewCapacity) {
    return opensimModelJNI.SetBodies_computeNewCapacity(swigCPtr, this, aMinCapacity, SWIGTYPE_p_int.getCPtr(rNewCapacity));
  }

  public boolean ensureCapacity(int aCapacity) {
    return opensimModelJNI.SetBodies_ensureCapacity(swigCPtr, this, aCapacity);
  }

  public void trim() {
    opensimModelJNI.SetBodies_trim(swigCPtr, this);
  }

  public int getCapacity() {
    return opensimModelJNI.SetBodies_getCapacity(swigCPtr, this);
  }

  public void setCapacityIncrement(int aIncrement) {
    opensimModelJNI.SetBodies_setCapacityIncrement(swigCPtr, this, aIncrement);
  }

  public int getCapacityIncrement() {
    return opensimModelJNI.SetBodies_getCapacityIncrement(swigCPtr, this);
  }

  public boolean setSize(int aSize) {
    return opensimModelJNI.SetBodies_setSize(swigCPtr, this, aSize);
  }

  public int getSize() {
    return opensimModelJNI.SetBodies_getSize(swigCPtr, this);
  }

  public int getIndex(AbstractBody aObject, int aStartIndex) {
    return opensimModelJNI.SetBodies_getIndex__SWIG_0(swigCPtr, this, AbstractBody.getCPtr(aObject), aObject, aStartIndex);
  }

  public int getIndex(AbstractBody aObject) {
    return opensimModelJNI.SetBodies_getIndex__SWIG_1(swigCPtr, this, AbstractBody.getCPtr(aObject), aObject);
  }

  public int getIndex(String aName, int aStartIndex) {
    return opensimModelJNI.SetBodies_getIndex__SWIG_2(swigCPtr, this, aName, aStartIndex);
  }

  public int getIndex(String aName) {
    return opensimModelJNI.SetBodies_getIndex__SWIG_3(swigCPtr, this, aName);
  }

  public boolean append(AbstractBody aObject) {
    return opensimModelJNI.SetBodies_append__SWIG_0(swigCPtr, this, AbstractBody.getCPtr(aObject), aObject);
  }

  public boolean append(SWIGTYPE_p_OpenSim__ArrayPtrsTOpenSim__AbstractBody_t aArray) {
    return opensimModelJNI.SetBodies_append__SWIG_1(swigCPtr, this, SWIGTYPE_p_OpenSim__ArrayPtrsTOpenSim__AbstractBody_t.getCPtr(aArray));
  }

  public boolean insert(int aIndex, AbstractBody aObject) {
    return opensimModelJNI.SetBodies_insert(swigCPtr, this, aIndex, AbstractBody.getCPtr(aObject), aObject);
  }

  public boolean remove(int aIndex) {
    return opensimModelJNI.SetBodies_remove__SWIG_0(swigCPtr, this, aIndex);
  }

  public boolean remove(AbstractBody aObject) {
    return opensimModelJNI.SetBodies_remove__SWIG_1(swigCPtr, this, AbstractBody.getCPtr(aObject), aObject);
  }

  public void clearAndDestroy() {
    opensimModelJNI.SetBodies_clearAndDestroy(swigCPtr, this);
  }

  public boolean set(int aIndex, AbstractBody aObject) {
    return opensimModelJNI.SetBodies_set(swigCPtr, this, aIndex, AbstractBody.getCPtr(aObject), aObject);
  }

  public AbstractBody get(int aIndex) {
    long cPtr = opensimModelJNI.SetBodies_get__SWIG_0(swigCPtr, this, aIndex);
    return (cPtr == 0) ? null : new AbstractBody(cPtr, false);
  }

  public AbstractBody get(String aName) {
    long cPtr = opensimModelJNI.SetBodies_get__SWIG_1(swigCPtr, this, aName);
    return (cPtr == 0) ? null : new AbstractBody(cPtr, false);
  }

  public void getNames(ArrayStr rNames) {
    opensimModelJNI.SetBodies_getNames(swigCPtr, this, ArrayStr.getCPtr(rNames), rNames);
  }

  public AbstractBody getLast() {
    long cPtr = opensimModelJNI.SetBodies_getLast(swigCPtr, this);
    return (cPtr == 0) ? null : new AbstractBody(cPtr, false);
  }

  public int searchBinary(AbstractBody aObject, boolean aFindFirst, int aLo, int aHi) {
    return opensimModelJNI.SetBodies_searchBinary__SWIG_0(swigCPtr, this, AbstractBody.getCPtr(aObject), aObject, aFindFirst, aLo, aHi);
  }

  public int searchBinary(AbstractBody aObject, boolean aFindFirst, int aLo) {
    return opensimModelJNI.SetBodies_searchBinary__SWIG_1(swigCPtr, this, AbstractBody.getCPtr(aObject), aObject, aFindFirst, aLo);
  }

  public int searchBinary(AbstractBody aObject, boolean aFindFirst) {
    return opensimModelJNI.SetBodies_searchBinary__SWIG_2(swigCPtr, this, AbstractBody.getCPtr(aObject), aObject, aFindFirst);
  }

  public int searchBinary(AbstractBody aObject) {
    return opensimModelJNI.SetBodies_searchBinary__SWIG_3(swigCPtr, this, AbstractBody.getCPtr(aObject), aObject);
  }

  public void addGroup(SWIGTYPE_p_std__string aGroupName) {
    opensimModelJNI.SetBodies_addGroup(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(aGroupName));
  }

  public void addObjectToGroup(SWIGTYPE_p_std__string aGroupName, SWIGTYPE_p_std__string aObjectName) {
    opensimModelJNI.SetBodies_addObjectToGroup(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(aGroupName), SWIGTYPE_p_std__string.getCPtr(aObjectName));
  }

}
