/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class SetJoints extends OpenSimObject {
  private long swigCPtr;

  public SetJoints(long cPtr, boolean cMemoryOwn) {
    super(opensimModelJNI.SWIGStorageUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(SetJoints obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      opensimModelJNI.delete_SetJoints(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public SetJoints() {
    this(opensimModelJNI.new_SetJoints__SWIG_0(), true);
  }

  public SetJoints(String aFileName) {
    this(opensimModelJNI.new_SetJoints__SWIG_1(aFileName), true);
  }

  public SetJoints(SWIGTYPE_p_DOMElement aElement) {
    this(opensimModelJNI.new_SetJoints__SWIG_2(SWIGTYPE_p_DOMElement.getCPtr(aElement)), true);
  }

  public SetJoints(SetJoints aSet) {
    this(opensimModelJNI.new_SetJoints__SWIG_3(SetJoints.getCPtr(aSet)), true);
  }

  public OpenSimObject copy() {
    long cPtr = opensimModelJNI.SetJoints_copy(swigCPtr);
    return (cPtr == 0) ? null : new OpenSimObject(cPtr, false);
  }

  public void setMemoryOwner(boolean aTrueFalse) {
    opensimModelJNI.SetJoints_setMemoryOwner(swigCPtr, aTrueFalse);
  }

  public boolean getMemoryOwner() {
    return opensimModelJNI.SetJoints_getMemoryOwner(swigCPtr);
  }

  public boolean computeNewCapacity(int aMinCapacity, SWIGTYPE_p_int rNewCapacity) {
    return opensimModelJNI.SetJoints_computeNewCapacity(swigCPtr, aMinCapacity, SWIGTYPE_p_int.getCPtr(rNewCapacity));
  }

  public boolean ensureCapacity(int aCapacity) {
    return opensimModelJNI.SetJoints_ensureCapacity(swigCPtr, aCapacity);
  }

  public void trim() {
    opensimModelJNI.SetJoints_trim(swigCPtr);
  }

  public int getCapacity() {
    return opensimModelJNI.SetJoints_getCapacity(swigCPtr);
  }

  public void setCapacityIncrement(int aIncrement) {
    opensimModelJNI.SetJoints_setCapacityIncrement(swigCPtr, aIncrement);
  }

  public int getCapacityIncrement() {
    return opensimModelJNI.SetJoints_getCapacityIncrement(swigCPtr);
  }

  public boolean setSize(int aSize) {
    return opensimModelJNI.SetJoints_setSize(swigCPtr, aSize);
  }

  public int getSize() {
    return opensimModelJNI.SetJoints_getSize(swigCPtr);
  }

  public int getIndex(AbstractJoint aObject, int aStartIndex) {
    return opensimModelJNI.SetJoints_getIndex__SWIG_0(swigCPtr, AbstractJoint.getCPtr(aObject), aStartIndex);
  }

  public int getIndex(AbstractJoint aObject) {
    return opensimModelJNI.SetJoints_getIndex__SWIG_1(swigCPtr, AbstractJoint.getCPtr(aObject));
  }

  public int getIndex(String aName, int aStartIndex) {
    return opensimModelJNI.SetJoints_getIndex__SWIG_2(swigCPtr, aName, aStartIndex);
  }

  public int getIndex(String aName) {
    return opensimModelJNI.SetJoints_getIndex__SWIG_3(swigCPtr, aName);
  }

  public boolean append(AbstractJoint aObject) {
    return opensimModelJNI.SetJoints_append__SWIG_0(swigCPtr, AbstractJoint.getCPtr(aObject));
  }

  public boolean append(SWIGTYPE_p_OpenSim__ArrayPtrsTOpenSim__AbstractJoint_t aArray) {
    return opensimModelJNI.SetJoints_append__SWIG_1(swigCPtr, SWIGTYPE_p_OpenSim__ArrayPtrsTOpenSim__AbstractJoint_t.getCPtr(aArray));
  }

  public boolean insert(int aIndex, AbstractJoint aObject) {
    return opensimModelJNI.SetJoints_insert(swigCPtr, aIndex, AbstractJoint.getCPtr(aObject));
  }

  public boolean remove(int aIndex) {
    return opensimModelJNI.SetJoints_remove__SWIG_0(swigCPtr, aIndex);
  }

  public boolean remove(AbstractJoint aObject) {
    return opensimModelJNI.SetJoints_remove__SWIG_1(swigCPtr, AbstractJoint.getCPtr(aObject));
  }

  public void clearAndDestroy() {
    opensimModelJNI.SetJoints_clearAndDestroy(swigCPtr);
  }

  public boolean set(int aIndex, AbstractJoint aObject) {
    return opensimModelJNI.SetJoints_set(swigCPtr, aIndex, AbstractJoint.getCPtr(aObject));
  }

  public AbstractJoint get(int aIndex) {
    long cPtr = opensimModelJNI.SetJoints_get__SWIG_0(swigCPtr, aIndex);
    return (cPtr == 0) ? null : new AbstractJoint(cPtr, false);
  }

  public AbstractJoint get(String aName) {
    long cPtr = opensimModelJNI.SetJoints_get__SWIG_1(swigCPtr, aName);
    return (cPtr == 0) ? null : new AbstractJoint(cPtr, false);
  }

  public void getNames(ArrayStr rNames) {
    opensimModelJNI.SetJoints_getNames(swigCPtr, ArrayStr.getCPtr(rNames));
  }

  public AbstractJoint getLast() {
    long cPtr = opensimModelJNI.SetJoints_getLast(swigCPtr);
    return (cPtr == 0) ? null : new AbstractJoint(cPtr, false);
  }

  public int searchBinary(AbstractJoint aObject, boolean aFindFirst, int aLo, int aHi) {
    return opensimModelJNI.SetJoints_searchBinary__SWIG_0(swigCPtr, AbstractJoint.getCPtr(aObject), aFindFirst, aLo, aHi);
  }

  public int searchBinary(AbstractJoint aObject, boolean aFindFirst, int aLo) {
    return opensimModelJNI.SetJoints_searchBinary__SWIG_1(swigCPtr, AbstractJoint.getCPtr(aObject), aFindFirst, aLo);
  }

  public int searchBinary(AbstractJoint aObject, boolean aFindFirst) {
    return opensimModelJNI.SetJoints_searchBinary__SWIG_2(swigCPtr, AbstractJoint.getCPtr(aObject), aFindFirst);
  }

  public int searchBinary(AbstractJoint aObject) {
    return opensimModelJNI.SetJoints_searchBinary__SWIG_3(swigCPtr, AbstractJoint.getCPtr(aObject));
  }

}
