/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class SetMarkers extends OpenSimObject {
  private long swigCPtr;

  public SetMarkers(long cPtr, boolean cMemoryOwn) {
    super(opensimModelJNI.SWIGStorageUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(SetMarkers obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      opensimModelJNI.delete_SetMarkers(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public SetMarkers() {
    this(opensimModelJNI.new_SetMarkers__SWIG_0(), true);
  }

  public SetMarkers(String aFileName) {
    this(opensimModelJNI.new_SetMarkers__SWIG_1(aFileName), true);
  }

  public SetMarkers(SetMarkers aSet) {
    this(opensimModelJNI.new_SetMarkers__SWIG_2(SetMarkers.getCPtr(aSet)), true);
  }

  public OpenSimObject copy() {
    long cPtr = opensimModelJNI.SetMarkers_copy(swigCPtr);
    return (cPtr == 0) ? null : new OpenSimObject(cPtr, false);
  }

  public void setMemoryOwner(boolean aTrueFalse) {
    opensimModelJNI.SetMarkers_setMemoryOwner(swigCPtr, aTrueFalse);
  }

  public boolean getMemoryOwner() {
    return opensimModelJNI.SetMarkers_getMemoryOwner(swigCPtr);
  }

  public boolean computeNewCapacity(int aMinCapacity, SWIGTYPE_p_int rNewCapacity) {
    return opensimModelJNI.SetMarkers_computeNewCapacity(swigCPtr, aMinCapacity, SWIGTYPE_p_int.getCPtr(rNewCapacity));
  }

  public boolean ensureCapacity(int aCapacity) {
    return opensimModelJNI.SetMarkers_ensureCapacity(swigCPtr, aCapacity);
  }

  public void trim() {
    opensimModelJNI.SetMarkers_trim(swigCPtr);
  }

  public int getCapacity() {
    return opensimModelJNI.SetMarkers_getCapacity(swigCPtr);
  }

  public void setCapacityIncrement(int aIncrement) {
    opensimModelJNI.SetMarkers_setCapacityIncrement(swigCPtr, aIncrement);
  }

  public int getCapacityIncrement() {
    return opensimModelJNI.SetMarkers_getCapacityIncrement(swigCPtr);
  }

  public boolean setSize(int aSize) {
    return opensimModelJNI.SetMarkers_setSize(swigCPtr, aSize);
  }

  public int getSize() {
    return opensimModelJNI.SetMarkers_getSize(swigCPtr);
  }

  public int getIndex(AbstractMarker aObject, int aStartIndex) {
    return opensimModelJNI.SetMarkers_getIndex__SWIG_0(swigCPtr, AbstractMarker.getCPtr(aObject), aStartIndex);
  }

  public int getIndex(AbstractMarker aObject) {
    return opensimModelJNI.SetMarkers_getIndex__SWIG_1(swigCPtr, AbstractMarker.getCPtr(aObject));
  }

  public int getIndex(String aName, int aStartIndex) {
    return opensimModelJNI.SetMarkers_getIndex__SWIG_2(swigCPtr, aName, aStartIndex);
  }

  public int getIndex(String aName) {
    return opensimModelJNI.SetMarkers_getIndex__SWIG_3(swigCPtr, aName);
  }

  public boolean append(AbstractMarker aObject) {
    return opensimModelJNI.SetMarkers_append__SWIG_0(swigCPtr, AbstractMarker.getCPtr(aObject));
  }

  public boolean append(SWIGTYPE_p_OpenSim__ArrayPtrsTOpenSim__AbstractMarker_t aArray) {
    return opensimModelJNI.SetMarkers_append__SWIG_1(swigCPtr, SWIGTYPE_p_OpenSim__ArrayPtrsTOpenSim__AbstractMarker_t.getCPtr(aArray));
  }

  public boolean insert(int aIndex, AbstractMarker aObject) {
    return opensimModelJNI.SetMarkers_insert(swigCPtr, aIndex, AbstractMarker.getCPtr(aObject));
  }

  public boolean remove(int aIndex) {
    return opensimModelJNI.SetMarkers_remove__SWIG_0(swigCPtr, aIndex);
  }

  public boolean remove(AbstractMarker aObject) {
    return opensimModelJNI.SetMarkers_remove__SWIG_1(swigCPtr, AbstractMarker.getCPtr(aObject));
  }

  public void clearAndDestroy() {
    opensimModelJNI.SetMarkers_clearAndDestroy(swigCPtr);
  }

  public boolean set(int aIndex, AbstractMarker aObject) {
    return opensimModelJNI.SetMarkers_set(swigCPtr, aIndex, AbstractMarker.getCPtr(aObject));
  }

  public AbstractMarker get(int aIndex) {
    long cPtr = opensimModelJNI.SetMarkers_get__SWIG_0(swigCPtr, aIndex);
    return (cPtr == 0) ? null : new AbstractMarker(cPtr, false);
  }

  public AbstractMarker get(String aName) {
    long cPtr = opensimModelJNI.SetMarkers_get__SWIG_1(swigCPtr, aName);
    return (cPtr == 0) ? null : new AbstractMarker(cPtr, false);
  }

  public void getNames(ArrayStr rNames) {
    opensimModelJNI.SetMarkers_getNames(swigCPtr, ArrayStr.getCPtr(rNames));
  }

  public AbstractMarker getLast() {
    long cPtr = opensimModelJNI.SetMarkers_getLast(swigCPtr);
    return (cPtr == 0) ? null : new AbstractMarker(cPtr, false);
  }

  public int searchBinary(AbstractMarker aObject, boolean aFindFirst, int aLo, int aHi) {
    return opensimModelJNI.SetMarkers_searchBinary__SWIG_0(swigCPtr, AbstractMarker.getCPtr(aObject), aFindFirst, aLo, aHi);
  }

  public int searchBinary(AbstractMarker aObject, boolean aFindFirst, int aLo) {
    return opensimModelJNI.SetMarkers_searchBinary__SWIG_1(swigCPtr, AbstractMarker.getCPtr(aObject), aFindFirst, aLo);
  }

  public int searchBinary(AbstractMarker aObject, boolean aFindFirst) {
    return opensimModelJNI.SetMarkers_searchBinary__SWIG_2(swigCPtr, AbstractMarker.getCPtr(aObject), aFindFirst);
  }

  public int searchBinary(AbstractMarker aObject) {
    return opensimModelJNI.SetMarkers_searchBinary__SWIG_3(swigCPtr, AbstractMarker.getCPtr(aObject));
  }

}
