/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class SetSimmBodies extends OpenSimObject {
  private long swigCPtr;

  public SetSimmBodies(long cPtr, boolean cMemoryOwn) {
    super(opensimModelJNI.SWIGStorageUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(SetSimmBodies obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      opensimModelJNI.delete_SetSimmBodies(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public SetSimmBodies() {
    this(opensimModelJNI.new_SetSimmBodies__SWIG_0(), true);
  }

  public SetSimmBodies(String aFileName) {
    this(opensimModelJNI.new_SetSimmBodies__SWIG_1(aFileName), true);
  }

  public SetSimmBodies(SWIGTYPE_p_DOMElement aElement) {
    this(opensimModelJNI.new_SetSimmBodies__SWIG_2(SWIGTYPE_p_DOMElement.getCPtr(aElement)), true);
  }

  public SetSimmBodies(SetSimmBodies aSet) {
    this(opensimModelJNI.new_SetSimmBodies__SWIG_3(SetSimmBodies.getCPtr(aSet)), true);
  }

  public OpenSimObject copy() {
    long cPtr = opensimModelJNI.SetSimmBodies_copy(swigCPtr);
    return (cPtr == 0) ? null : new OpenSimObject(cPtr, false);
  }

  public void setMemoryOwner(boolean aTrueFalse) {
    opensimModelJNI.SetSimmBodies_setMemoryOwner(swigCPtr, aTrueFalse);
  }

  public boolean getMemoryOwner() {
    return opensimModelJNI.SetSimmBodies_getMemoryOwner(swigCPtr);
  }

  public boolean computeNewCapacity(int aMinCapacity, SWIGTYPE_p_int rNewCapacity) {
    return opensimModelJNI.SetSimmBodies_computeNewCapacity(swigCPtr, aMinCapacity, SWIGTYPE_p_int.getCPtr(rNewCapacity));
  }

  public boolean ensureCapacity(int aCapacity) {
    return opensimModelJNI.SetSimmBodies_ensureCapacity(swigCPtr, aCapacity);
  }

  public void trim() {
    opensimModelJNI.SetSimmBodies_trim(swigCPtr);
  }

  public int getCapacity() {
    return opensimModelJNI.SetSimmBodies_getCapacity(swigCPtr);
  }

  public void setCapacityIncrement(int aIncrement) {
    opensimModelJNI.SetSimmBodies_setCapacityIncrement(swigCPtr, aIncrement);
  }

  public int getCapacityIncrement() {
    return opensimModelJNI.SetSimmBodies_getCapacityIncrement(swigCPtr);
  }

  public boolean setSize(int aSize) {
    return opensimModelJNI.SetSimmBodies_setSize(swigCPtr, aSize);
  }

  public int getSize() {
    return opensimModelJNI.SetSimmBodies_getSize(swigCPtr);
  }

  public int getIndex(SimmBody aObject, int aStartIndex) {
    return opensimModelJNI.SetSimmBodies_getIndex__SWIG_0(swigCPtr, SimmBody.getCPtr(aObject), aStartIndex);
  }

  public int getIndex(SimmBody aObject) {
    return opensimModelJNI.SetSimmBodies_getIndex__SWIG_1(swigCPtr, SimmBody.getCPtr(aObject));
  }

  public int getIndex(String aName, int aStartIndex) {
    return opensimModelJNI.SetSimmBodies_getIndex__SWIG_2(swigCPtr, aName, aStartIndex);
  }

  public int getIndex(String aName) {
    return opensimModelJNI.SetSimmBodies_getIndex__SWIG_3(swigCPtr, aName);
  }

  public boolean append(SimmBody aObject) {
    return opensimModelJNI.SetSimmBodies_append__SWIG_0(swigCPtr, SimmBody.getCPtr(aObject));
  }

  public boolean append(SWIGTYPE_p_OpenSim__ArrayPtrsTOpenSim__SimmBody_t aArray) {
    return opensimModelJNI.SetSimmBodies_append__SWIG_1(swigCPtr, SWIGTYPE_p_OpenSim__ArrayPtrsTOpenSim__SimmBody_t.getCPtr(aArray));
  }

  public boolean insert(int aIndex, SimmBody aObject) {
    return opensimModelJNI.SetSimmBodies_insert(swigCPtr, aIndex, SimmBody.getCPtr(aObject));
  }

  public boolean remove(int aIndex) {
    return opensimModelJNI.SetSimmBodies_remove__SWIG_0(swigCPtr, aIndex);
  }

  public boolean remove(SimmBody aObject) {
    return opensimModelJNI.SetSimmBodies_remove__SWIG_1(swigCPtr, SimmBody.getCPtr(aObject));
  }

  public boolean set(int aIndex, SimmBody aObject) {
    return opensimModelJNI.SetSimmBodies_set(swigCPtr, aIndex, SimmBody.getCPtr(aObject));
  }

  public SimmBody get(int aIndex) {
    long cPtr = opensimModelJNI.SetSimmBodies_get__SWIG_0(swigCPtr, aIndex);
    return (cPtr == 0) ? null : new SimmBody(cPtr, false);
  }

  public SimmBody get(String aName) {
    long cPtr = opensimModelJNI.SetSimmBodies_get__SWIG_1(swigCPtr, aName);
    return (cPtr == 0) ? null : new SimmBody(cPtr, false);
  }

  public SimmBody getLast() {
    long cPtr = opensimModelJNI.SetSimmBodies_getLast(swigCPtr);
    return (cPtr == 0) ? null : new SimmBody(cPtr, false);
  }

  public int searchBinary(SimmBody aObject, boolean aFindFirst, int aLo, int aHi) {
    return opensimModelJNI.SetSimmBodies_searchBinary__SWIG_0(swigCPtr, SimmBody.getCPtr(aObject), aFindFirst, aLo, aHi);
  }

  public int searchBinary(SimmBody aObject, boolean aFindFirst, int aLo) {
    return opensimModelJNI.SetSimmBodies_searchBinary__SWIG_1(swigCPtr, SimmBody.getCPtr(aObject), aFindFirst, aLo);
  }

  public int searchBinary(SimmBody aObject, boolean aFindFirst) {
    return opensimModelJNI.SetSimmBodies_searchBinary__SWIG_2(swigCPtr, SimmBody.getCPtr(aObject), aFindFirst);
  }

  public int searchBinary(SimmBody aObject) {
    return opensimModelJNI.SetSimmBodies_searchBinary__SWIG_3(swigCPtr, SimmBody.getCPtr(aObject));
  }

}
