/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class SetTransformAxis extends OpenSimObject {
  private long swigCPtr;

  public SetTransformAxis(long cPtr, boolean cMemoryOwn) {
    super(opensimModelJNI.SWIGStorageUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(SetTransformAxis obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      opensimModelJNI.delete_SetTransformAxis(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public SetTransformAxis() {
    this(opensimModelJNI.new_SetTransformAxis__SWIG_0(), true);
  }

  public SetTransformAxis(String aFileName, boolean aUpdateFromXMLNode) {
    this(opensimModelJNI.new_SetTransformAxis__SWIG_1(aFileName, aUpdateFromXMLNode), true);
  }

  public SetTransformAxis(String aFileName) {
    this(opensimModelJNI.new_SetTransformAxis__SWIG_2(aFileName), true);
  }

  public SetTransformAxis(SetTransformAxis aSet) {
    this(opensimModelJNI.new_SetTransformAxis__SWIG_3(SetTransformAxis.getCPtr(aSet), aSet), true);
  }

  public OpenSimObject copy() {
    long cPtr = opensimModelJNI.SetTransformAxis_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new OpenSimObject(cPtr, false);
  }

  public void setup() {
    opensimModelJNI.SetTransformAxis_setup(swigCPtr, this);
  }

  public void setMemoryOwner(boolean aTrueFalse) {
    opensimModelJNI.SetTransformAxis_setMemoryOwner(swigCPtr, this, aTrueFalse);
  }

  public boolean getMemoryOwner() {
    return opensimModelJNI.SetTransformAxis_getMemoryOwner(swigCPtr, this);
  }

  public boolean computeNewCapacity(int aMinCapacity, SWIGTYPE_p_int rNewCapacity) {
    return opensimModelJNI.SetTransformAxis_computeNewCapacity(swigCPtr, this, aMinCapacity, SWIGTYPE_p_int.getCPtr(rNewCapacity));
  }

  public boolean ensureCapacity(int aCapacity) {
    return opensimModelJNI.SetTransformAxis_ensureCapacity(swigCPtr, this, aCapacity);
  }

  public void trim() {
    opensimModelJNI.SetTransformAxis_trim(swigCPtr, this);
  }

  public int getCapacity() {
    return opensimModelJNI.SetTransformAxis_getCapacity(swigCPtr, this);
  }

  public void setCapacityIncrement(int aIncrement) {
    opensimModelJNI.SetTransformAxis_setCapacityIncrement(swigCPtr, this, aIncrement);
  }

  public int getCapacityIncrement() {
    return opensimModelJNI.SetTransformAxis_getCapacityIncrement(swigCPtr, this);
  }

  public boolean setSize(int aSize) {
    return opensimModelJNI.SetTransformAxis_setSize(swigCPtr, this, aSize);
  }

  public int getSize() {
    return opensimModelJNI.SetTransformAxis_getSize(swigCPtr, this);
  }

  public int getIndex(AbstractTransformAxis aObject, int aStartIndex) {
    return opensimModelJNI.SetTransformAxis_getIndex__SWIG_0(swigCPtr, this, AbstractTransformAxis.getCPtr(aObject), aObject, aStartIndex);
  }

  public int getIndex(AbstractTransformAxis aObject) {
    return opensimModelJNI.SetTransformAxis_getIndex__SWIG_1(swigCPtr, this, AbstractTransformAxis.getCPtr(aObject), aObject);
  }

  public int getIndex(String aName, int aStartIndex) {
    return opensimModelJNI.SetTransformAxis_getIndex__SWIG_2(swigCPtr, this, aName, aStartIndex);
  }

  public int getIndex(String aName) {
    return opensimModelJNI.SetTransformAxis_getIndex__SWIG_3(swigCPtr, this, aName);
  }

  public void getGroupNamesContaining(String aObjectName, ArrayStr rGroupNames) {
    opensimModelJNI.SetTransformAxis_getGroupNamesContaining(swigCPtr, this, aObjectName, ArrayStr.getCPtr(rGroupNames), rGroupNames);
  }

  public boolean append(AbstractTransformAxis aObject) {
    return opensimModelJNI.SetTransformAxis_append__SWIG_0(swigCPtr, this, AbstractTransformAxis.getCPtr(aObject), aObject);
  }

  public boolean append(SWIGTYPE_p_OpenSim__ArrayPtrsTOpenSim__AbstractTransformAxis_t aArray) {
    return opensimModelJNI.SetTransformAxis_append__SWIG_1(swigCPtr, this, SWIGTYPE_p_OpenSim__ArrayPtrsTOpenSim__AbstractTransformAxis_t.getCPtr(aArray));
  }

  public boolean insert(int aIndex, AbstractTransformAxis aObject) {
    return opensimModelJNI.SetTransformAxis_insert(swigCPtr, this, aIndex, AbstractTransformAxis.getCPtr(aObject), aObject);
  }

  public boolean remove(int aIndex) {
    return opensimModelJNI.SetTransformAxis_remove__SWIG_0(swigCPtr, this, aIndex);
  }

  public boolean remove(AbstractTransformAxis aObject) {
    return opensimModelJNI.SetTransformAxis_remove__SWIG_1(swigCPtr, this, AbstractTransformAxis.getCPtr(aObject), aObject);
  }

  public boolean replace(int aIndex, AbstractTransformAxis aObject) {
    return opensimModelJNI.SetTransformAxis_replace(swigCPtr, this, aIndex, AbstractTransformAxis.getCPtr(aObject), aObject);
  }

  public void clearAndDestroy() {
    opensimModelJNI.SetTransformAxis_clearAndDestroy(swigCPtr, this);
  }

  public boolean set(int aIndex, AbstractTransformAxis aObject) {
    return opensimModelJNI.SetTransformAxis_set(swigCPtr, this, aIndex, AbstractTransformAxis.getCPtr(aObject), aObject);
  }

  public AbstractTransformAxis get(int aIndex) {
    long cPtr = opensimModelJNI.SetTransformAxis_get__SWIG_0(swigCPtr, this, aIndex);
    return (cPtr == 0) ? null : new AbstractTransformAxis(cPtr, false);
  }

  public AbstractTransformAxis get(String aName) {
    long cPtr = opensimModelJNI.SetTransformAxis_get__SWIG_1(swigCPtr, this, aName);
    return (cPtr == 0) ? null : new AbstractTransformAxis(cPtr, false);
  }

  public void getNames(ArrayStr rNames) {
    opensimModelJNI.SetTransformAxis_getNames(swigCPtr, this, ArrayStr.getCPtr(rNames), rNames);
  }

  public AbstractTransformAxis getLast() {
    long cPtr = opensimModelJNI.SetTransformAxis_getLast(swigCPtr, this);
    return (cPtr == 0) ? null : new AbstractTransformAxis(cPtr, false);
  }

  public int searchBinary(AbstractTransformAxis aObject, boolean aFindFirst, int aLo, int aHi) {
    return opensimModelJNI.SetTransformAxis_searchBinary__SWIG_0(swigCPtr, this, AbstractTransformAxis.getCPtr(aObject), aObject, aFindFirst, aLo, aHi);
  }

  public int searchBinary(AbstractTransformAxis aObject, boolean aFindFirst, int aLo) {
    return opensimModelJNI.SetTransformAxis_searchBinary__SWIG_1(swigCPtr, this, AbstractTransformAxis.getCPtr(aObject), aObject, aFindFirst, aLo);
  }

  public int searchBinary(AbstractTransformAxis aObject, boolean aFindFirst) {
    return opensimModelJNI.SetTransformAxis_searchBinary__SWIG_2(swigCPtr, this, AbstractTransformAxis.getCPtr(aObject), aObject, aFindFirst);
  }

  public int searchBinary(AbstractTransformAxis aObject) {
    return opensimModelJNI.SetTransformAxis_searchBinary__SWIG_3(swigCPtr, this, AbstractTransformAxis.getCPtr(aObject), aObject);
  }

  public int getNumGroups() {
    return opensimModelJNI.SetTransformAxis_getNumGroups(swigCPtr, this);
  }

  public void addGroup(String aGroupName) {
    opensimModelJNI.SetTransformAxis_addGroup(swigCPtr, this, aGroupName);
  }

  public void removeGroup(String aGroupName) {
    opensimModelJNI.SetTransformAxis_removeGroup(swigCPtr, this, aGroupName);
  }

  public void renameGroup(String oldGroupName, String newGroupName) {
    opensimModelJNI.SetTransformAxis_renameGroup(swigCPtr, this, oldGroupName, newGroupName);
  }

  public void addObjectToGroup(String aGroupName, String aObjectName) {
    opensimModelJNI.SetTransformAxis_addObjectToGroup(swigCPtr, this, aGroupName, aObjectName);
  }

  public void getGroupNames(ArrayStr rGroupNames) {
    opensimModelJNI.SetTransformAxis_getGroupNames(swigCPtr, this, ArrayStr.getCPtr(rGroupNames), rGroupNames);
  }

  public ObjectGroup getGroup(String aGroupName) {
    long cPtr = opensimModelJNI.SetTransformAxis_getGroup__SWIG_0(swigCPtr, this, aGroupName);
    return (cPtr == 0) ? null : new ObjectGroup(cPtr, false);
  }

  public ObjectGroup getGroup(int aIndex) {
    long cPtr = opensimModelJNI.SetTransformAxis_getGroup__SWIG_1(swigCPtr, this, aIndex);
    return (cPtr == 0) ? null : new ObjectGroup(cPtr, false);
  }

}
