/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class SimmPoint extends OpenSimObject {
  private long swigCPtr;

  public SimmPoint(long cPtr, boolean cMemoryOwn) {
    super(opensimModelJNI.SWIGStorageUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(SimmPoint obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      opensimModelJNI.delete_SimmPoint(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public SimmPoint() {
    this(opensimModelJNI.new_SimmPoint__SWIG_0(), true);
  }

  public SimmPoint(SWIGTYPE_p_SimTK__Vec3 coords) {
    this(opensimModelJNI.new_SimmPoint__SWIG_1(SWIGTYPE_p_SimTK__Vec3.getCPtr(coords)), true);
  }

  public SimmPoint(SimmPoint aPoint) {
    this(opensimModelJNI.new_SimmPoint__SWIG_2(SimmPoint.getCPtr(aPoint), aPoint), true);
  }

  public OpenSimObject copy() {
    long cPtr = opensimModelJNI.SimmPoint_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new OpenSimObject(cPtr, false);
  }

  public void set(double x, double y, double z) {
    opensimModelJNI.SimmPoint_set(swigCPtr, this, x, y, z);
  }

  public SWIGTYPE_p_SimTK__Vec3 get() {
    return new SWIGTYPE_p_SimTK__Vec3(opensimModelJNI.SimmPoint_get(swigCPtr, this), false);
  }

  public void scale(double aScaleFactor) {
    opensimModelJNI.SimmPoint_scale(swigCPtr, this, aScaleFactor);
  }

  public boolean isVisible() {
    return opensimModelJNI.SimmPoint_isVisible(swigCPtr, this);
  }

}
