/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class Tool extends OpenSimObject {
  private long swigCPtr;

  public Tool(long cPtr, boolean cMemoryOwn) {
    super(opensimModelJNI.SWIGStorageUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(Tool obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimModelJNI.delete_Tool(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public boolean run() throws java.io.IOException {
    return opensimModelJNI.Tool_run(swigCPtr, this);
  }

  public String getInputsDir() {
    return opensimModelJNI.Tool_getInputsDir(swigCPtr, this);
  }

  public void setInputsDir(String aString) {
    opensimModelJNI.Tool_setInputsDir(swigCPtr, this, aString);
  }

  public String getResultsDir() {
    return opensimModelJNI.Tool_getResultsDir(swigCPtr, this);
  }

  public void setResultsDir(String aString) {
    opensimModelJNI.Tool_setResultsDir(swigCPtr, this, aString);
  }

}
