/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.19
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package simtkModel;


public class rdControlConstant extends rdControl {
  private long swigCPtr;

  
  public  rdControlConstant(long cPtr, boolean cMemoryOwn) {
    super(ModelJNI.SWIGrdControlConstantTordControl(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected rdControlConstant() {
    this(0, false);
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      ModelJNI.delete_rdControlConstant(swigCPtr);
      swigCMemOwn = false;
      super.delete();
    }
    swigCPtr = 0;
  }

  public static long getCPtr(rdControlConstant obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public rdControlConstant(double aX, String aName) {
    this(ModelJNI.new_rdControlConstant__SWIG_0(aX, aName), true);
  }

  public rdControlConstant(SWIGTYPE_p_DOMElement aElement) {
    this(ModelJNI.new_rdControlConstant__SWIG_1(SWIGTYPE_p_DOMElement.getCPtr(aElement)), true);
  }

  public rdControlConstant(rdControlConstant aControl) {
    this(ModelJNI.new_rdControlConstant__SWIG_2(rdControlConstant.getCPtr(aControl)), true);
  }

  public rdObject copy() {
    long cPtr = ModelJNI.rdControlConstant_copy__SWIG_0(swigCPtr);
    return (cPtr == 0) ? null : new rdObject(cPtr, false);
  }

  public rdObject copy(SWIGTYPE_p_DOMElement aElement) {
    long cPtr = ModelJNI.rdControlConstant_copy__SWIG_1(swigCPtr, SWIGTYPE_p_DOMElement.getCPtr(aElement));
    return (cPtr == 0) ? null : new rdObject(cPtr, false);
  }

  public int getNumParameters() {
    return ModelJNI.rdControlConstant_getNumParameters(swigCPtr);
  }

  public void setParameterMin(int aI, double aMin) {
    ModelJNI.rdControlConstant_setParameterMin(swigCPtr, aI, aMin);
  }

  public double getParameterMin(int aI) {
    return ModelJNI.rdControlConstant_getParameterMin(swigCPtr, aI);
  }

  public void setParameterMax(int aI, double aMax) {
    ModelJNI.rdControlConstant_setParameterMax(swigCPtr, aI, aMax);
  }

  public double getParameterMax(int aI) {
    return ModelJNI.rdControlConstant_getParameterMax(swigCPtr, aI);
  }

  public double getParameterTime(int aI) {
    return ModelJNI.rdControlConstant_getParameterTime(swigCPtr, aI);
  }

  public void getParameterNeighborhood(int aI, SWIGTYPE_p_double rTLower, SWIGTYPE_p_double rTUpper) {
    ModelJNI.rdControlConstant_getParameterNeighborhood(swigCPtr, aI, SWIGTYPE_p_double.getCPtr(rTLower), SWIGTYPE_p_double.getCPtr(rTUpper));
  }

  public int getParameterList(double aT, rdArrayInt rList) {
    return ModelJNI.rdControlConstant_getParameterList__SWIG_0(swigCPtr, aT, rdArrayInt.getCPtr(rList));
  }

  public int getParameterList(double aT1, double aT2, rdArrayInt rList) {
    return ModelJNI.rdControlConstant_getParameterList__SWIG_1(swigCPtr, aT1, aT2, rdArrayInt.getCPtr(rList));
  }

  public void setParameterValue(int aI, double aP) {
    ModelJNI.rdControlConstant_setParameterValue(swigCPtr, aI, aP);
  }

  public double getParameterValue(int aI) {
    return ModelJNI.rdControlConstant_getParameterValue(swigCPtr, aI);
  }

  public void setControlValue(double aT, double aX) {
    ModelJNI.rdControlConstant_setControlValue(swigCPtr, aT, aX);
  }

  public double getControlValue(double aT) {
    return ModelJNI.rdControlConstant_getControlValue(swigCPtr, aT);
  }

  public double getControlValueMin(double aT) {
    return ModelJNI.rdControlConstant_getControlValueMin(swigCPtr, aT);
  }

  public void setControlValueMin(double aT, double aX) {
    ModelJNI.rdControlConstant_setControlValueMin(swigCPtr, aT, aX);
  }

  public double getControlValueMax(double aT) {
    return ModelJNI.rdControlConstant_getControlValueMax(swigCPtr, aT);
  }

  public void setControlValueMax(double aT, double aX) {
    ModelJNI.rdControlConstant_setControlValueMax(swigCPtr, aT, aX);
  }

}
