/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.19
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package simtkModel;


public class rdManager {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  
  public  rdManager(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      ModelJNI.delete_rdManager(swigCPtr);
      swigCMemOwn = false;
    }
    swigCPtr = 0;
  }

  public static long getCPtr(rdManager obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public rdManager(rdModel model, rdControlSet aControlSet) {
    this(ModelJNI.new_rdManager__SWIG_0(rdModel.getCPtr(model), rdControlSet.getCPtr(aControlSet)), true);
  }

  public rdManager() {
    this(ModelJNI.new_rdManager__SWIG_1(), true);
  }

  public void setSessionName(String name) {
    ModelJNI.rdManager_setSessionName(swigCPtr, name);
  }

  public String getSessionName() {
    return ModelJNI.rdManager_getSessionName(swigCPtr);
  }

  public String toString() {
    return ModelJNI.rdManager_toString(swigCPtr);
  }

  public void setModel(rdModel model) {
    ModelJNI.rdManager_setModel(swigCPtr, rdModel.getCPtr(model));
  }

  public rdModel getModel() {
    long cPtr = ModelJNI.rdManager_getModel(swigCPtr);
    return (cPtr == 0) ? null : new rdModel(cPtr, false);
  }

  public rdControlSet setControlSet(rdControlSet aControlSet) {
    long cPtr = ModelJNI.rdManager_setControlSet(swigCPtr, rdControlSet.getCPtr(aControlSet));
    return (cPtr == 0) ? null : new rdControlSet(cPtr, false);
  }

  public rdControlSet getControlSet() {
    long cPtr = ModelJNI.rdManager_getControlSet(swigCPtr);
    return (cPtr == 0) ? null : new rdControlSet(cPtr, false);
  }

  public rdIntegRKF getIntegrator() {
    long cPtr = ModelJNI.rdManager_getIntegrator(swigCPtr);
    return (cPtr == 0) ? null : new rdIntegRKF(cPtr, false);
  }

  public void setInitialTime(double aTI) {
    ModelJNI.rdManager_setInitialTime(swigCPtr, aTI);
  }

  public double getInitialTime() {
    return ModelJNI.rdManager_getInitialTime(swigCPtr);
  }

  public void setFinalTime(double aTF) {
    ModelJNI.rdManager_setFinalTime(swigCPtr, aTF);
  }

  public double getFinalTime() {
    return ModelJNI.rdManager_getFinalTime(swigCPtr);
  }

  public void setFirstDT(double aDT) {
    ModelJNI.rdManager_setFirstDT(swigCPtr, aDT);
  }

  public double getFirstDT() {
    return ModelJNI.rdManager_getFirstDT(swigCPtr);
  }

  public boolean initializeStates() {
    return ModelJNI.rdManager_initializeStates__SWIG_0(swigCPtr);
  }

  public boolean initializeStates(SWIGTYPE_p_double aY, SWIGTYPE_p_double aYP) {
    return ModelJNI.rdManager_initializeStates__SWIG_1(swigCPtr, SWIGTYPE_p_double.getCPtr(aY), SWIGTYPE_p_double.getCPtr(aYP));
  }

  public boolean integrate() {
    return ModelJNI.rdManager_integrate__SWIG_0(swigCPtr);
  }

  public boolean integrate(int startIndex) {
    return ModelJNI.rdManager_integrate__SWIG_1(swigCPtr, startIndex);
  }

  public boolean integrate(double startTime) {
    return ModelJNI.rdManager_integrate__SWIG_2(swigCPtr, startTime);
  }

  public rdControlSet constructControlSet() {
    long cPtr = ModelJNI.rdManager_constructControlSet(swigCPtr);
    return (cPtr == 0) ? null : new rdControlSet(cPtr, false);
  }

}
