/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.19
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package simtkModel;


public class rdSetAnalysis extends rdObject {
  private long swigCPtr;

  
  public  rdSetAnalysis(long cPtr, boolean cMemoryOwn) {
    super(ModelJNI.SWIGrdSetAnalysisTordObject(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      ModelJNI.delete_rdSetAnalysis(swigCPtr);
      swigCMemOwn = false;
      super.delete();
    }
    swigCPtr = 0;
  }

  public static long getCPtr(rdSetAnalysis obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public rdSetAnalysis() {
    this(ModelJNI.new_rdSetAnalysis__SWIG_0(), true);
  }

  public rdSetAnalysis(String aFileName) {
    this(ModelJNI.new_rdSetAnalysis__SWIG_1(aFileName), true);
  }

  public rdSetAnalysis(rdSetAnalysis aSet) {
    this(ModelJNI.new_rdSetAnalysis__SWIG_2(rdSetAnalysis.getCPtr(aSet)), true);
  }

  public rdObject copy() {
    long cPtr = ModelJNI.rdSetAnalysis_copy(swigCPtr);
    return (cPtr == 0) ? null : new rdObject(cPtr, false);
  }

  public void setMemoryOwner(boolean aTrueFalse) {
    ModelJNI.rdSetAnalysis_setMemoryOwner(swigCPtr, aTrueFalse);
  }

  public boolean getMemoryOwner() {
    return ModelJNI.rdSetAnalysis_getMemoryOwner(swigCPtr);
  }

  public boolean computeNewCapacity(int aMinCapacity, SWIGTYPE_p_int rNewCapacity) {
    return ModelJNI.rdSetAnalysis_computeNewCapacity(swigCPtr, aMinCapacity, SWIGTYPE_p_int.getCPtr(rNewCapacity));
  }

  public boolean ensureCapacity(int aCapacity) {
    return ModelJNI.rdSetAnalysis_ensureCapacity(swigCPtr, aCapacity);
  }

  public void trim() {
    ModelJNI.rdSetAnalysis_trim(swigCPtr);
  }

  public int getCapacity() {
    return ModelJNI.rdSetAnalysis_getCapacity(swigCPtr);
  }

  public void setCapacityIncrement(int aIncrement) {
    ModelJNI.rdSetAnalysis_setCapacityIncrement(swigCPtr, aIncrement);
  }

  public int getCapacityIncrement() {
    return ModelJNI.rdSetAnalysis_getCapacityIncrement(swigCPtr);
  }

  public boolean setSize(int aSize) {
    return ModelJNI.rdSetAnalysis_setSize(swigCPtr, aSize);
  }

  public int getSize() {
    return ModelJNI.rdSetAnalysis_getSize(swigCPtr);
  }

  public int getIndex(rdAnalysis aObject, int aStartIndex) {
    return ModelJNI.rdSetAnalysis_getIndex__SWIG_0(swigCPtr, rdAnalysis.getCPtr(aObject), aStartIndex);
  }

  public int getIndex(String aName, int aStartIndex) {
    return ModelJNI.rdSetAnalysis_getIndex__SWIG_1(swigCPtr, aName, aStartIndex);
  }

  public boolean append(rdAnalysis aObject) {
    return ModelJNI.rdSetAnalysis_append__SWIG_0(swigCPtr, rdAnalysis.getCPtr(aObject));
  }

  public boolean append(rdArrayAnalysis aArray) {
    return ModelJNI.rdSetAnalysis_append__SWIG_1(swigCPtr, rdArrayAnalysis.getCPtr(aArray));
  }

  public boolean insert(int aIndex, rdAnalysis aObject) {
    return ModelJNI.rdSetAnalysis_insert(swigCPtr, aIndex, rdAnalysis.getCPtr(aObject));
  }

  public boolean remove(int aIndex) {
    return ModelJNI.rdSetAnalysis_remove__SWIG_0(swigCPtr, aIndex);
  }

  public boolean remove(rdAnalysis aObject) {
    return ModelJNI.rdSetAnalysis_remove__SWIG_1(swigCPtr, rdAnalysis.getCPtr(aObject));
  }

  public boolean set(int aIndex, rdAnalysis aObject) {
    return ModelJNI.rdSetAnalysis_set(swigCPtr, aIndex, rdAnalysis.getCPtr(aObject));
  }

  public rdAnalysis get(int aIndex) {
    long cPtr = ModelJNI.rdSetAnalysis_get__SWIG_0(swigCPtr, aIndex);
    return (cPtr == 0) ? null : new rdAnalysis(cPtr, false);
  }

  public rdAnalysis get(String aName) {
    long cPtr = ModelJNI.rdSetAnalysis_get__SWIG_1(swigCPtr, aName);
    return (cPtr == 0) ? null : new rdAnalysis(cPtr, false);
  }

  public rdAnalysis getLast() {
    long cPtr = ModelJNI.rdSetAnalysis_getLast(swigCPtr);
    return (cPtr == 0) ? null : new rdAnalysis(cPtr, false);
  }

  public int searchBinary(rdAnalysis aObject, boolean aFindFirst, int aLo, int aHi) {
    return ModelJNI.rdSetAnalysis_searchBinary(swigCPtr, rdAnalysis.getCPtr(aObject), aFindFirst, aLo, aHi);
  }

}
