/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.19
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package simtkModel;


public class rdSimtkAnimationCallback extends rdIntegCallback {
  private long swigCPtr;


  public  rdSimtkAnimationCallback(long cPtr, boolean cMemoryOwn) {
    super(ModelJNI.SWIGrdSimtkAnimationCallbackTordIntegCallback(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected rdSimtkAnimationCallback() {
    this(0, false);
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      ModelJNI.delete_rdSimtkAnimationCallback(swigCPtr);
      swigCMemOwn = false;
      super.delete();
    }
    swigCPtr = 0;
  }

  public static long getCPtr(rdSimtkAnimationCallback obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public rdSimtkAnimationCallback(rdModel aModel) {
    this(ModelJNI.new_rdSimtkAnimationCallback(rdModel.getCPtr(aModel)), true);
  }

  public double getCurrentTime() {
    return ModelJNI.rdSimtkAnimationCallback_getCurrentTime(swigCPtr);
  }

  public int step(SWIGTYPE_p_double aXPrev, SWIGTYPE_p_double aYPrev, int aStep, double aDT, double aT, SWIGTYPE_p_double aX, SWIGTYPE_p_double aY, SWIGTYPE_p_void aClientData) {
    return ModelJNI.rdSimtkAnimationCallback_step(swigCPtr, SWIGTYPE_p_double.getCPtr(aXPrev), SWIGTYPE_p_double.getCPtr(aYPrev), aStep, aDT, aT, SWIGTYPE_p_double.getCPtr(aX), SWIGTYPE_p_double.getCPtr(aY), SWIGTYPE_p_void.getCPtr(aClientData));
  }

}
