/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package opensimModel;

public class SetBodies extends OpenSimObject {
  private long swigCPtr;

  protected SetBodies(long cPtr, boolean cMemoryOwn) {
    super(opensimModelJNI.SWIGSetBodiesUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SetBodies obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      opensimModelJNI.delete_SetBodies(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public SetBodies() {
    this(opensimModelJNI.new_SetBodies__SWIG_0(), true);
  }

  public SetBodies(String aFileName) {
    this(opensimModelJNI.new_SetBodies__SWIG_1(aFileName), true);
  }

  public SetBodies(SWIGTYPE_p_DOMElement aElement) {
    this(opensimModelJNI.new_SetBodies__SWIG_2(SWIGTYPE_p_DOMElement.getCPtr(aElement)), true);
  }

  public SetBodies(SetBodies aSet) {
    this(opensimModelJNI.new_SetBodies__SWIG_3(SetBodies.getCPtr(aSet)), true);
  }

  public OpenSimObject copy() {
    long cPtr = opensimModelJNI.SetBodies_copy(swigCPtr);
    return (cPtr == 0) ? null : new OpenSimObject(cPtr, false);
  }

  public void setMemoryOwner(boolean aTrueFalse) {
    opensimModelJNI.SetBodies_setMemoryOwner(swigCPtr, aTrueFalse);
  }

  public boolean getMemoryOwner() {
    return opensimModelJNI.SetBodies_getMemoryOwner(swigCPtr);
  }

  public boolean computeNewCapacity(int aMinCapacity, SWIGTYPE_p_int rNewCapacity) {
    return opensimModelJNI.SetBodies_computeNewCapacity(swigCPtr, aMinCapacity, SWIGTYPE_p_int.getCPtr(rNewCapacity));
  }

  public boolean ensureCapacity(int aCapacity) {
    return opensimModelJNI.SetBodies_ensureCapacity(swigCPtr, aCapacity);
  }

  public void trim() {
    opensimModelJNI.SetBodies_trim(swigCPtr);
  }

  public int getCapacity() {
    return opensimModelJNI.SetBodies_getCapacity(swigCPtr);
  }

  public void setCapacityIncrement(int aIncrement) {
    opensimModelJNI.SetBodies_setCapacityIncrement(swigCPtr, aIncrement);
  }

  public int getCapacityIncrement() {
    return opensimModelJNI.SetBodies_getCapacityIncrement(swigCPtr);
  }

  public boolean setSize(int aSize) {
    return opensimModelJNI.SetBodies_setSize(swigCPtr, aSize);
  }

  public int getSize() {
    return opensimModelJNI.SetBodies_getSize(swigCPtr);
  }

  public int getIndex(Body aObject, int aStartIndex) {
    return opensimModelJNI.SetBodies_getIndex__SWIG_0(swigCPtr, Body.getCPtr(aObject), aStartIndex);
  }

  public int getIndex(Body aObject) {
    return opensimModelJNI.SetBodies_getIndex__SWIG_1(swigCPtr, Body.getCPtr(aObject));
  }

  public int getIndex(String aName, int aStartIndex) {
    return opensimModelJNI.SetBodies_getIndex__SWIG_2(swigCPtr, aName, aStartIndex);
  }

  public int getIndex(String aName) {
    return opensimModelJNI.SetBodies_getIndex__SWIG_3(swigCPtr, aName);
  }

  public boolean append(Body aObject) {
    return opensimModelJNI.SetBodies_append__SWIG_0(swigCPtr, Body.getCPtr(aObject));
  }

  public boolean append(SWIGTYPE_p_OpenSim__ArrayPtrsTOpenSim__Body_t aArray) {
    return opensimModelJNI.SetBodies_append__SWIG_1(swigCPtr, SWIGTYPE_p_OpenSim__ArrayPtrsTOpenSim__Body_t.getCPtr(aArray));
  }

  public boolean insert(int aIndex, Body aObject) {
    return opensimModelJNI.SetBodies_insert(swigCPtr, aIndex, Body.getCPtr(aObject));
  }

  public boolean remove(int aIndex) {
    return opensimModelJNI.SetBodies_remove__SWIG_0(swigCPtr, aIndex);
  }

  public boolean remove(Body aObject) {
    return opensimModelJNI.SetBodies_remove__SWIG_1(swigCPtr, Body.getCPtr(aObject));
  }

  public boolean set(int aIndex, Body aObject) {
    return opensimModelJNI.SetBodies_set(swigCPtr, aIndex, Body.getCPtr(aObject));
  }

  public Body get(int aIndex) {
    long cPtr = opensimModelJNI.SetBodies_get__SWIG_0(swigCPtr, aIndex);
    return (cPtr == 0) ? null : new Body(cPtr, false);
  }

  public Body get(String aName) {
    long cPtr = opensimModelJNI.SetBodies_get__SWIG_1(swigCPtr, aName);
    return (cPtr == 0) ? null : new Body(cPtr, false);
  }

  public Body getLast() {
    long cPtr = opensimModelJNI.SetBodies_getLast(swigCPtr);
    return (cPtr == 0) ? null : new Body(cPtr, false);
  }

  public int searchBinary(Body aObject, boolean aFindFirst, int aLo, int aHi) {
    return opensimModelJNI.SetBodies_searchBinary__SWIG_0(swigCPtr, Body.getCPtr(aObject), aFindFirst, aLo, aHi);
  }

  public int searchBinary(Body aObject, boolean aFindFirst, int aLo) {
    return opensimModelJNI.SetBodies_searchBinary__SWIG_1(swigCPtr, Body.getCPtr(aObject), aFindFirst, aLo);
  }

  public int searchBinary(Body aObject, boolean aFindFirst) {
    return opensimModelJNI.SetBodies_searchBinary__SWIG_2(swigCPtr, Body.getCPtr(aObject), aFindFirst);
  }

  public int searchBinary(Body aObject) {
    return opensimModelJNI.SetBodies_searchBinary__SWIG_3(swigCPtr, Body.getCPtr(aObject));
  }

}
