package org.opensim.view.editors;

import java.awt.Component;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.io.Serializable;
import java.lang.String;
import javax.swing.ScrollPaneConstants;
import javax.swing.SwingConstants;
import org.openide.ErrorManager;
import org.openide.nodes.Node;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;
import org.opensim.modeling.AbstractActuator;
import org.opensim.modeling.AbstractModel;
import org.opensim.modeling.BodySet;
import org.opensim.modeling.Function;
import org.opensim.modeling.OpenSimObject;
import org.opensim.modeling.Property;
import org.opensim.modeling.PropertySet;
import org.opensim.modeling.SetSimmMusclePoint;
import org.opensim.modeling.SimmDarrylMuscle;
import org.opensim.modeling.SimmMusclePoint;
import org.opensim.modeling.SimmMusclePointSet;
import org.opensim.modeling.AbstractSimmMuscle;
import org.opensim.view.ExplorerTopComponent;
import org.opensim.view.NameChangedEvent;
import org.opensim.view.nodes.OneMuscleNode;
import org.opensim.view.pub.OpenSimDB;

/**
 * Top component which displays the Muscle Editor window.
 */
final class MuscleEditorTopComponent extends TopComponent {
   
   private static MuscleEditorTopComponent instance;
   private AbstractActuator act; // the actuator that is currently shown in the Muscle Editor window
   private static Dimension AttachmentsPref = new Dimension(100, 100);
   private static Dimension ForcePref = new Dimension(100, 100);
   private static Dimension DynamicPref = new Dimension(100, 100);
   private static Dimension FunctionsPref = new Dimension(100, 100);
   private static Dimension WrapPref = new Dimension(100, 100);
   
   /** path to the icon used by the component and its open action */
//    static final String ICON_PATH = "SET/PATH/TO/ICON/HERE";
   
   private static final String PREFERRED_ID = "MuscleEditorTopComponent";
   
   private MuscleEditorTopComponent() {
      initComponents();
      setName(NbBundle.getMessage(MuscleEditorTopComponent.class, "CTL_MuscleEditorTopComponent"));
      setToolTipText(NbBundle.getMessage(MuscleEditorTopComponent.class, "HINT_MuscleEditorTopComponent"));
//        setIcon(Utilities.loadImage(ICON_PATH, true));
   }
   
   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
   private void initComponents() {
      MuscleNameLabel = new javax.swing.JLabel();
      MuscleNameTextField = new javax.swing.JTextField();
      MuscleTypeLabel = new javax.swing.JLabel();
      MuscleTypeComboBox = new javax.swing.JComboBox();
      ApplyButton = new javax.swing.JButton();
      ResetButton = new javax.swing.JButton();
      ParametersTabbedPanel = new javax.swing.JTabbedPane();
      AttachmentsTab = new javax.swing.JScrollPane();
      AttachmentsPanel = new javax.swing.JPanel();
      AttachmentXLabel = new javax.swing.JLabel();
      AttachmentYLabel = new javax.swing.JLabel();
      AttachmentZLabel = new javax.swing.JLabel();
      AttachmentBodyLabel = new javax.swing.JLabel();
      AttachmentSelectedLabel = new javax.swing.JLabel();
      ForceTab = new javax.swing.JScrollPane();
      ForcePanel = new javax.swing.JPanel();
      DynamicTab = new javax.swing.JScrollPane();
      DynamicPanel = new javax.swing.JPanel();
      FunctionsTab = new javax.swing.JScrollPane();
      FunctionsPanel = new javax.swing.JPanel();
      WrappingTab = new javax.swing.JScrollPane();
      WrapPanel = new javax.swing.JPanel();
      WrapObjectLabel = new javax.swing.JLabel();
      WrapMethodLabel = new javax.swing.JLabel();
      WrapRangeStartLabel = new javax.swing.JLabel();
      WrapRangeEndLabel = new javax.swing.JLabel();
      jLabel10 = new javax.swing.JLabel();
      jComboBox12 = new javax.swing.JComboBox();
      jComboBox13 = new javax.swing.JComboBox();
      jComboBox14 = new javax.swing.JComboBox();
      jComboBox15 = new javax.swing.JComboBox();

      org.openide.awt.Mnemonics.setLocalizedText(MuscleNameLabel, "name:");

      MuscleNameTextField.setText("glut_med1_r");

      MuscleTypeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
      org.openide.awt.Mnemonics.setLocalizedText(MuscleTypeLabel, "type:");

      MuscleTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DarrylMuscle", "Item 1", "Item 2", "Item 3", "Item 4" }));

      ApplyButton.setBackground(new java.awt.Color(51, 153, 0));
      org.openide.awt.Mnemonics.setLocalizedText(ApplyButton, "apply");

      ResetButton.setBackground(new java.awt.Color(204, 0, 0));
      org.openide.awt.Mnemonics.setLocalizedText(ResetButton, "reset");
      ResetButton.setMaximumSize(new java.awt.Dimension(63, 25));
      ResetButton.setMinimumSize(new java.awt.Dimension(63, 25));
      ResetButton.setPreferredSize(new java.awt.Dimension(63, 25));

      AttachmentsPanel.setLayout(null);

      org.openide.awt.Mnemonics.setLocalizedText(AttachmentXLabel, "X");
      AttachmentsPanel.add(AttachmentXLabel);
      AttachmentXLabel.setBounds(50, 10, 8, 16);

      org.openide.awt.Mnemonics.setLocalizedText(AttachmentYLabel, "Y");
      AttachmentsPanel.add(AttachmentYLabel);
      AttachmentYLabel.setBounds(110, 10, 7, 16);

      org.openide.awt.Mnemonics.setLocalizedText(AttachmentZLabel, "Z");
      AttachmentsPanel.add(AttachmentZLabel);
      AttachmentZLabel.setBounds(170, 10, 7, 16);

      org.openide.awt.Mnemonics.setLocalizedText(AttachmentBodyLabel, "body");
      AttachmentsPanel.add(AttachmentBodyLabel);
      AttachmentBodyLabel.setBounds(240, 10, 27, 16);

      org.openide.awt.Mnemonics.setLocalizedText(AttachmentSelectedLabel, "sel");
      AttachmentsPanel.add(AttachmentSelectedLabel);
      AttachmentSelectedLabel.setBounds(320, 10, 16, 16);

      AttachmentsTab.setViewportView(AttachmentsPanel);

      ParametersTabbedPanel.addTab("attachments", AttachmentsTab);

      ForcePanel.setLayout(null);

      ForceTab.setViewportView(ForcePanel);

      ParametersTabbedPanel.addTab("force", ForceTab);

      DynamicPanel.setLayout(null);

      DynamicTab.setViewportView(DynamicPanel);

      ParametersTabbedPanel.addTab("dynamic", DynamicTab);

      FunctionsPanel.setLayout(null);

      FunctionsTab.setViewportView(FunctionsPanel);

      ParametersTabbedPanel.addTab("functions", FunctionsTab);

      WrapPanel.setLayout(null);

      org.openide.awt.Mnemonics.setLocalizedText(WrapObjectLabel, "object");
      WrapPanel.add(WrapObjectLabel);
      WrapObjectLabel.setBounds(70, 50, 35, 16);

      org.openide.awt.Mnemonics.setLocalizedText(WrapMethodLabel, "  method");
      WrapPanel.add(WrapMethodLabel);
      WrapMethodLabel.setBounds(150, 50, 51, 16);

      org.openide.awt.Mnemonics.setLocalizedText(WrapRangeStartLabel, "start");
      WrapPanel.add(WrapRangeStartLabel);
      WrapRangeStartLabel.setBounds(220, 50, 26, 16);

      org.openide.awt.Mnemonics.setLocalizedText(WrapRangeEndLabel, "end");
      WrapPanel.add(WrapRangeEndLabel);
      WrapRangeEndLabel.setBounds(280, 50, 21, 16);

      org.openide.awt.Mnemonics.setLocalizedText(jLabel10, "1.");
      WrapPanel.add(jLabel10);
      jLabel10.setBounds(10, 80, 11, 16);

      jComboBox12.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "wrap_obj23" }));
      WrapPanel.add(jComboBox12);
      jComboBox12.setBounds(34, 80, 110, 24);

      jComboBox13.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "hybrid", "Item 1", "Item 2", "Item 3", "Item 4" }));
      WrapPanel.add(jComboBox13);
      jComboBox13.setBounds(150, 80, 63, 24);

      jComboBox14.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "Item 1", "Item 2", "Item 3", "Item 4" }));
      WrapPanel.add(jComboBox14);
      jComboBox14.setBounds(220, 80, 40, 24);

      jComboBox15.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "end", "Item 1", "Item 2", "Item 3", "Item 4" }));
      WrapPanel.add(jComboBox15);
      jComboBox15.setBounds(270, 80, 50, 24);

      WrappingTab.setViewportView(WrapPanel);

      ParametersTabbedPanel.addTab("wrapping", WrappingTab);

      org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
         .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
               .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                  .addContainerGap()
                  .add(ParametersTabbedPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE))
               .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                  .addContainerGap()
                  .add(ResetButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 290, Short.MAX_VALUE)
                  .add(ApplyButton))
               .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                  .add(14, 14, 14)
                  .add(MuscleNameLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                  .add(MuscleNameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 185, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                  .add(MuscleTypeLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 47, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                  .add(MuscleTypeComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 126, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
         .add(layout.createSequentialGroup()
            .add(18, 18, 18)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
               .add(MuscleNameLabel)
               .add(MuscleNameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
               .add(MuscleTypeLabel)
               .add(MuscleTypeComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(19, 19, 19)
            .add(ParametersTabbedPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
               .add(ResetButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
               .add(ApplyButton))
            .addContainerGap())
      );
   }// </editor-fold>//GEN-END:initComponents
   
   
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton ApplyButton;
   private javax.swing.JLabel AttachmentBodyLabel;
   private javax.swing.JLabel AttachmentSelectedLabel;
   private javax.swing.JLabel AttachmentXLabel;
   private javax.swing.JLabel AttachmentYLabel;
   private javax.swing.JLabel AttachmentZLabel;
   private javax.swing.JPanel AttachmentsPanel;
   private javax.swing.JScrollPane AttachmentsTab;
   private javax.swing.JPanel DynamicPanel;
   private javax.swing.JScrollPane DynamicTab;
   private javax.swing.JPanel ForcePanel;
   private javax.swing.JScrollPane ForceTab;
   private javax.swing.JPanel FunctionsPanel;
   private javax.swing.JScrollPane FunctionsTab;
   private javax.swing.JLabel MuscleNameLabel;
   private javax.swing.JTextField MuscleNameTextField;
   private javax.swing.JComboBox MuscleTypeComboBox;
   private javax.swing.JLabel MuscleTypeLabel;
   private javax.swing.JTabbedPane ParametersTabbedPanel;
   private javax.swing.JButton ResetButton;
   private javax.swing.JLabel WrapMethodLabel;
   private javax.swing.JLabel WrapObjectLabel;
   private javax.swing.JPanel WrapPanel;
   private javax.swing.JLabel WrapRangeEndLabel;
   private javax.swing.JLabel WrapRangeStartLabel;
   private javax.swing.JScrollPane WrappingTab;
   private javax.swing.JComboBox jComboBox12;
   private javax.swing.JComboBox jComboBox13;
   private javax.swing.JComboBox jComboBox14;
   private javax.swing.JComboBox jComboBox15;
   private javax.swing.JLabel jLabel10;
   // End of variables declaration//GEN-END:variables
   
   /**
    * Gets default instance. Do not use directly: reserved for *.settings files only,
    * i.e. deserialization routines; otherwise you could get a non-deserialized instance.
    * To obtain the singleton instance, use {@link findInstance}.
    */
   public static synchronized MuscleEditorTopComponent getDefault() {
      if (instance == null) {
         instance = new MuscleEditorTopComponent();
      }
      return instance;
   }
   
   /**
    * Obtain the MuscleEditorTopComponent instance. Never call {@link #getDefault} directly!
    */
   public static synchronized MuscleEditorTopComponent findInstance() {
      TopComponent win = WindowManager.getDefault().findTopComponent(PREFERRED_ID);
      if (win == null) {
         ErrorManager.getDefault().log(ErrorManager.WARNING, "Cannot find MuscleEditor component. It will not be located properly in the window system.");
         return getDefault();
      }
      if (win instanceof MuscleEditorTopComponent) {
         return (MuscleEditorTopComponent)win;
      }
      ErrorManager.getDefault().log(ErrorManager.WARNING, "There seem to be multiple components with the '" + PREFERRED_ID + "' ID. That is a potential source of errors and unexpected behavior.");
      return getDefault();
   }
   
   public int getPersistenceType() {
      return TopComponent.PERSISTENCE_ALWAYS;
   }
   
   public void componentOpened() {
      Node[] selected = ExplorerTopComponent.findInstance().getExplorerManager().getSelectedNodes();
      // Action shouldn't be available otherwise'
      OneMuscleNode muscleNode = (OneMuscleNode) selected[0];
      act = (AbstractActuator)muscleNode.getOpensimObject();
      MuscleNameTextField.setText(act.getName());
      //PropertiesPanel.setBounds(80, 80, 400, 600);
      PropertySet ps = act.getPropertySet();
      int i, j;
      AbstractSimmMuscle asm = AbstractSimmMuscle.safeDownCast(act);
      if (true) {
         int dCount = 0, fCount = 0, iCount = 0;
         for (i = 0; i < ps.getSize(); i++) {
            Property p;
            try {
               p = ps.get(i);
               // for testing, add doubles to Force panel and Dynamic panel
               if (p.getType() == org.opensim.modeling.Property.PropertyType.Dbl) {
                  javax.swing.JLabel propLabel = new javax.swing.JLabel();
                  propLabel.setText(p.getName());
                  propLabel.setHorizontalAlignment(SwingConstants.RIGHT);
                  propLabel.setBounds(20, 22 + dCount * 22, 180, 16);
                  propLabel.setToolTipText(p.getComment());
                  javax.swing.JTextField propField = new javax.swing.JTextField();
                  propField.setBounds(210, 20 + dCount * 22, 120, 21);
                  propField.setText(p.toString());
                  propField.setToolTipText(p.getComment());
                  DynamicPanel.add(propLabel);
                  DynamicPanel.add(propField);
                  ////////////////////////////
                  javax.swing.JLabel propLabel2 = new javax.swing.JLabel();
                  propLabel2.setText(p.getName());
                  propLabel2.setHorizontalAlignment(SwingConstants.RIGHT);
                  propLabel2.setBounds(20, 22 + dCount * 22, 180, 16);
                  propLabel2.setToolTipText(p.getComment());
                  javax.swing.JTextField propField2 = new javax.swing.JTextField();
                  propField2.setBounds(210, 20 + dCount * 22, 120, 21);
                  propField2.setText(p.toString());
                  propField2.setToolTipText(p.getComment());
                  ForcePanel.add(propLabel2);
                  ForcePanel.add(propField2);
                  ////////////////////////////
                  dCount++;
               } else if (p.getType() == org.opensim.modeling.Property.PropertyType.Int) {
                  // for testing...
                  javax.swing.JLabel propLabel = new javax.swing.JLabel();
                  propLabel.setText(p.getName());
                  propLabel.setHorizontalAlignment(SwingConstants.RIGHT);
                  propLabel.setBounds(20, 22 + iCount * 22, 180, 16);
                  propLabel.setToolTipText(p.getComment());
                  javax.swing.JTextField propField = new javax.swing.JTextField();
                  propField.setBounds(210, 20 + iCount * 22, 120, 21);
                  propField.setText(p.toString());
                  propField.setToolTipText(p.getComment());
                  //ForcePanel.add(propLabel);
                  //ForcePanel.add(propField);
                  iCount++;
               } else if (p.getType() == org.opensim.modeling.Property.PropertyType.ObjPtr) {
                  OpenSimObject obj = p.getValueObjPtr();
                  Function func = Function.safeDownCast(obj);
                  if (func != null) {
                     javax.swing.JLabel propLabel = new javax.swing.JLabel();
                     propLabel.setText(p.getName());
                     propLabel.setHorizontalAlignment(SwingConstants.RIGHT);
                     propLabel.setBounds(20, 22 + fCount * 22, 200, 16);
                     propLabel.setToolTipText(p.getComment());
                     javax.swing.JButton propButton = new javax.swing.JButton();
                     propButton.setBounds(230, 20 + fCount * 22, 60, 21);
                     propButton.setText("edit");
                     FunctionsPanel.add(propLabel);
                     FunctionsPanel.add(propButton);
                     fCount++;
                  }
               }
            } catch (IOException ex) {
               ex.printStackTrace();
            }
         }

         // Put the attachment points in the attachments tab
         SetSimmMusclePoint ssmp = asm.getAttachmentSet();
         int X = 30;
         int Y = 40;
         BodySet bodies = asm.getModel().getDynamicsEngine().getBodySet();
         String[] bodyNames = new String[bodies.getSize()];
         for (i = 0; i < bodies.getSize(); i++)
            bodyNames[i] = new String(bodies.get(i).getName());
         for (i = 0; i < ssmp.getSize(); i++) {
            javax.swing.JLabel indexLabel = new javax.swing.JLabel();
            javax.swing.JTextField xField = new javax.swing.JTextField();
            javax.swing.JTextField yField = new javax.swing.JTextField();
            javax.swing.JTextField zField = new javax.swing.JTextField();
            javax.swing.JComboBox comboBox = new javax.swing.JComboBox();
            javax.swing.JCheckBox selectBox = new javax.swing.JCheckBox();
            indexLabel.setText(String.valueOf(i+1));
            comboBox.setModel(new javax.swing.DefaultComboBoxModel(bodyNames));
            SimmMusclePoint smp = ssmp.get(i);
            String foo = smp.getBodyName();
            int bar = findElement(bodyNames, ssmp.get(i).getBodyName());
            comboBox.setSelectedIndex(findElement(bodyNames, ssmp.get(i).getBodyName()));
            comboBox.setEnabled(true);
            int height = Y + i * 22;
            int width = 60;
            indexLabel.setBounds(X - 20, height, 20, 21);
            xField.setBounds(X, height, width, 21);
            yField.setBounds(X + width + 1, height, width, 21);
            zField.setBounds(X + 2*width + 2, height, width, 21);
            comboBox.setBounds(X + 3*width + 10, height, 90, 21);
            selectBox.setBounds(X + 3*width + 110, height, 21, 21);
            xField.setText(String.valueOf(ssmp.get(i).getAttachment().getitem(0)));
            yField.setText(String.valueOf(ssmp.get(i).getAttachment().getitem(1)));
            zField.setText(String.valueOf(ssmp.get(i).getAttachment().getitem(2)));
            AttachmentsPanel.add(indexLabel);
            AttachmentsPanel.add(xField);
            AttachmentsPanel.add(yField);
            AttachmentsPanel.add(zField);
            AttachmentsPanel.add(comboBox);
            AttachmentsPanel.add(selectBox);
         }

         AttachmentsPref.width = 350;
         AttachmentsPref.height = Y + ssmp.getSize() * 22;
         AttachmentsPanel.setPreferredSize(AttachmentsPref);
         AttachmentsPanel.revalidate();

         ForcePref.width = 350;
         ForcePref.height = 30 + dCount * 22;
         ForcePanel.setPreferredSize(ForcePref);
         ForcePanel.revalidate();

         DynamicPref.width = 350;
         DynamicPref.height = 30 + dCount * 22;
         DynamicPanel.setPreferredSize(DynamicPref);
         DynamicPanel.revalidate();

         FunctionsPref.width = 350;
         FunctionsPref.height = 30 + fCount * 22;
         FunctionsPanel.setPreferredSize(FunctionsPref);
         FunctionsPanel.revalidate();

         WrapPref.width = 350;
         WrapPref.height = 30 + dCount * 22;
         WrapPanel.setPreferredSize(WrapPref);
         WrapPanel.revalidate();
      }
      
      this.revalidate();
      this.repaint();
   }
   
   public void componentClosed() {
      // TODO add custom code on component closing
   }
   
   /** replaces this in object stream */
   public Object writeReplace() {
      return new ResolvableHelper();
   }
   
   protected String preferredID() {
      return PREFERRED_ID;
   }

   private int findElement(String[] bodyNames, String name) {
      int i;
      for (i = 0; i < bodyNames.length; i++)
         if (bodyNames[i].equals(name))
            return i;
      return -1;
   }
   
   final static class ResolvableHelper implements Serializable {
      private static final long serialVersionUID = 1L;
      public Object readResolve() {
         return MuscleEditorTopComponent.getDefault();
      }
   }
   
}
