OpenSim: ControlLinear Class Reference
ControlLinear Class Reference
#include <ControlLinear.h>
Public Member Functions
ControlLinear ()
ControlLinear (const ControlLinear &aControl)
virtual ~ControlLinear ()
virtual Object * copy () const
void copyData (const ControlLinear &aControl)
ControlLinear & operator= (const ControlLinear &aControl)
void setUseSteps (bool aTrueFalse)
bool getUseSteps () const
void setKp (double aKp)
double getKp () const
void setKv (double aKv)
double getKv () const
virtual int getNumParameters () const
virtual void setParameterMin (int aI, double aMin)
virtual double getParameterMin (int aI) const
virtual void setParameterMax (int aI, double aMax)
virtual double getParameterMax (int aI) const
virtual double getParameterTime (int aI) const
virtual void getParameterNeighborhood (int aI, double &rTLower, double &rTUpper) const
virtual int getParameterList (double aT, Array< int > &rList)
virtual int getParameterList (double aT1, double aT2, Array< int > &rList)
virtual void setParameterValue (int aI, double aP)
virtual double getParameterValue (int aI) const
virtual void setControlValue (double aT, double aX)
virtual double getControlValue (double aT)
virtual double getControlValueMin (double aT=0.0)
virtual void setControlValueMin (double aT, double aX)
virtual double getControlValueMax (double aT=0.0)
virtual void setControlValueMax (double aT, double aX)
void clearControlNodes ()
ArrayPtrs< ControlLinearNode > & getControlValues ()
ArrayPtrs< ControlLinearNode > & getControlMinValues ()
ArrayPtrs< ControlLinearNode > & getControlMaxValues ()
void insertNewValueNode (int index, const ControlLinearNode &newNode)
void insertNewMinNode (int index, const ControlLinearNode &newNode)
void insertNewMaxNode (int index, const ControlLinearNode &newNode)
virtual const double getFirstTime () const
virtual const double getLastTime () const
virtual void simplify (const PropertySet &aProperties)
bool simplify (const double &cutoffFrequency, const double &distance)
virtual void filter (double aT)
Protected Member Functions
virtual void setupProperties ()
Protected Attributes
PropertyBool _propUseSteps
Flag that indicates whether or not to linearly interpolate between nodes or use step functions.
PropertyObjArray
< ControlLinearNode > _propXNodes
Array of control nodes.
PropertyObjArray
< ControlLinearNode > _propMinNodes
PropertyObjArray
< ControlLinearNode > _propMaxNodes
PropertyDbl _propKp
Position gain for PD follower filter.
PropertyDbl _propKv
Velocity gain for PD follower filter.
bool & _useSteps
ArrayPtrs< ControlLinearNode > & _xNodes
ArrayPtrs< ControlLinearNode > & _minNodes
ArrayPtrs< ControlLinearNode > & _maxNodes
double & _kp
double & _kv
ControlLinearNode _searchNode
Utility node for speeding up searches for control values in getControlValue() and elsewhere.
Constructor & Destructor Documentation
ControlLinear ()
ControlLinear (const ControlLinear & aControl)
virtual ~ControlLinear () [virtual]
Member Function Documentation
virtual Object* copy () const [virtual]
Reimplemented from Object.
void copyData (const ControlLinear & aControl)
virtual void setupProperties () [protected, virtual]
Reimplemented from Control.
ControlLinear& operator= (const ControlLinear & aControl)
void setUseSteps (bool aTrueFalse)
bool getUseSteps () const
void setKp (double aKp)
double getKp () const
void setKv (double aKv)
double getKv () const
virtual int getNumParameters () const [virtual]
Implements Control.
virtual void setParameterMin (int aI, double aMin) [virtual]
Implements Control.
virtual double getParameterMin (int aI) const [virtual]
Implements Control.
virtual void setParameterMax (int aI, double aMax) [virtual]
Implements Control.
virtual double getParameterMax (int aI) const [virtual]
Implements Control.
virtual double getParameterTime (int aI) const [virtual]
Implements Control.
virtual void getParameterNeighborhood (int aI, double & rTLower, double & rTUpper) const [virtual]
Implements Control.
virtual int getParameterList (double aT, Array< int > & rList) [virtual]
Implements Control.
virtual int getParameterList (double aT1, double aT2, Array< int > & rList) [virtual]
Implements Control.
virtual void setParameterValue (int aI, double aP) [virtual]
Implements Control.
virtual double getParameterValue (int aI) const [virtual]
Implements Control.
virtual void setControlValue (double aT, double aX) [virtual]
Implements Control.
virtual double getControlValue (double aT) [virtual]
Implements Control.
virtual double getControlValueMin (double aT = 0.0) [virtual]
Implements Control.
virtual void setControlValueMin (double aT, double aX) [virtual]
Implements Control.
virtual double getControlValueMax (double aT = 0.0) [virtual]
Implements Control.
virtual void setControlValueMax (double aT, double aX) [virtual]
Implements Control.
void clearControlNodes ()
ArrayPtrs<ControlLinearNode>& getControlValues () [inline]
ArrayPtrs<ControlLinearNode>& getControlMinValues () [inline]
ArrayPtrs<ControlLinearNode>& getControlMaxValues () [inline]
void insertNewValueNode (int index, const ControlLinearNode & newNode) [inline]
References ControlLinearNode::copy().
void insertNewMinNode (int index, const ControlLinearNode & newNode) [inline]
References ControlLinearNode::copy().
void insertNewMaxNode (int index, const ControlLinearNode & newNode) [inline]
References ControlLinearNode::copy().
virtual const double getFirstTime () const [virtual]
Reimplemented from Control.
virtual const double getLastTime () const [virtual]
Reimplemented from Control.
virtual void simplify (const PropertySet & aProperties) [virtual]
Reimplemented from Control.
bool simplify (const double & cutoffFrequency, const double & distance)
virtual void filter (double aT) [virtual]
Reimplemented from Control.
Member Data Documentation
PropertyBool _propUseSteps [protected]
Flag that indicates whether or not to linearly interpolate between nodes or use step functions.
PropertyObjArray<ControlLinearNode> _propXNodes [protected]
Array of control nodes.
PropertyObjArray<ControlLinearNode> _propMinNodes [protected]
PropertyObjArray<ControlLinearNode> _propMaxNodes [protected]
PropertyDbl _propKp [protected]
Position gain for PD follower filter.
PropertyDbl _propKv [protected]
Velocity gain for PD follower filter.
bool& _useSteps [protected]
ArrayPtrs<ControlLinearNode>& _xNodes [protected]
ArrayPtrs<ControlLinearNode>& _minNodes [protected]
ArrayPtrs<ControlLinearNode>& _maxNodes [protected]
double& _kp [protected]
double& _kv [protected]
ControlLinearNode _searchNode [protected]
Utility node for speeding up searches for control values in getControlValue() and elsewhere.
Without this node, a control node would need to be contructed, but this is too expensive. It is better to contruct a node up front, and then just alter the time.
The documentation for this class was generated from the following file:
ControlLinear.h