OpenSim: ControlLinearNode Class Reference
ControlLinearNode Class Reference
#include <ControlLinearNode.h>
Public Member Functions
ControlLinearNode (double aT=0.0, double aValue=0.0)
ControlLinearNode (const ControlLinearNode &aNode)
virtual Object * copy () const
virtual ~ControlLinearNode ()
ControlLinearNode & operator= (const ControlLinearNode &aControl)
bool operator== (const ControlLinearNode &aControl) const
bool operator< (const ControlLinearNode &aControl) const
void setTime (double aT)
double getTime () const
void setValue (double aValue)
double getValue () const
char * toString ()
Protected Attributes
PropertyDbl _propT
Equality tolerance.
PropertyDbl _propValue
Value of the node (may represent control value or min or max bounds, depending on which curve it's in).
double & _t
Reference to the value of the T property.
double & _value
Reference to the value of the X property.
Friends
std::ostream & operator<< (std::ostream &aOut, const ControlLinearNode &aControlLinearNode)
Constructor & Destructor Documentation
ControlLinearNode (double aT = 0.0, double aValue = 0.0)
ControlLinearNode (const ControlLinearNode & aNode)
virtual ~ControlLinearNode () [virtual]
Member Function Documentation
virtual Object* copy () const [virtual]
Reimplemented from Object.
Referenced by ControlLinear::insertNewMaxNode(), ControlLinear::insertNewMinNode(), and ControlLinear::insertNewValueNode().
ControlLinearNode& operator= (const ControlLinearNode & aControl)
bool operator== (const ControlLinearNode & aControl) const
bool operator< (const ControlLinearNode & aControl) const
void setTime (double aT)
double getTime () const
void setValue (double aValue)
double getValue () const
char* toString ()
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & aOut, const ControlLinearNode & aControlLinearNode) [friend]
Member Data Documentation
PropertyDbl _propT [protected]
Equality tolerance.
Time at which the node occurs.
PropertyDbl _propValue [protected]
Value of the node (may represent control value or min or max bounds, depending on which curve it's in).
double& _t [protected]
Reference to the value of the T property.
double& _value [protected]
Reference to the value of the X property.
The documentation for this class was generated from the following file:
ControlLinearNode.h