OpenSim: Object Class Reference
Object Class Reference
#include <Object.h>
Public Types
enum { NAME_LENGTH = 128 }
A length limit for a name.
Public Member Functions
virtual ~Object ()
Object ()
Object (const std::string &aFileName, bool aUpdateFromXMLNode=true) SWIG_DECLARE_EXCEPTION
Object (const XMLDocument *aDocument)
Object (DOMElement *aNode)
Object (const Object &aObject)
virtual Object * copy () const
virtual Object * copy (DOMElement *aNode) const
virtual void migrateFromPreviousVersion (const Object *aObject)
virtual VisibleObject * getDisplayer () const
Object & operator= (const Object &aObject)
virtual bool operator== (const Object &aObject) const
virtual bool operator< (const Object &aObject) const
void setType (const std::string &aType)
const std::string & getType () const
virtual const std::string & getNewType () const
void setName (const std::string &aName)
const std::string & getName () const
void setDescription (const std::string &aDescrip)
const std::string & getDescription () const
const std::string & toString () const
PropertySet & getPropertySet ()
const PropertySet & getPropertySet () const
virtual bool isValidDefaultType (const Object *aObject) const
virtual void updateFromXMLNode ()
virtual void updateDefaultObjectsFromXMLNode ()
virtual void updateXMLNode (DOMElement *aParent, int aNodeIndex=0)
virtual void updateDefaultObjectsXMLNode (DOMElement *aParent)
virtual void generateXMLNode (DOMElement *aParent, int aNodeIndex=0)
bool getInlined () const
void setInlined (bool aInlined, const std::string &aFileName="")
XMLDocument * getDocument () const
std::string getDocumentFileName () const
DOMElement * getXMLNode () const
void clearXMLStructures ()
void setAllPropertiesUseDefault (bool aUseDefault)
bool print (const std::string &aFileName)
void addObserver (Object &aObserver)
void deleteObserver (Object &aObserver)
void addObserverEvent (Object &aObserver, Event &aEvent)
Eventually observers will have to specify what event to observe so that they're not called unnecessarily.
void notifyObservers (Event &aEvent)
void deleteObservers ()
int countObservers () const
virtual void update (const Object &aObject, Event &aEvent)
virtual bool isA (const char *type) const
Static Public Member Functions
static Object * SafeCopy (const Object *aObject)
static void RegisterType (const Object &aObject)
static Object * makeObjectFromFile (const std::string &aFileName)
static Object * newInstanceOfType (const std::string &aType)
static void getRegisteredTypenames (Array< std::string > &rTypeNames)
static void PrintPropertyInfo (std::ostream &aOStream, const std::string &aClassNameDotPropertyName)
static void PrintPropertyInfo (std::ostream &aOStream, const std::string &aClassName, const std::string &aPropertyName)
static void setSerializeAllDefaults (bool aBoolean)
static bool getSerializeAllDefaults ()
static bool isKindOf (const char *type)
template<class T>
static void getRegisteredObjectsOfGivenType (ArrayPtrs< T > &rArray)
Static Public Attributes
static const std::string DEFAULT_NAME
Name used for default objects when they are serialized.
Protected Member Functions
void setXMLNode (DOMElement *aNode)
void setChanged ()
void clearChanged ()
bool hasChanged ()
Protected Attributes
PropertySet _propertySet
Property set for serializable member variables of this and derived classes.
std::string _type
Type.
std::string _name
Name.
std::string _description
A description of the object.
XMLDocument * _document
XML document.
DOMElement * _node
XML element node.
bool _inlined
Inlined object -> rdSerializable interface.
DOMElement * _refNode
For non inlined objects their _node and _document refer to external file _refNode contains the type and reference to file name -> rdSerializable interface.
bool _converting
Friends
std::ostream & operator<< (std::ostream &aOut, const Object &aObject)
Member Enumeration Documentation
anonymous enum
A length limit for a name.
Enumerator:
NAME_LENGTH
Constructor & Destructor Documentation
virtual ~Object () [virtual]
Object ()
Object (const std::string & aFileName, bool aUpdateFromXMLNode = true)
Object (const XMLDocument * aDocument)
Object (DOMElement * aNode)
Object (const Object & aObject)
Member Function Documentation
virtual Object* copy () const [virtual]
Reimplemented in GeneralizedForceAtv, JointMoment, LinearSetPoint, PassiveJointTorque, PolynomialSetPoint, Schutte1993Muscle, SpringGeneralizedForce, Thelen2003Muscle, Torque, Actuation, ActuatorGeneralizedForces, BodyKinematics, GeneralizedForces, InverseDynamics, JointReaction, Kinematics, MuscleAnalysis, PointKinematics, StaticOptimization, Constant, Function, GCVSpline, LinearFunction, Material, MaterialManager, NatCubicSpline, ObjectGroup, Range, Scale, Set, SimmMotionData, SimmMotionEvent, SimmPoint, StepFunction, Storage, VectorFunction, VectorFunctionUncoupledNxN, VectorGCVSplineR1R3, VisibleObject, VisibleProperties, Body, Constraint, Coordinate, CoordinateCouplerConstraint, CustomJoint, SimbodyBody01_05, SimbodyCoordinate01_05, SimbodyEngine, SimbodyEngine01_05, SimbodyJoint01_05, SimbodyRotationDof01_05, SimbodySpeed01_05, SimbodyTranslationDof01_05, Speed, TransformAxis, WeldConstraint, ControlConstant, ControlLinear, ControlLinearNode, ControlObject, ControlSet, AbstractActuator, AbstractBody, AbstractConstraint, AbstractCoordinate, AbstractDof01_05, AbstractDynamicsEngine, AbstractDynamicsEngine01_05, AbstractJoint, AbstractMarker, AbstractMuscle, AbstractSpeed, AbstractTransformAxis, ActuatorSet, Analysis, AnalysisSet, BodyScale, Callback, ContactForceSet, Force, GeneralizedForce, IntegCallback, InterruptingIntegCallback, Marker, MarkerSet, Model, MovingMusclePoint, MusclePoint, MuscleViaPoint, VectorFunctionForActuators, AbstractWrapObject, MuscleWrap, MuscleWrapPoint, WrapCylinder, WrapEllipsoid, WrapSphere, WrapTorus, AnalyzeTool, CMCTool, ForwardTool, GenericModelMaker, IKCoordinateTask, IKMarkerTask, IKTask, IKTool, IKTrial, MarkerPair, MarkerPlacer, Measurement, ModelScaler, PerturbationTool, rdCMC_Joint, rdCMC_Point, rdCMC_Task, ScaleTool, SMC_Joint, Set< OpenSim::MarkerPair >, Set< OpenSim::IKTask >, Set< OpenSim::Measurement >, Set< OpenSim::AbstractCoordinate >, Set< OpenSim::AbstractDof01_05 >, Set< OpenSim::AbstractConstraint >, Set< OpenSim::AbstractTransformAxis >, Set< OpenSim::VisibleObject >, Set< OpenSim::Analysis >, Set< OpenSim::AbstractWrapObject >, Set< OpenSim::Callback >, Set< OpenSim::AbstractBody >, Set< OpenSim::rdCMC_Task >, Set< OpenSim::AbstractJoint >, Set< OpenSim::AbstractActuator >, Set< OpenSim::Material >, Set< OpenSim::IKTrial >, Set< OpenSim::AbstractMarker >, Set< OpenSim::Scale >, Set< OpenSim::MuscleWrap >, Set< OpenSim::Function >, Set< OpenSim::AbstractSpeed >, Set< OpenSim::MusclePoint >, Set< OpenSim::Control >, and Set< OpenSim::BodyScale >.
Referenced by Object::SafeCopy().
virtual Object* copy (DOMElement * aNode) const [virtual]
virtual void migrateFromPreviousVersion (const Object * aObject) [inline, virtual]
Reimplemented in SimbodyEngine.
static Object* SafeCopy (const Object * aObject) [inline, static]
References Object::copy().
virtual VisibleObject* getDisplayer () const [inline, virtual]
Reimplemented in Body, SimbodyBody01_05, AbstractActuator, AbstractBody, AbstractMarker, AbstractMuscle, Marker, MusclePoint, and AbstractWrapObject.
Object& operator= (const Object & aObject)
Referenced by Set< OpenSim::BodyScale >::operator=().
virtual bool operator== (const Object & aObject) const [virtual]
virtual bool operator< (const Object & aObject) const [virtual]
void setType (const std::string & aType)
Referenced by Set< OpenSim::BodyScale >::Set().
const std::string& getType () const
Referenced by PropertyObjArray< OpenSim::BodyScale >::appendValue().
virtual const std::string& getNewType () const [inline, virtual]
Reimplemented in SimbodyBody01_05, SimbodyJoint01_05, SimbodyRotationDof01_05, SimbodyTranslationDof01_05, and DofSet01_05.
void setName (const std::string & aName)
Reimplemented in AbstractMuscle.
Referenced by Set< OpenSim::BodyScale >::renameGroup().
const std::string& getName () const
void setDescription (const std::string & aDescrip)
const std::string& getDescription () const
const std::string& toString () const
PropertySet& getPropertySet () [inline]
const PropertySet& getPropertySet () const [inline]
static void RegisterType (const Object & aObject) [static]
static Object* makeObjectFromFile (const std::string & aFileName) [static]
static Object* newInstanceOfType (const std::string & aType) [static]
static void getRegisteredTypenames (Array< std::string > & rTypeNames) [static]
virtual bool isValidDefaultType (const Object * aObject) const [virtual]
virtual void updateFromXMLNode () [virtual]
Reimplemented in GeneralizedForceAtv, JointMoment, LinearSetPoint, PolynomialSetPoint, SetPoint, LinearFunction, NatCubicSpline, StepFunction, SimbodyTranslationDof01_05, ContactForce, GeneralizedForce, rdCMC_Joint, rdCMC_Point, and rdCMC_Task.
Referenced by Set< OpenSim::BodyScale >::Set().
virtual void updateDefaultObjectsFromXMLNode () [virtual]
virtual void updateXMLNode (DOMElement * aParent, int aNodeIndex = 0) [virtual]
virtual void updateDefaultObjectsXMLNode (DOMElement * aParent) [virtual]
virtual void generateXMLNode (DOMElement * aParent, int aNodeIndex = 0) [virtual]
bool getInlined () const
void setInlined (bool aInlined, const std::string & aFileName = "")
XMLDocument* getDocument () const
std::string getDocumentFileName () const
DOMElement* getXMLNode () const
void clearXMLStructures ()
void setAllPropertiesUseDefault (bool aUseDefault)
void setXMLNode (DOMElement * aNode) [protected]
bool print (const std::string & aFileName)
static void PrintPropertyInfo (std::ostream & aOStream, const std::string & aClassNameDotPropertyName) [static]
static void PrintPropertyInfo (std::ostream & aOStream, const std::string & aClassName, const std::string & aPropertyName) [static]
void addObserver (Object & aObserver) [inline]
void deleteObserver (Object & aObserver) [inline]
void addObserverEvent (Object & aObserver, Event & aEvent) [inline]
Eventually observers will have to specify what event to observe so that they're not called unnecessarily.
Will do this after the Event class hierarchy matures.
void notifyObservers (Event & aEvent) [inline]
void deleteObservers () [inline]
int countObservers () const [inline]
void setChanged () [inline, protected]
void clearChanged () [inline, protected]
bool hasChanged () [inline, protected]
virtual void update (const Object & aObject, Event & aEvent) [inline, virtual]
static void setSerializeAllDefaults (bool aBoolean) [inline, static]
static bool getSerializeAllDefaults () [inline, static]
static bool isKindOf (const char * type) [inline, static]
virtual bool isA (const char * type) const [inline, virtual]
static void getRegisteredObjectsOfGivenType (ArrayPtrs< T > & rArray) [inline, static]
References ArrayPtrs::append(), ArrayPtrs::setMemoryOwner(), and ArrayPtrs::setSize().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & aOut, const Object & aObject) [friend]
Member Data Documentation
const std::string DEFAULT_NAME [static]
Name used for default objects when they are serialized.
Reimplemented in ControlObject.
PropertySet _propertySet [protected]
Property set for serializable member variables of this and derived classes.
std::string _type [protected]
Type.
std::string _name [protected]
Name.
Made protected so that classes can customize their setName. -Ayman 04/04
std::string _description [protected]
A description of the object.
-> rdSerializable interface
XMLDocument* _document [protected]
XML document.
-> rdSerializable interface
DOMElement* _node [protected]
XML element node.
-> rdSerializable interface
bool _inlined [protected]
Inlined object -> rdSerializable interface.
DOMElement* _refNode [protected]
For non inlined objects their _node and _document refer to external file _refNode contains the type and reference to file name -> rdSerializable interface.
bool _converting [protected]
The documentation for this class was generated from the following file:
Object.h