OpenSim: AnalyticSphere Class Reference
AnalyticSphere Class Reference
#include <Geometry.h>
Public Member Functions
AnalyticSphere ()
AnalyticSphere (double radius)
virtual ~AnalyticSphere ()
const double & getRadius () const
void setSphereRadius (double radius)
Static Public Member Functions
static AnalyticGeometry * createSphere (double radius)
Protected Attributes
double _attributes [1]
Constructor & Destructor Documentation
AnalyticSphere () [inline]
AnalyticSphere (double radius) [inline]
virtual ~AnalyticSphere () [inline, virtual]
Member Function Documentation
const double& getRadius () const [inline]
void setSphereRadius (double radius) [inline]
Referenced by AnalyticSphere::createSphere().
static AnalyticGeometry* createSphere (double radius) [inline, static]
References AnalyticSphere::setSphereRadius().
Referenced by VisibleObject::getDefaultGeometry().
Member Data Documentation
double _attributes[1] [protected]
The documentation for this class was generated from the following file:
Geometry.h