OpenSim: Property Class Reference
Property Class Reference
#include <Property.h>
Public Types
enum PropertyType {
None = 0, Bool, Int, Dbl,
Str, Obj, ObjPtr, BoolArray,
IntArray, DblArray, StrArray, ObjArray,
DblVec3
}
Enumeration of recognized types.
Public Member Functions
Property ()
Property (PropertyType aType, const std::string &aName)
Property (const Property &aProperty)
virtual Property * copy () const =0
virtual ~Property ()
void setNull ()
Property & operator= (const Property &aProperty)
virtual bool operator== (const Property &aProperty) const
virtual bool operator< (const Property &aProperty) const
void setType (PropertyType aType)
PropertyType getType () const
virtual const char * getTypeAsString () const
void setName (const std::string &aName)
const std::string & getName () const
void setComment (const std::string &aComment)
const std::string & getComment () const
virtual const std::string & toString ()=0
void setAllowableArraySize (int aMin, int aMax)
void setAllowableArraySize (int aNum)
int getMinArraySize ()
int getMaxArraySize ()
virtual void setValue (bool aValue)
virtual bool & getValueBool ()
virtual const bool & getValueBool () const
virtual void setValue (int aValue)
virtual int & getValueInt ()
virtual const int & getValueInt () const
virtual void setValue (double aValue)
virtual double & getValueDbl ()
virtual const double & getValueDbl () const
virtual void setValue (const std::string &aValue)
virtual std::string & getValueStr ()
virtual const std::string & getValueStr () const
virtual void setValue (int aSize, const bool aArray[])
virtual void setValue (const Array< bool > &aArray)
virtual Array< bool > & getValueBoolArray ()
virtual const Array< bool > & getValueBoolArray () const
virtual void setValue (int aSize, const int aArray[])
virtual void setValue (const Array< int > &aArray)
virtual Array< int > & getValueIntArray ()
virtual const Array< int > & getValueIntArray () const
virtual void setValue (int aSize, const double aArray[])
virtual void setValue (const Array< double > &aArray)
virtual Array< double > & getValueDblArray ()
virtual const Array< double > & getValueDblArray () const
virtual void setValue (int aSize, const std::string aArray[])
virtual void setValue (const Array< std::string > &aArray)
virtual Array< std::string > & getValueStrArray ()
virtual const Array
< std::string > & getValueStrArray () const
virtual bool isValidObject (const Object *aValue) const
virtual Object & getValueObj ()
virtual const Object & getValueObj () const
virtual void setValue (Object *aValue)
virtual Object * getValueObjPtr ()
virtual Object * getValueObjPtr (int index)
virtual void appendValue (Object *obj)
virtual void clearObjArray ()
void setUseDefault (bool aTrueFalse)
bool getUseDefault () const
virtual int getArraySize () const
template<class T>
T & getValue ()
template<class T>
const T & getValue () const
template<class T>
Array< T > & getValueArray ()
template<class T>
const Array< T > & getValueArray () const
Protected Attributes
std::string _comment
Comment to be associated with property, shown for default objects only for efficiency.
std::string _valueString
String representation of property.
Friends
std::ostream & operator<< (std::ostream &aOut, const Property &aProperty)
Member Enumeration Documentation
enum PropertyType
Enumeration of recognized types.
Enumerator:
None
Bool
Int
Dbl
Str
Obj
ObjPtr
BoolArray
IntArray
DblArray
StrArray
ObjArray
DblVec3
Constructor & Destructor Documentation
Property ()
Property (PropertyType aType, const std::string & aName)
Property (const Property & aProperty)
virtual ~Property () [inline, virtual]
Member Function Documentation
virtual Property* copy () const [pure virtual]
Implemented in PropertyBool, PropertyBoolArray, PropertyDbl, PropertyDblArray, PropertyDblVec3, PropertyInt, PropertyIntArray, PropertyObj, PropertyObjArray, PropertyObjPtr, PropertyStr, PropertyStrArray, PropertyObjArray< OpenSim::MarkerPair >, PropertyObjArray< OpenSim::IKTask >, PropertyObjArray< OpenSim::Measurement >, PropertyObjArray< OpenSim::AbstractCoordinate >, PropertyObjArray< OpenSim::ObjectGroup >, PropertyObjArray< OpenSim::AbstractDof01_05 >, PropertyObjArray< OpenSim::AbstractConstraint >, PropertyObjArray< OpenSim::AbstractTransformAxis >, PropertyObjArray< OpenSim::VisibleObject >, PropertyObjArray< OpenSim::Analysis >, PropertyObjArray< OpenSim::AbstractWrapObject >, PropertyObjArray< OpenSim::Callback >, PropertyObjArray< OpenSim::AbstractBody >, PropertyObjArray< OpenSim::rdCMC_Task >, PropertyObjArray< OpenSim::AbstractJoint >, PropertyObjArray< OpenSim::AbstractActuator >, PropertyObjArray< OpenSim::Material >, PropertyObjArray< OpenSim::IKTrial >, PropertyObjArray< OpenSim::AbstractMarker >, PropertyObjArray< OpenSim::Scale >, PropertyObjArray< OpenSim::ControlLinearNode >, PropertyObjArray< OpenSim::MuscleWrap >, PropertyObjArray< OpenSim::Function >, PropertyObjArray< OpenSim::AbstractSpeed >, PropertyObjArray< OpenSim::MusclePoint >, PropertyObjArray< OpenSim::Control >, PropertyObjArray< OpenSim::BodyScale >, PropertyObjPtr< OpenSim::AbstractDynamicsEngine >, PropertyObjPtr< OpenSim::Joint >, PropertyObjPtr< OpenSim::Controller >, and PropertyObjPtr< OpenSim::Function >.
void setNull ()
Property& operator= (const Property & aProperty)
Referenced by PropertyObjPtr< OpenSim::Function >::operator=(), and PropertyObjArray< OpenSim::BodyScale >::operator=().
virtual bool operator== (const Property & aProperty) const [virtual]
virtual bool operator< (const Property & aProperty) const [virtual]
void setType (PropertyType aType)
PropertyType getType () const
virtual const char* getTypeAsString () const [virtual]
Reimplemented in PropertyBool, PropertyBoolArray, PropertyDbl, PropertyDblArray, PropertyDblVec3, PropertyInt, PropertyIntArray, PropertyObj, PropertyObjArray, PropertyObjPtr, PropertyStr, PropertyStrArray, PropertyObjArray< OpenSim::MarkerPair >, PropertyObjArray< OpenSim::IKTask >, PropertyObjArray< OpenSim::Measurement >, PropertyObjArray< OpenSim::AbstractCoordinate >, PropertyObjArray< OpenSim::ObjectGroup >, PropertyObjArray< OpenSim::AbstractDof01_05 >, PropertyObjArray< OpenSim::AbstractConstraint >, PropertyObjArray< OpenSim::AbstractTransformAxis >, PropertyObjArray< OpenSim::VisibleObject >, PropertyObjArray< OpenSim::Analysis >, PropertyObjArray< OpenSim::AbstractWrapObject >, PropertyObjArray< OpenSim::Callback >, PropertyObjArray< OpenSim::AbstractBody >, PropertyObjArray< OpenSim::rdCMC_Task >, PropertyObjArray< OpenSim::AbstractJoint >, PropertyObjArray< OpenSim::AbstractActuator >, PropertyObjArray< OpenSim::Material >, PropertyObjArray< OpenSim::IKTrial >, PropertyObjArray< OpenSim::AbstractMarker >, PropertyObjArray< OpenSim::Scale >, PropertyObjArray< OpenSim::ControlLinearNode >, PropertyObjArray< OpenSim::MuscleWrap >, PropertyObjArray< OpenSim::Function >, PropertyObjArray< OpenSim::AbstractSpeed >, PropertyObjArray< OpenSim::MusclePoint >, PropertyObjArray< OpenSim::Control >, PropertyObjArray< OpenSim::BodyScale >, PropertyObjPtr< OpenSim::AbstractDynamicsEngine >, PropertyObjPtr< OpenSim::Joint >, PropertyObjPtr< OpenSim::Controller >, and PropertyObjPtr< OpenSim::Function >.
void setName (const std::string & aName)
const std::string& getName () const
void setComment (const std::string & aComment) [inline]
const std::string& getComment () const [inline]
virtual const std::string& toString () [pure virtual]
Implemented in PropertyBool, PropertyBoolArray, PropertyDbl, PropertyDblArray, PropertyDblVec3, PropertyInt, PropertyIntArray, PropertyObj, PropertyObjArray, PropertyObjPtr, PropertyStr, PropertyStrArray, PropertyObjArray< OpenSim::MarkerPair >, PropertyObjArray< OpenSim::IKTask >, PropertyObjArray< OpenSim::Measurement >, PropertyObjArray< OpenSim::AbstractCoordinate >, PropertyObjArray< OpenSim::ObjectGroup >, PropertyObjArray< OpenSim::AbstractDof01_05 >, PropertyObjArray< OpenSim::AbstractConstraint >, PropertyObjArray< OpenSim::AbstractTransformAxis >, PropertyObjArray< OpenSim::VisibleObject >, PropertyObjArray< OpenSim::Analysis >, PropertyObjArray< OpenSim::AbstractWrapObject >, PropertyObjArray< OpenSim::Callback >, PropertyObjArray< OpenSim::AbstractBody >, PropertyObjArray< OpenSim::rdCMC_Task >, PropertyObjArray< OpenSim::AbstractJoint >, PropertyObjArray< OpenSim::AbstractActuator >, PropertyObjArray< OpenSim::Material >, PropertyObjArray< OpenSim::IKTrial >, PropertyObjArray< OpenSim::AbstractMarker >, PropertyObjArray< OpenSim::Scale >, PropertyObjArray< OpenSim::ControlLinearNode >, PropertyObjArray< OpenSim::MuscleWrap >, PropertyObjArray< OpenSim::Function >, PropertyObjArray< OpenSim::AbstractSpeed >, PropertyObjArray< OpenSim::MusclePoint >, PropertyObjArray< OpenSim::Control >, PropertyObjArray< OpenSim::BodyScale >, PropertyObjPtr< OpenSim::AbstractDynamicsEngine >, PropertyObjPtr< OpenSim::Joint >, PropertyObjPtr< OpenSim::Controller >, and PropertyObjPtr< OpenSim::Function >.
void setAllowableArraySize (int aMin, int aMax) [inline]
void setAllowableArraySize (int aNum) [inline]
int getMinArraySize () [inline]
int getMaxArraySize () [inline]
virtual void setValue (bool aValue) [inline, virtual]
Reimplemented in PropertyBool.
References Property_PROPERTY_TYPE_MISMATCH.
virtual bool& getValueBool () [inline, virtual]
Reimplemented in PropertyBool.
References Property_PROPERTY_TYPE_MISMATCH.
Referenced by Property::getValue().
virtual const bool& getValueBool () const [inline, virtual]
Reimplemented in PropertyBool.
References Property_PROPERTY_TYPE_MISMATCH.
virtual void setValue (int aValue) [inline, virtual]
Reimplemented in PropertyInt.
References Property_PROPERTY_TYPE_MISMATCH.
virtual int& getValueInt () [inline, virtual]
Reimplemented in PropertyInt.
References Property_PROPERTY_TYPE_MISMATCH.
virtual const int& getValueInt () const [inline, virtual]
Reimplemented in PropertyInt.
References Property_PROPERTY_TYPE_MISMATCH.
virtual void setValue (double aValue) [inline, virtual]
Reimplemented in PropertyDbl.
References Property_PROPERTY_TYPE_MISMATCH.
virtual double& getValueDbl () [inline, virtual]
Reimplemented in PropertyDbl.
References Property_PROPERTY_TYPE_MISMATCH.
virtual const double& getValueDbl () const [inline, virtual]
Reimplemented in PropertyDbl.
References Property_PROPERTY_TYPE_MISMATCH.
virtual void setValue (const std::string & aValue) [inline, virtual]
Reimplemented in PropertyStr.
References Property_PROPERTY_TYPE_MISMATCH.
virtual std::string& getValueStr () [inline, virtual]
Reimplemented in PropertyStr.
References Property_PROPERTY_TYPE_MISMATCH.
virtual const std::string& getValueStr () const [inline, virtual]
Reimplemented in PropertyStr.
References Property_PROPERTY_TYPE_MISMATCH.
virtual void setValue (int aSize, const bool aArray[]) [inline, virtual]
Reimplemented in PropertyBoolArray.
References Property_PROPERTY_TYPE_MISMATCH.
virtual void setValue (const Array< bool > & aArray) [inline, virtual]
Reimplemented in PropertyBoolArray.
References Property_PROPERTY_TYPE_MISMATCH.
virtual Array<bool>& getValueBoolArray () [inline, virtual]
Reimplemented in PropertyBoolArray.
References Property_PROPERTY_TYPE_MISMATCH.
Referenced by Property::getValueArray().
virtual const Array<bool>& getValueBoolArray () const [inline, virtual]
Reimplemented in PropertyBoolArray.
References Property_PROPERTY_TYPE_MISMATCH.
virtual void setValue (int aSize, const int aArray[]) [inline, virtual]
Reimplemented in PropertyIntArray.
References Property_PROPERTY_TYPE_MISMATCH.
virtual void setValue (const Array< int > & aArray) [inline, virtual]
Reimplemented in PropertyIntArray.
References Property_PROPERTY_TYPE_MISMATCH.
virtual Array<int>& getValueIntArray () [inline, virtual]
Reimplemented in PropertyIntArray.
References Property_PROPERTY_TYPE_MISMATCH.
virtual const Array<int>& getValueIntArray () const [inline, virtual]
Reimplemented in PropertyIntArray.
References Property_PROPERTY_TYPE_MISMATCH.
virtual void setValue (int aSize, const double aArray[]) [inline, virtual]
Reimplemented in PropertyDblArray, and PropertyDblVec3.
References Property_PROPERTY_TYPE_MISMATCH.
virtual void setValue (const Array< double > & aArray) [inline, virtual]
Reimplemented in PropertyDblArray.
References Property_PROPERTY_TYPE_MISMATCH.
virtual Array<double>& getValueDblArray () [inline, virtual]
Reimplemented in PropertyDblArray.
References Property_PROPERTY_TYPE_MISMATCH.
virtual const Array<double>& getValueDblArray () const [inline, virtual]
Reimplemented in PropertyDblArray.
References Property_PROPERTY_TYPE_MISMATCH.
virtual void setValue (int aSize, const std::string aArray[]) [inline, virtual]
Reimplemented in PropertyStrArray.
References Property_PROPERTY_TYPE_MISMATCH.
virtual void setValue (const Array< std::string > & aArray) [inline, virtual]
Reimplemented in PropertyStrArray.
References Property_PROPERTY_TYPE_MISMATCH.
virtual Array<std::string>& getValueStrArray () [inline, virtual]
Reimplemented in PropertyStrArray.
References Property_PROPERTY_TYPE_MISMATCH.
virtual const Array<std::string>& getValueStrArray () const [inline, virtual]
Reimplemented in PropertyStrArray.
References Property_PROPERTY_TYPE_MISMATCH.
virtual bool isValidObject (const Object * aValue) const [inline, virtual]
Reimplemented in PropertyObj, PropertyObjArray, PropertyObjPtr, PropertyObjArray< OpenSim::MarkerPair >, PropertyObjArray< OpenSim::IKTask >, PropertyObjArray< OpenSim::Measurement >, PropertyObjArray< OpenSim::AbstractCoordinate >, PropertyObjArray< OpenSim::ObjectGroup >, PropertyObjArray< OpenSim::AbstractDof01_05 >, PropertyObjArray< OpenSim::AbstractConstraint >, PropertyObjArray< OpenSim::AbstractTransformAxis >, PropertyObjArray< OpenSim::VisibleObject >, PropertyObjArray< OpenSim::Analysis >, PropertyObjArray< OpenSim::AbstractWrapObject >, PropertyObjArray< OpenSim::Callback >, PropertyObjArray< OpenSim::AbstractBody >, PropertyObjArray< OpenSim::rdCMC_Task >, PropertyObjArray< OpenSim::AbstractJoint >, PropertyObjArray< OpenSim::AbstractActuator >, PropertyObjArray< OpenSim::Material >, PropertyObjArray< OpenSim::IKTrial >, PropertyObjArray< OpenSim::AbstractMarker >, PropertyObjArray< OpenSim::Scale >, PropertyObjArray< OpenSim::ControlLinearNode >, PropertyObjArray< OpenSim::MuscleWrap >, PropertyObjArray< OpenSim::Function >, PropertyObjArray< OpenSim::AbstractSpeed >, PropertyObjArray< OpenSim::MusclePoint >, PropertyObjArray< OpenSim::Control >, PropertyObjArray< OpenSim::BodyScale >, PropertyObjPtr< OpenSim::AbstractDynamicsEngine >, PropertyObjPtr< OpenSim::Joint >, PropertyObjPtr< OpenSim::Controller >, and PropertyObjPtr< OpenSim::Function >.
References Property_PROPERTY_TYPE_MISMATCH.
virtual Object& getValueObj () [inline, virtual]
Reimplemented in PropertyObj.
References Property_PROPERTY_TYPE_MISMATCH.
virtual const Object& getValueObj () const [inline, virtual]
Reimplemented in PropertyObj.
References Property_PROPERTY_TYPE_MISMATCH.
virtual void setValue (Object * aValue) [inline, virtual]
Reimplemented in PropertyObjPtr, PropertyObjPtr< OpenSim::AbstractDynamicsEngine >, PropertyObjPtr< OpenSim::Joint >, PropertyObjPtr< OpenSim::Controller >, and PropertyObjPtr< OpenSim::Function >.
References Property_PROPERTY_TYPE_MISMATCH.
virtual Object* getValueObjPtr () [inline, virtual]
Reimplemented in PropertyObjPtr, PropertyObjPtr< OpenSim::AbstractDynamicsEngine >, PropertyObjPtr< OpenSim::Joint >, PropertyObjPtr< OpenSim::Controller >, and PropertyObjPtr< OpenSim::Function >.
References Property_PROPERTY_TYPE_MISMATCH.
virtual Object* getValueObjPtr (int index) [inline, virtual]
Reimplemented in PropertyObjArray, PropertyObjArray< OpenSim::MarkerPair >, PropertyObjArray< OpenSim::IKTask >, PropertyObjArray< OpenSim::Measurement >, PropertyObjArray< OpenSim::AbstractCoordinate >, PropertyObjArray< OpenSim::ObjectGroup >, PropertyObjArray< OpenSim::AbstractDof01_05 >, PropertyObjArray< OpenSim::AbstractConstraint >, PropertyObjArray< OpenSim::AbstractTransformAxis >, PropertyObjArray< OpenSim::VisibleObject >, PropertyObjArray< OpenSim::Analysis >, PropertyObjArray< OpenSim::AbstractWrapObject >, PropertyObjArray< OpenSim::Callback >, PropertyObjArray< OpenSim::AbstractBody >, PropertyObjArray< OpenSim::rdCMC_Task >, PropertyObjArray< OpenSim::AbstractJoint >, PropertyObjArray< OpenSim::AbstractActuator >, PropertyObjArray< OpenSim::Material >, PropertyObjArray< OpenSim::IKTrial >, PropertyObjArray< OpenSim::AbstractMarker >, PropertyObjArray< OpenSim::Scale >, PropertyObjArray< OpenSim::ControlLinearNode >, PropertyObjArray< OpenSim::MuscleWrap >, PropertyObjArray< OpenSim::Function >, PropertyObjArray< OpenSim::AbstractSpeed >, PropertyObjArray< OpenSim::MusclePoint >, PropertyObjArray< OpenSim::Control >, and PropertyObjArray< OpenSim::BodyScale >.
References Property_PROPERTY_TYPE_MISMATCH.
virtual void appendValue (Object * obj) [inline, virtual]
Reimplemented in PropertyObjArray, PropertyObjArray< OpenSim::MarkerPair >, PropertyObjArray< OpenSim::IKTask >, PropertyObjArray< OpenSim::Measurement >, PropertyObjArray< OpenSim::AbstractCoordinate >, PropertyObjArray< OpenSim::ObjectGroup >, PropertyObjArray< OpenSim::AbstractDof01_05 >, PropertyObjArray< OpenSim::AbstractConstraint >, PropertyObjArray< OpenSim::AbstractTransformAxis >, PropertyObjArray< OpenSim::VisibleObject >, PropertyObjArray< OpenSim::Analysis >, PropertyObjArray< OpenSim::AbstractWrapObject >, PropertyObjArray< OpenSim::Callback >, PropertyObjArray< OpenSim::AbstractBody >, PropertyObjArray< OpenSim::rdCMC_Task >, PropertyObjArray< OpenSim::AbstractJoint >, PropertyObjArray< OpenSim::AbstractActuator >, PropertyObjArray< OpenSim::Material >, PropertyObjArray< OpenSim::IKTrial >, PropertyObjArray< OpenSim::AbstractMarker >, PropertyObjArray< OpenSim::Scale >, PropertyObjArray< OpenSim::ControlLinearNode >, PropertyObjArray< OpenSim::MuscleWrap >, PropertyObjArray< OpenSim::Function >, PropertyObjArray< OpenSim::AbstractSpeed >, PropertyObjArray< OpenSim::MusclePoint >, PropertyObjArray< OpenSim::Control >, and PropertyObjArray< OpenSim::BodyScale >.
References Property_PROPERTY_TYPE_MISMATCH.
virtual void clearObjArray () [inline, virtual]
Reimplemented in PropertyObjArray, PropertyObjArray< OpenSim::MarkerPair >, PropertyObjArray< OpenSim::IKTask >, PropertyObjArray< OpenSim::Measurement >, PropertyObjArray< OpenSim::AbstractCoordinate >, PropertyObjArray< OpenSim::ObjectGroup >, PropertyObjArray< OpenSim::AbstractDof01_05 >, PropertyObjArray< OpenSim::AbstractConstraint >, PropertyObjArray< OpenSim::AbstractTransformAxis >, PropertyObjArray< OpenSim::VisibleObject >, PropertyObjArray< OpenSim::Analysis >, PropertyObjArray< OpenSim::AbstractWrapObject >, PropertyObjArray< OpenSim::Callback >, PropertyObjArray< OpenSim::AbstractBody >, PropertyObjArray< OpenSim::rdCMC_Task >, PropertyObjArray< OpenSim::AbstractJoint >, PropertyObjArray< OpenSim::AbstractActuator >, PropertyObjArray< OpenSim::Material >, PropertyObjArray< OpenSim::IKTrial >, PropertyObjArray< OpenSim::AbstractMarker >, PropertyObjArray< OpenSim::Scale >, PropertyObjArray< OpenSim::ControlLinearNode >, PropertyObjArray< OpenSim::MuscleWrap >, PropertyObjArray< OpenSim::Function >, PropertyObjArray< OpenSim::AbstractSpeed >, PropertyObjArray< OpenSim::MusclePoint >, PropertyObjArray< OpenSim::Control >, and PropertyObjArray< OpenSim::BodyScale >.
References Property_PROPERTY_TYPE_MISMATCH.
void setUseDefault (bool aTrueFalse)
bool getUseDefault () const
virtual int getArraySize () const [inline, virtual]
Reimplemented in PropertyBoolArray, PropertyDblArray, PropertyDblVec3, PropertyIntArray, PropertyObjArray, PropertyStrArray, PropertyObjArray< OpenSim::MarkerPair >, PropertyObjArray< OpenSim::IKTask >, PropertyObjArray< OpenSim::Measurement >, PropertyObjArray< OpenSim::AbstractCoordinate >, PropertyObjArray< OpenSim::ObjectGroup >, PropertyObjArray< OpenSim::AbstractDof01_05 >, PropertyObjArray< OpenSim::AbstractConstraint >, PropertyObjArray< OpenSim::AbstractTransformAxis >, PropertyObjArray< OpenSim::VisibleObject >, PropertyObjArray< OpenSim::Analysis >, PropertyObjArray< OpenSim::AbstractWrapObject >, PropertyObjArray< OpenSim::Callback >, PropertyObjArray< OpenSim::AbstractBody >, PropertyObjArray< OpenSim::rdCMC_Task >, PropertyObjArray< OpenSim::AbstractJoint >, PropertyObjArray< OpenSim::AbstractActuator >, PropertyObjArray< OpenSim::Material >, PropertyObjArray< OpenSim::IKTrial >, PropertyObjArray< OpenSim::AbstractMarker >, PropertyObjArray< OpenSim::Scale >, PropertyObjArray< OpenSim::ControlLinearNode >, PropertyObjArray< OpenSim::MuscleWrap >, PropertyObjArray< OpenSim::Function >, PropertyObjArray< OpenSim::AbstractSpeed >, PropertyObjArray< OpenSim::MusclePoint >, PropertyObjArray< OpenSim::Control >, and PropertyObjArray< OpenSim::BodyScale >.
References Property_PROPERTY_TYPE_MISMATCH.
std::string & getValue () [inline]
References Property::getValueBool().
const std::string & getValue () const [inline]
References Property::getValueBool().
Array< std::string > & getValueArray () [inline]
References Property::getValueBoolArray().
const Array< std::string > & getValueArray () const [inline]
References Property::getValueBoolArray().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & aOut, const Property & aProperty) [friend]
Member Data Documentation
std::string _comment [protected]
Comment to be associated with property, shown for default objects only for efficiency.
std::string _valueString [protected]
String representation of property.
Referenced by PropertyObjPtr< OpenSim::Function >::toString(), and PropertyObjArray< OpenSim::BodyScale >::toString().
The documentation for this class was generated from the following file:
Property.h