OpenSim: XMLNode Class Reference
XMLNode Class Reference
#include <XMLNode.h>
Public Member Functions
template<>
void SetValueArray (DOMNode *aNode, int aN, const bool *rData)
template<>
void SetValueArray (DOMNode *aNode, int aN, const int *rData)
template<>
void SetValueArray (DOMNode *aNode, int aN, const double *rData)
template<>
void SetValueArray (DOMNode *aNode, int aN, const std::string *rData)
template<>
int GetValueArray (const DOMNode *aNode, bool *&rData)
template<>
int GetValueArray (const DOMNode *aNode, int *&rData)
template<>
int GetValueArray (const DOMNode *aNode, double *&rData)
template<>
int GetValueArray (const DOMNode *aNode, std::string *&rData)
Static Public Member Functions
static int GetNumberOfParents (const DOMNode *node)
static std::string ToString (const DOMNode *aNode)
static std::string NodeContextString (const DOMNode *aNode)
static std::string Transcode (const XMLCh *aCh)
static std::string TranscodeAndTrim (const XMLCh *aCh)
static DOMElement * AppendNewElementWithComment (DOMNode *aParent, const std::string &aTag, const std::string &aName="", const std::string &aComment="")
static DOMElement * InsertNewElementWithComment (DOMNode *aParent, const std::string &aTag, const std::string &aName="", const std::string &aComment="", int aNodeIndex=0)
static void RemoveChildren (DOMNode *aNode)
static DOMNode * FindInsertionPoint (DOMNode *aElement, int aNodeIndex)
static void RemoveElementFromParent (DOMElement *aElement, bool aRemoveWhitespaceAndComments=true)
static void UpdateCommentNodeCorrespondingToChildElement (DOMElement *aElement, const std::string &aComment)
static DOMText * CreateDOMText (DOMDocument *aDocument, const std::string &aText)
static DOMComment * CreateDOMComment (DOMDocument *aDocument, const std::string &aComment)
static DOMElement * CreateDOMElement (DOMDocument *aDocument, const std::string &aTag)
static DOMElement * GetFirstChildElementByTagName (const DOMNode *aNode, const std::string &aTagName, const std::string *aName=0, bool aCheckForMultiple=true)
static DOMCharacterData * GetCDataSectionNode (const DOMNode *aNode)
static DOMText * GetTextNode (const DOMNode *aNode)
static bool GetBool (const DOMNode *aNode)
static int GetInt (const DOMNode *aNode)
static double GetDbl (const DOMNode *aNode)
static std::string GetStr (const DOMNode *aNode)
static void SetBoolArray (DOMNode *aNode, int aN, const bool *aData)
static int GetBoolArray (const DOMNode *aNode, bool *&rData)
static void SetIntArray (DOMNode *aNode, int aN, const int *aData)
static int GetIntArray (const DOMNode *aNode, int *&rData)
static void SetDblArray (DOMNode *aNode, int aN, const double *aData)
static int GetDblArray (const DOMNode *aNode, double *&rData)
static void SetStrArray (DOMNode *aNode, int aN, const std::string *aData)
static int GetStrArray (const DOMNode *aNode, std::string *&rData)
template<class T>
static T GetValue (const DOMNode *aNode)
template<class T>
static void SetValueArray (DOMNode *aNode, int aN, const T *rData)
template<class T>
static int GetValueArray (const DOMNode *aNode, T *&rData)
static void SetAttribute (DOMNode *aNode, const std::string &aName, const std::string &aValue)
static std::string GetAttribute (DOMNode *aNode, const std::string &aName)
static void RemoveAttribute (DOMNode *aNode, const std::string &aName)
Member Function Documentation
static int GetNumberOfParents (const DOMNode * node) [static]
static std::string ToString (const DOMNode * aNode) [static]
static std::string NodeContextString (const DOMNode * aNode) [static]
static std::string Transcode (const XMLCh * aCh) [static]
static std::string TranscodeAndTrim (const XMLCh * aCh) [static]
static DOMElement* AppendNewElementWithComment (DOMNode * aParent, const std::string & aTag, const std::string & aName = "", const std::string & aComment = "") [static]
static DOMElement* InsertNewElementWithComment (DOMNode * aParent, const std::string & aTag, const std::string & aName = "", const std::string & aComment = "", int aNodeIndex = 0) [static]
static void RemoveChildren (DOMNode * aNode) [static]
static DOMNode* FindInsertionPoint (DOMNode * aElement, int aNodeIndex) [static]
static void RemoveElementFromParent (DOMElement * aElement, bool aRemoveWhitespaceAndComments = true) [static]
static void UpdateCommentNodeCorrespondingToChildElement (DOMElement * aElement, const std::string & aComment) [static]
static DOMText* CreateDOMText (DOMDocument * aDocument, const std::string & aText) [static]
static DOMComment* CreateDOMComment (DOMDocument * aDocument, const std::string & aComment) [static]
static DOMElement* CreateDOMElement (DOMDocument * aDocument, const std::string & aTag) [static]
static DOMElement* GetFirstChildElementByTagName (const DOMNode * aNode, const std::string & aTagName, const std::string * aName = 0, bool aCheckForMultiple = true) [static]
static DOMCharacterData* GetCDataSectionNode (const DOMNode * aNode) [static]
static DOMText* GetTextNode (const DOMNode * aNode) [static]
static bool GetBool (const DOMNode * aNode) [static]
Referenced by XMLNode::GetValue().
static int GetInt (const DOMNode * aNode) [static]
static double GetDbl (const DOMNode * aNode) [static]
static std::string GetStr (const DOMNode * aNode) [static]
static void SetBoolArray (DOMNode * aNode, int aN, const bool * aData) [static]
Referenced by XMLNode::SetValueArray().
static int GetBoolArray (const DOMNode * aNode, bool *& rData) [static]
Referenced by XMLNode::GetValueArray().
static void SetIntArray (DOMNode * aNode, int aN, const int * aData) [static]
Referenced by XMLNode::SetValueArray().
static int GetIntArray (const DOMNode * aNode, int *& rData) [static]
Referenced by XMLNode::GetValueArray().
static void SetDblArray (DOMNode * aNode, int aN, const double * aData) [static]
Referenced by XMLNode::SetValueArray().
static int GetDblArray (const DOMNode * aNode, double *& rData) [static]
Referenced by XMLNode::GetValueArray().
static void SetStrArray (DOMNode * aNode, int aN, const std::string * aData) [static]
Referenced by XMLNode::SetValueArray().
static int GetStrArray (const DOMNode * aNode, std::string *& rData) [static]
Referenced by XMLNode::GetValueArray().
std::string GetValue (const DOMNode * aNode) [inline, static]
References XMLNode::GetBool().
static void SetValueArray (DOMNode * aNode, int aN, const T * rData) [inline, static]
static int GetValueArray (const DOMNode * aNode, T *& rData) [inline, static]
static void SetAttribute (DOMNode * aNode, const std::string & aName, const std::string & aValue) [static]
static std::string GetAttribute (DOMNode * aNode, const std::string & aName) [static]
static void RemoveAttribute (DOMNode * aNode, const std::string & aName) [static]
void SetValueArray (DOMNode * aNode, int aN, const bool * rData) [inline]
References XMLNode::SetBoolArray().
void SetValueArray (DOMNode * aNode, int aN, const int * rData) [inline]
References XMLNode::SetIntArray().
void SetValueArray (DOMNode * aNode, int aN, const double * rData) [inline]
References XMLNode::SetDblArray().
void SetValueArray (DOMNode * aNode, int aN, const std::string * rData) [inline]
References XMLNode::SetStrArray().
int GetValueArray (const DOMNode * aNode, bool *& rData) [inline]
References XMLNode::GetBoolArray().
int GetValueArray (const DOMNode * aNode, int *& rData) [inline]
References XMLNode::GetIntArray().
int GetValueArray (const DOMNode * aNode, double *& rData) [inline]
References XMLNode::GetDblArray().
int GetValueArray (const DOMNode * aNode, std::string *& rData) [inline]
References XMLNode::GetStrArray().
The documentation for this class was generated from the following file:
XMLNode.h