# Makefile for compiling the simulation modules.

#=============================
# RULES
#=============================
all :
	cd Block;			make;  cd ..;
	cd UTWalking8;		make;  cd ..;
	cd UTWalking9;		make;  cd ..;

clean :
	cd Block;			make clean;  cd ..;
	cd UTWalking8;		make clean;  cd ..;
	cd UTWalking9;		make clean;  cd ..;
