/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.19
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package simtkcgmalWalking01Pkg;

import simtkModel.*;

public class cgmalWalking01 extends rdActuatedModel_SDFast {
  private long swigCPtr;

  protected cgmalWalking01(long cPtr, boolean cMemoryOwn) {
    super(cgmalWalking01ModuleJNI.SWIGcgmalWalking01TordActuatedModel_SDFast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected cgmalWalking01() {
    this(0, false);
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      cgmalWalking01ModuleJNI.delete_cgmalWalking01(swigCPtr);
      swigCMemOwn = false;
      super.delete();
    }
    swigCPtr = 0;
  }

  protected static long getCPtr(cgmalWalking01 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public cgmalWalking01(rdActuatorSet aActuatorSet, rdContactForceSet aContacts) {
    this(cgmalWalking01ModuleJNI.new_cgmalWalking01(rdActuatorSet.getCPtr(aActuatorSet), rdContactForceSet.getCPtr(aContacts)), true);
  }

  public static void RegisterTypes() {
    cgmalWalking01ModuleJNI.cgmalWalking01_RegisterTypes();
  }

}
