/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.19
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package simtkBlock;


public class rdSDFast extends rdModel {
  private long swigCPtr;

  protected rdSDFast(long cPtr, boolean cMemoryOwn) {
    super(rdBlockModuleJNI.SWIGrdSDFastTordModel(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected rdSDFast() {
    this(0, false);
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      rdBlockModuleJNI.delete_rdSDFast(swigCPtr);
      swigCMemOwn = false;
      super.delete();
    }
    swigCPtr = 0;
  }

  protected static long getCPtr(rdSDFast obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public void setGravity(SWIGTYPE_p_double aGrav) {
    rdBlockModuleJNI.rdSDFast_setGravity(swigCPtr, SWIGTYPE_p_double.getCPtr(aGrav));
  }

  public void getGravity(SWIGTYPE_p_double rGrav) {
    rdBlockModuleJNI.rdSDFast_getGravity(swigCPtr, SWIGTYPE_p_double.getCPtr(rGrav));
  }

  public void setConfiguration(SWIGTYPE_p_double aQ, SWIGTYPE_p_double aU) {
    rdBlockModuleJNI.rdSDFast_setConfiguration__SWIG_0(swigCPtr, SWIGTYPE_p_double.getCPtr(aQ), SWIGTYPE_p_double.getCPtr(aU));
  }

  public void setConfiguration(SWIGTYPE_p_double aY) {
    rdBlockModuleJNI.rdSDFast_setConfiguration__SWIG_1(swigCPtr, SWIGTYPE_p_double.getCPtr(aY));
  }

  public int getGroundID() {
    return rdBlockModuleJNI.rdSDFast_getGroundID(swigCPtr);
  }

  public void setBodyToJointBodyLocal(int aBody, SWIGTYPE_p_double aBTJ) {
    rdBlockModuleJNI.rdSDFast_setBodyToJointBodyLocal(swigCPtr, aBody, SWIGTYPE_p_double.getCPtr(aBTJ));
  }

  public void getBodyToJointBodyLocal(int aBody, SWIGTYPE_p_double rBTJ) {
    rdBlockModuleJNI.rdSDFast_getBodyToJointBodyLocal(swigCPtr, aBody, SWIGTYPE_p_double.getCPtr(rBTJ));
  }

  public void setInboardToJointBodyLocal(int aBody, SWIGTYPE_p_double aBTJ) {
    rdBlockModuleJNI.rdSDFast_setInboardToJointBodyLocal(swigCPtr, aBody, SWIGTYPE_p_double.getCPtr(aBTJ));
  }

  public void getInboardToJointBodyLocal(int aBody, SWIGTYPE_p_double rITJ) {
    rdBlockModuleJNI.rdSDFast_getInboardToJointBodyLocal(swigCPtr, aBody, SWIGTYPE_p_double.getCPtr(rITJ));
  }

  public double getMass(int aBody) {
    return rdBlockModuleJNI.rdSDFast_getMass(swigCPtr, aBody);
  }

  public int getInertiaBodyLocal(int aBody, SWIGTYPE_p_a_3__double rI) {
    return rdBlockModuleJNI.rdSDFast_getInertiaBodyLocal__SWIG_0(swigCPtr, aBody, SWIGTYPE_p_a_3__double.getCPtr(rI));
  }

  public int getInertiaBodyLocal(int aBody, SWIGTYPE_p_double rI) {
    return rdBlockModuleJNI.rdSDFast_getInertiaBodyLocal__SWIG_1(swigCPtr, aBody, SWIGTYPE_p_double.getCPtr(rI));
  }

  public void getSystemInertia(SWIGTYPE_p_double rM, SWIGTYPE_p_double rCOM, SWIGTYPE_p_a_3__double rI) {
    rdBlockModuleJNI.rdSDFast_getSystemInertia__SWIG_0(swigCPtr, SWIGTYPE_p_double.getCPtr(rM), SWIGTYPE_p_double.getCPtr(rCOM), SWIGTYPE_p_a_3__double.getCPtr(rI));
  }

  public void getSystemInertia(SWIGTYPE_p_double rM, SWIGTYPE_p_double rCOM, SWIGTYPE_p_double rI) {
    rdBlockModuleJNI.rdSDFast_getSystemInertia__SWIG_1(swigCPtr, SWIGTYPE_p_double.getCPtr(rM), SWIGTYPE_p_double.getCPtr(rCOM), SWIGTYPE_p_double.getCPtr(rI));
  }

  public void getPosition(int aBody, SWIGTYPE_p_double aPoint, SWIGTYPE_p_double rPos) {
    rdBlockModuleJNI.rdSDFast_getPosition(swigCPtr, aBody, SWIGTYPE_p_double.getCPtr(aPoint), SWIGTYPE_p_double.getCPtr(rPos));
  }

  public void getVelocity(int aBody, SWIGTYPE_p_double aPoint, SWIGTYPE_p_double rVel) {
    rdBlockModuleJNI.rdSDFast_getVelocity(swigCPtr, aBody, SWIGTYPE_p_double.getCPtr(aPoint), SWIGTYPE_p_double.getCPtr(rVel));
  }

  public void getAcceleration(int aBody, SWIGTYPE_p_double aPoint, SWIGTYPE_p_double rAcc) {
    rdBlockModuleJNI.rdSDFast_getAcceleration(swigCPtr, aBody, SWIGTYPE_p_double.getCPtr(aPoint), SWIGTYPE_p_double.getCPtr(rAcc));
  }

  public void getDirectionCosines(int aBody, SWIGTYPE_p_a_3__double rDirCos) {
    rdBlockModuleJNI.rdSDFast_getDirectionCosines__SWIG_0(swigCPtr, aBody, SWIGTYPE_p_a_3__double.getCPtr(rDirCos));
  }

  public void getDirectionCosines(int aBody, SWIGTYPE_p_double rDirCos) {
    rdBlockModuleJNI.rdSDFast_getDirectionCosines__SWIG_1(swigCPtr, aBody, SWIGTYPE_p_double.getCPtr(rDirCos));
  }

  public void getAngularVelocity(int aBody, SWIGTYPE_p_double rAngVel) {
    rdBlockModuleJNI.rdSDFast_getAngularVelocity(swigCPtr, aBody, SWIGTYPE_p_double.getCPtr(rAngVel));
  }

  public void getAngularVelocityBodyLocal(int aBody, SWIGTYPE_p_double rAngVel) {
    rdBlockModuleJNI.rdSDFast_getAngularVelocityBodyLocal(swigCPtr, aBody, SWIGTYPE_p_double.getCPtr(rAngVel));
  }

  public void getAngularAcceleration(int aBody, SWIGTYPE_p_double rAngAcc) {
    rdBlockModuleJNI.rdSDFast_getAngularAcceleration(swigCPtr, aBody, SWIGTYPE_p_double.getCPtr(rAngAcc));
  }

  public void getAngularAccelerationBodyLocal(int aBody, SWIGTYPE_p_double rAngAcc) {
    rdBlockModuleJNI.rdSDFast_getAngularAccelerationBodyLocal(swigCPtr, aBody, SWIGTYPE_p_double.getCPtr(rAngAcc));
  }

  public void applyForce(int aBody, SWIGTYPE_p_double aPoint, SWIGTYPE_p_double aForce) {
    rdBlockModuleJNI.rdSDFast_applyForce(swigCPtr, aBody, SWIGTYPE_p_double.getCPtr(aPoint), SWIGTYPE_p_double.getCPtr(aForce));
  }

  public void applyForces(int aN, SWIGTYPE_p_int aBodies, SWIGTYPE_p_a_3__double aPoints, SWIGTYPE_p_a_3__double aForces) {
    rdBlockModuleJNI.rdSDFast_applyForces__SWIG_0(swigCPtr, aN, SWIGTYPE_p_int.getCPtr(aBodies), SWIGTYPE_p_a_3__double.getCPtr(aPoints), SWIGTYPE_p_a_3__double.getCPtr(aForces));
  }

  public void applyForces(int aN, SWIGTYPE_p_int aBodies, SWIGTYPE_p_double aPoints, SWIGTYPE_p_double aForces) {
    rdBlockModuleJNI.rdSDFast_applyForces__SWIG_1(swigCPtr, aN, SWIGTYPE_p_int.getCPtr(aBodies), SWIGTYPE_p_double.getCPtr(aPoints), SWIGTYPE_p_double.getCPtr(aForces));
  }

  public void applyForceBodyLocal(int aBody, SWIGTYPE_p_double aPoint, SWIGTYPE_p_double aForce) {
    rdBlockModuleJNI.rdSDFast_applyForceBodyLocal(swigCPtr, aBody, SWIGTYPE_p_double.getCPtr(aPoint), SWIGTYPE_p_double.getCPtr(aForce));
  }

  public void applyForcesBodyLocal(int aN, SWIGTYPE_p_int aBodies, SWIGTYPE_p_a_3__double aPoints, SWIGTYPE_p_a_3__double aForces) {
    rdBlockModuleJNI.rdSDFast_applyForcesBodyLocal__SWIG_0(swigCPtr, aN, SWIGTYPE_p_int.getCPtr(aBodies), SWIGTYPE_p_a_3__double.getCPtr(aPoints), SWIGTYPE_p_a_3__double.getCPtr(aForces));
  }

  public void applyForcesBodyLocal(int aN, SWIGTYPE_p_int aBodies, SWIGTYPE_p_double aPoints, SWIGTYPE_p_double aForces) {
    rdBlockModuleJNI.rdSDFast_applyForcesBodyLocal__SWIG_1(swigCPtr, aN, SWIGTYPE_p_int.getCPtr(aBodies), SWIGTYPE_p_double.getCPtr(aPoints), SWIGTYPE_p_double.getCPtr(aForces));
  }

  public void applyTorque(int aBody, SWIGTYPE_p_double aTorque) {
    rdBlockModuleJNI.rdSDFast_applyTorque(swigCPtr, aBody, SWIGTYPE_p_double.getCPtr(aTorque));
  }

  public void applyTorques(int aN, SWIGTYPE_p_int aBodies, SWIGTYPE_p_a_3__double aTorques) {
    rdBlockModuleJNI.rdSDFast_applyTorques__SWIG_0(swigCPtr, aN, SWIGTYPE_p_int.getCPtr(aBodies), SWIGTYPE_p_a_3__double.getCPtr(aTorques));
  }

  public void applyTorques(int aN, SWIGTYPE_p_int aBodies, SWIGTYPE_p_double aTorques) {
    rdBlockModuleJNI.rdSDFast_applyTorques__SWIG_1(swigCPtr, aN, SWIGTYPE_p_int.getCPtr(aBodies), SWIGTYPE_p_double.getCPtr(aTorques));
  }

  public void applyTorqueBodyLocal(int aBody, SWIGTYPE_p_double aTorque) {
    rdBlockModuleJNI.rdSDFast_applyTorqueBodyLocal(swigCPtr, aBody, SWIGTYPE_p_double.getCPtr(aTorque));
  }

  public void applyTorquesBodyLocal(int aN, SWIGTYPE_p_int aBodies, SWIGTYPE_p_a_3__double aTorques) {
    rdBlockModuleJNI.rdSDFast_applyTorquesBodyLocal__SWIG_0(swigCPtr, aN, SWIGTYPE_p_int.getCPtr(aBodies), SWIGTYPE_p_a_3__double.getCPtr(aTorques));
  }

  public void applyTorquesBodyLocal(int aN, SWIGTYPE_p_int aBodies, SWIGTYPE_p_double aTorques) {
    rdBlockModuleJNI.rdSDFast_applyTorquesBodyLocal__SWIG_1(swigCPtr, aN, SWIGTYPE_p_int.getCPtr(aBodies), SWIGTYPE_p_double.getCPtr(aTorques));
  }

  public void applyGeneralizedForce(int aU, double aF) {
    rdBlockModuleJNI.rdSDFast_applyGeneralizedForce(swigCPtr, aU, aF);
  }

  public void applyGeneralizedForces(SWIGTYPE_p_double aF) {
    rdBlockModuleJNI.rdSDFast_applyGeneralizedForces__SWIG_0(swigCPtr, SWIGTYPE_p_double.getCPtr(aF));
  }

  public void applyGeneralizedForces(int aN, SWIGTYPE_p_int aU, SWIGTYPE_p_double aF) {
    rdBlockModuleJNI.rdSDFast_applyGeneralizedForces__SWIG_1(swigCPtr, aN, SWIGTYPE_p_int.getCPtr(aU), SWIGTYPE_p_double.getCPtr(aF));
  }

  public double getNetAppliedGeneralizedForce(int aU) {
    return rdBlockModuleJNI.rdSDFast_getNetAppliedGeneralizedForce(swigCPtr, aU);
  }

  public void computeGeneralizedForces(SWIGTYPE_p_double aDUDT, SWIGTYPE_p_double rF) {
    rdBlockModuleJNI.rdSDFast_computeGeneralizedForces(swigCPtr, SWIGTYPE_p_double.getCPtr(aDUDT), SWIGTYPE_p_double.getCPtr(rF));
  }

  public int computeAccelerations(SWIGTYPE_p_double dqdt, SWIGTYPE_p_double dudt) {
    return rdBlockModuleJNI.rdSDFast_computeAccelerations(swigCPtr, SWIGTYPE_p_double.getCPtr(dqdt), SWIGTYPE_p_double.getCPtr(dudt));
  }

  public void formMassMatrix(SWIGTYPE_p_double rI) {
    rdBlockModuleJNI.rdSDFast_formMassMatrix(swigCPtr, SWIGTYPE_p_double.getCPtr(rI));
  }

  public void formEulerTransform(int aBody, SWIGTYPE_p_double rE) {
    rdBlockModuleJNI.rdSDFast_formEulerTransform(swigCPtr, aBody, SWIGTYPE_p_double.getCPtr(rE));
  }

  public void formJacobianTranslation(int aBody, SWIGTYPE_p_double aBodyPoint, SWIGTYPE_p_double rJ, int aRefBody) {
    rdBlockModuleJNI.rdSDFast_formJacobianTranslation(swigCPtr, aBody, SWIGTYPE_p_double.getCPtr(aBodyPoint), SWIGTYPE_p_double.getCPtr(rJ), aRefBody);
  }

  public void formJacobianOrientation(int aBody, SWIGTYPE_p_double rJ0, int aRefBody) {
    rdBlockModuleJNI.rdSDFast_formJacobianOrientation(swigCPtr, aBody, SWIGTYPE_p_double.getCPtr(rJ0), aRefBody);
  }

  public void formJacobianEuler(int aBody, SWIGTYPE_p_double rJE, int aRefBody) {
    rdBlockModuleJNI.rdSDFast_formJacobianEuler(swigCPtr, aBody, SWIGTYPE_p_double.getCPtr(rJE), aRefBody);
  }

  public void transform(int aBody1, SWIGTYPE_p_double aVec1, int aBody2, SWIGTYPE_p_double rVec2) {
    rdBlockModuleJNI.rdSDFast_transform(swigCPtr, aBody1, SWIGTYPE_p_double.getCPtr(aVec1), aBody2, SWIGTYPE_p_double.getCPtr(rVec2));
  }

  public void convertQuaternionsToAngles(SWIGTYPE_p_double aQ, SWIGTYPE_p_double rQAng) {
    rdBlockModuleJNI.rdSDFast_convertQuaternionsToAngles__SWIG_0(swigCPtr, SWIGTYPE_p_double.getCPtr(aQ), SWIGTYPE_p_double.getCPtr(rQAng));
  }

  public void convertQuaternionsToAngles(SWIGTYPE_p_rdStorage rQStore) {
    rdBlockModuleJNI.rdSDFast_convertQuaternionsToAngles__SWIG_1(swigCPtr, SWIGTYPE_p_rdStorage.getCPtr(rQStore));
  }

  public void convertAnglesToQuaternions(SWIGTYPE_p_double aQAng, SWIGTYPE_p_double rQ) {
    rdBlockModuleJNI.rdSDFast_convertAnglesToQuaternions__SWIG_0(swigCPtr, SWIGTYPE_p_double.getCPtr(aQAng), SWIGTYPE_p_double.getCPtr(rQ));
  }

  public void convertAnglesToQuaternions(SWIGTYPE_p_rdStorage rQStore) {
    rdBlockModuleJNI.rdSDFast_convertAnglesToQuaternions__SWIG_1(swigCPtr, SWIGTYPE_p_rdStorage.getCPtr(rQStore));
  }

  public void convertRadiansToDegrees(SWIGTYPE_p_double aQRad, SWIGTYPE_p_double rQDeg) {
    rdBlockModuleJNI.rdSDFast_convertRadiansToDegrees__SWIG_0(swigCPtr, SWIGTYPE_p_double.getCPtr(aQRad), SWIGTYPE_p_double.getCPtr(rQDeg));
  }

  public void convertRadiansToDegrees(SWIGTYPE_p_rdStorage rQStore) {
    rdBlockModuleJNI.rdSDFast_convertRadiansToDegrees__SWIG_1(swigCPtr, SWIGTYPE_p_rdStorage.getCPtr(rQStore));
  }

  public void convertDegreesToRadians(SWIGTYPE_p_double aQDeg, SWIGTYPE_p_double rQRad) {
    rdBlockModuleJNI.rdSDFast_convertDegreesToRadians__SWIG_0(swigCPtr, SWIGTYPE_p_double.getCPtr(aQDeg), SWIGTYPE_p_double.getCPtr(rQRad));
  }

  public void convertDegreesToRadians(SWIGTYPE_p_rdStorage rQStore) {
    rdBlockModuleJNI.rdSDFast_convertDegreesToRadians__SWIG_1(swigCPtr, SWIGTYPE_p_rdStorage.getCPtr(rQStore));
  }

  public void convertAnglesToDirectionCosines(double aE1, double aE2, double aE3, SWIGTYPE_p_a_3__double rDirCos) {
    rdBlockModuleJNI.rdSDFast_convertAnglesToDirectionCosines__SWIG_0(swigCPtr, aE1, aE2, aE3, SWIGTYPE_p_a_3__double.getCPtr(rDirCos));
  }

  public void convertAnglesToDirectionCosines(double aE1, double aE2, double aE3, SWIGTYPE_p_double rDirCos) {
    rdBlockModuleJNI.rdSDFast_convertAnglesToDirectionCosines__SWIG_1(swigCPtr, aE1, aE2, aE3, SWIGTYPE_p_double.getCPtr(rDirCos));
  }

  public void convertDirectionCosinesToAngles(SWIGTYPE_p_a_3__double aDirCos, SWIGTYPE_p_double rE1, SWIGTYPE_p_double rE2, SWIGTYPE_p_double rE3) {
    rdBlockModuleJNI.rdSDFast_convertDirectionCosinesToAngles__SWIG_0(swigCPtr, SWIGTYPE_p_a_3__double.getCPtr(aDirCos), SWIGTYPE_p_double.getCPtr(rE1), SWIGTYPE_p_double.getCPtr(rE2), SWIGTYPE_p_double.getCPtr(rE3));
  }

  public void convertDirectionCosinesToAngles(SWIGTYPE_p_double aDirCos, SWIGTYPE_p_double rE1, SWIGTYPE_p_double rE2, SWIGTYPE_p_double rE3) {
    rdBlockModuleJNI.rdSDFast_convertDirectionCosinesToAngles__SWIG_1(swigCPtr, SWIGTYPE_p_double.getCPtr(aDirCos), SWIGTYPE_p_double.getCPtr(rE1), SWIGTYPE_p_double.getCPtr(rE2), SWIGTYPE_p_double.getCPtr(rE3));
  }

  public void convertDirectionCosinesToQuaternions(SWIGTYPE_p_a_3__double aDirCos, SWIGTYPE_p_double rQ1, SWIGTYPE_p_double rQ2, SWIGTYPE_p_double rQ3, SWIGTYPE_p_double rQ4) {
    rdBlockModuleJNI.rdSDFast_convertDirectionCosinesToQuaternions__SWIG_0(swigCPtr, SWIGTYPE_p_a_3__double.getCPtr(aDirCos), SWIGTYPE_p_double.getCPtr(rQ1), SWIGTYPE_p_double.getCPtr(rQ2), SWIGTYPE_p_double.getCPtr(rQ3), SWIGTYPE_p_double.getCPtr(rQ4));
  }

  public void convertDirectionCosinesToQuaternions(SWIGTYPE_p_double aDirCos, SWIGTYPE_p_double rQ1, SWIGTYPE_p_double rQ2, SWIGTYPE_p_double rQ3, SWIGTYPE_p_double rQ4) {
    rdBlockModuleJNI.rdSDFast_convertDirectionCosinesToQuaternions__SWIG_1(swigCPtr, SWIGTYPE_p_double.getCPtr(aDirCos), SWIGTYPE_p_double.getCPtr(rQ1), SWIGTYPE_p_double.getCPtr(rQ2), SWIGTYPE_p_double.getCPtr(rQ3), SWIGTYPE_p_double.getCPtr(rQ4));
  }

  public void convertQuaternionsToDirectionCosines(double aQ1, double aQ2, double aQ3, double aQ4, SWIGTYPE_p_a_3__double rDirCos) {
    rdBlockModuleJNI.rdSDFast_convertQuaternionsToDirectionCosines__SWIG_0(swigCPtr, aQ1, aQ2, aQ3, aQ4, SWIGTYPE_p_a_3__double.getCPtr(rDirCos));
  }

  public void convertQuaternionsToDirectionCosines(double aQ1, double aQ2, double aQ3, double aQ4, SWIGTYPE_p_double rDirCos) {
    rdBlockModuleJNI.rdSDFast_convertQuaternionsToDirectionCosines__SWIG_1(swigCPtr, aQ1, aQ2, aQ3, aQ4, SWIGTYPE_p_double.getCPtr(rDirCos));
  }

}
